// pipeline.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module pipeline (
		input  wire        clk_clk,                                                     //                                           clk.clk
		input  wire [23:0] intel_vvp_clipper_0_axi4s_vid_in_tdata,                      //              intel_vvp_clipper_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_clipper_0_axi4s_vid_in_tvalid,                     //                                              .tvalid
		output wire        intel_vvp_clipper_0_axi4s_vid_in_tready,                     //                                              .tready
		input  wire        intel_vvp_clipper_0_axi4s_vid_in_tlast,                      //                                              .tlast
		input  wire [2:0]  intel_vvp_clipper_0_axi4s_vid_in_tuser,                      //                                              .tuser
		output wire [23:0] intel_vvp_clipper_0_axi4s_vid_out_tdata,                     //             intel_vvp_clipper_0_axi4s_vid_out.tdata
		output wire        intel_vvp_clipper_0_axi4s_vid_out_tvalid,                    //                                              .tvalid
		input  wire        intel_vvp_clipper_0_axi4s_vid_out_tready,                    //                                              .tready
		output wire        intel_vvp_clipper_0_axi4s_vid_out_tlast,                     //                                              .tlast
		output wire [2:0]  intel_vvp_clipper_0_axi4s_vid_out_tuser,                     //                                              .tuser
		input  wire [23:0] intel_vvp_crs_0_axi4s_vid_in_tdata,                          //                  intel_vvp_crs_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_crs_0_axi4s_vid_in_tvalid,                         //                                              .tvalid
		output wire        intel_vvp_crs_0_axi4s_vid_in_tready,                         //                                              .tready
		input  wire        intel_vvp_crs_0_axi4s_vid_in_tlast,                          //                                              .tlast
		input  wire [2:0]  intel_vvp_crs_0_axi4s_vid_in_tuser,                          //                                              .tuser
		output wire [23:0] intel_vvp_crs_0_axi4s_vid_out_tdata,                         //                 intel_vvp_crs_0_axi4s_vid_out.tdata
		output wire        intel_vvp_crs_0_axi4s_vid_out_tvalid,                        //                                              .tvalid
		input  wire        intel_vvp_crs_0_axi4s_vid_out_tready,                        //                                              .tready
		output wire        intel_vvp_crs_0_axi4s_vid_out_tlast,                         //                                              .tlast
		output wire [2:0]  intel_vvp_crs_0_axi4s_vid_out_tuser,                         //                                              .tuser
		input  wire [23:0] intel_vvp_csc_0_axi4s_vid_in_tdata,                          //                  intel_vvp_csc_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_csc_0_axi4s_vid_in_tvalid,                         //                                              .tvalid
		output wire        intel_vvp_csc_0_axi4s_vid_in_tready,                         //                                              .tready
		input  wire        intel_vvp_csc_0_axi4s_vid_in_tlast,                          //                                              .tlast
		input  wire [2:0]  intel_vvp_csc_0_axi4s_vid_in_tuser,                          //                                              .tuser
		output wire [23:0] intel_vvp_csc_0_axi4s_vid_out_tdata,                         //                 intel_vvp_csc_0_axi4s_vid_out.tdata
		output wire        intel_vvp_csc_0_axi4s_vid_out_tvalid,                        //                                              .tvalid
		input  wire        intel_vvp_csc_0_axi4s_vid_out_tready,                        //                                              .tready
		output wire        intel_vvp_csc_0_axi4s_vid_out_tlast,                         //                                              .tlast
		output wire [2:0]  intel_vvp_csc_0_axi4s_vid_out_tuser,                         //                                              .tuser
		input  wire [23:0] intel_vvp_dil_0_axi4s_vid_in_tdata,                          //                  intel_vvp_dil_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_dil_0_axi4s_vid_in_tvalid,                         //                                              .tvalid
		output wire        intel_vvp_dil_0_axi4s_vid_in_tready,                         //                                              .tready
		input  wire        intel_vvp_dil_0_axi4s_vid_in_tlast,                          //                                              .tlast
		input  wire [2:0]  intel_vvp_dil_0_axi4s_vid_in_tuser,                          //                                              .tuser
		output wire [23:0] intel_vvp_dil_0_axi4s_vid_out_tdata,                         //                 intel_vvp_dil_0_axi4s_vid_out.tdata
		output wire        intel_vvp_dil_0_axi4s_vid_out_tvalid,                        //                                              .tvalid
		input  wire        intel_vvp_dil_0_axi4s_vid_out_tready,                        //                                              .tready
		output wire        intel_vvp_dil_0_axi4s_vid_out_tlast,                         //                                              .tlast
		output wire [2:0]  intel_vvp_dil_0_axi4s_vid_out_tuser,                         //                                              .tuser
		input  wire [23:0] intel_vvp_protocol_conv_0_axi4s_vid_in_tdata,                //        intel_vvp_protocol_conv_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_protocol_conv_0_axi4s_vid_in_tvalid,               //                                              .tvalid
		output wire        intel_vvp_protocol_conv_0_axi4s_vid_in_tready,               //                                              .tready
		input  wire        intel_vvp_protocol_conv_0_axi4s_vid_in_tlast,                //                                              .tlast
		input  wire [2:0]  intel_vvp_protocol_conv_0_axi4s_vid_in_tuser,                //                                              .tuser
		output wire [23:0] intel_vvp_protocol_conv_0_axi4s_vid_out_tdata,               //       intel_vvp_protocol_conv_0_axi4s_vid_out.tdata
		output wire        intel_vvp_protocol_conv_0_axi4s_vid_out_tvalid,              //                                              .tvalid
		input  wire        intel_vvp_protocol_conv_0_axi4s_vid_out_tready,              //                                              .tready
		output wire        intel_vvp_protocol_conv_0_axi4s_vid_out_tlast,               //                                              .tlast
		output wire [2:0]  intel_vvp_protocol_conv_0_axi4s_vid_out_tuser,               //                                              .tuser
		input  wire [23:0] intel_vvp_protocol_conv_1_axi4s_vid_in_tdata,                //        intel_vvp_protocol_conv_1_axi4s_vid_in.tdata
		input  wire        intel_vvp_protocol_conv_1_axi4s_vid_in_tvalid,               //                                              .tvalid
		output wire        intel_vvp_protocol_conv_1_axi4s_vid_in_tready,               //                                              .tready
		input  wire        intel_vvp_protocol_conv_1_axi4s_vid_in_tlast,                //                                              .tlast
		input  wire [2:0]  intel_vvp_protocol_conv_1_axi4s_vid_in_tuser,                //                                              .tuser
		output wire [23:0] intel_vvp_protocol_conv_1_axi4s_vid_out_tdata,               //       intel_vvp_protocol_conv_1_axi4s_vid_out.tdata
		output wire        intel_vvp_protocol_conv_1_axi4s_vid_out_tvalid,              //                                              .tvalid
		input  wire        intel_vvp_protocol_conv_1_axi4s_vid_out_tready,              //                                              .tready
		output wire        intel_vvp_protocol_conv_1_axi4s_vid_out_tlast,               //                                              .tlast
		output wire [2:0]  intel_vvp_protocol_conv_1_axi4s_vid_out_tuser,               //                                              .tuser
		input  wire [6:0]  intel_vvp_protocol_conv_1_av_mm_control_agent_address,       // intel_vvp_protocol_conv_1_av_mm_control_agent.address
		input  wire        intel_vvp_protocol_conv_1_av_mm_control_agent_write,         //                                              .write
		input  wire [3:0]  intel_vvp_protocol_conv_1_av_mm_control_agent_byteenable,    //                                              .byteenable
		input  wire [31:0] intel_vvp_protocol_conv_1_av_mm_control_agent_writedata,     //                                              .writedata
		input  wire        intel_vvp_protocol_conv_1_av_mm_control_agent_read,          //                                              .read
		output wire [31:0] intel_vvp_protocol_conv_1_av_mm_control_agent_readdata,      //                                              .readdata
		output wire        intel_vvp_protocol_conv_1_av_mm_control_agent_readdatavalid, //                                              .readdatavalid
		output wire        intel_vvp_protocol_conv_1_av_mm_control_agent_waitrequest,   //                                              .waitrequest
		input  wire [23:0] intel_vvp_scaler_0_axi4s_vid_in_tdata,                       //               intel_vvp_scaler_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_scaler_0_axi4s_vid_in_tvalid,                      //                                              .tvalid
		output wire        intel_vvp_scaler_0_axi4s_vid_in_tready,                      //                                              .tready
		input  wire        intel_vvp_scaler_0_axi4s_vid_in_tlast,                       //                                              .tlast
		input  wire [2:0]  intel_vvp_scaler_0_axi4s_vid_in_tuser,                       //                                              .tuser
		output wire [23:0] intel_vvp_scaler_0_axi4s_vid_out_tdata,                      //              intel_vvp_scaler_0_axi4s_vid_out.tdata
		output wire        intel_vvp_scaler_0_axi4s_vid_out_tvalid,                     //                                              .tvalid
		input  wire        intel_vvp_scaler_0_axi4s_vid_out_tready,                     //                                              .tready
		output wire        intel_vvp_scaler_0_axi4s_vid_out_tlast,                      //                                              .tlast
		output wire [2:0]  intel_vvp_scaler_0_axi4s_vid_out_tuser,                      //                                              .tuser
		output wire [23:0] intel_vvp_tpg_0_axi4s_vid_out_tdata,                         //                 intel_vvp_tpg_0_axi4s_vid_out.tdata
		output wire        intel_vvp_tpg_0_axi4s_vid_out_tvalid,                        //                                              .tvalid
		input  wire        intel_vvp_tpg_0_axi4s_vid_out_tready,                        //                                              .tready
		output wire        intel_vvp_tpg_0_axi4s_vid_out_tlast,                         //                                              .tlast
		output wire [2:0]  intel_vvp_tpg_0_axi4s_vid_out_tuser,                         //                                              .tuser
		input  wire [6:0]  intel_vvp_tpg_0_av_mm_control_agent_address,                 //           intel_vvp_tpg_0_av_mm_control_agent.address
		input  wire        intel_vvp_tpg_0_av_mm_control_agent_write,                   //                                              .write
		input  wire [3:0]  intel_vvp_tpg_0_av_mm_control_agent_byteenable,              //                                              .byteenable
		input  wire [31:0] intel_vvp_tpg_0_av_mm_control_agent_writedata,               //                                              .writedata
		input  wire        intel_vvp_tpg_0_av_mm_control_agent_read,                    //                                              .read
		output wire [31:0] intel_vvp_tpg_0_av_mm_control_agent_readdata,                //                                              .readdata
		output wire        intel_vvp_tpg_0_av_mm_control_agent_readdatavalid,           //                                              .readdatavalid
		output wire        intel_vvp_tpg_0_av_mm_control_agent_waitrequest,             //                                              .waitrequest
		input  wire [23:0] intel_vvp_vfb_0_axi4s_vid_in_tdata,                          //                  intel_vvp_vfb_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_vfb_0_axi4s_vid_in_tvalid,                         //                                              .tvalid
		output wire        intel_vvp_vfb_0_axi4s_vid_in_tready,                         //                                              .tready
		input  wire        intel_vvp_vfb_0_axi4s_vid_in_tlast,                          //                                              .tlast
		input  wire [2:0]  intel_vvp_vfb_0_axi4s_vid_in_tuser,                          //                                              .tuser
		output wire [23:0] intel_vvp_vfb_0_axi4s_vid_out_tdata,                         //                 intel_vvp_vfb_0_axi4s_vid_out.tdata
		output wire        intel_vvp_vfb_0_axi4s_vid_out_tvalid,                        //                                              .tvalid
		input  wire        intel_vvp_vfb_0_axi4s_vid_out_tready,                        //                                              .tready
		output wire        intel_vvp_vfb_0_axi4s_vid_out_tlast,                         //                                              .tlast
		output wire [2:0]  intel_vvp_vfb_0_axi4s_vid_out_tuser,                         //                                              .tuser
		input  wire [6:0]  intel_vvp_vfb_0_av_mm_control_agent_address,                 //           intel_vvp_vfb_0_av_mm_control_agent.address
		input  wire        intel_vvp_vfb_0_av_mm_control_agent_write,                   //                                              .write
		input  wire [3:0]  intel_vvp_vfb_0_av_mm_control_agent_byteenable,              //                                              .byteenable
		input  wire [31:0] intel_vvp_vfb_0_av_mm_control_agent_writedata,               //                                              .writedata
		input  wire        intel_vvp_vfb_0_av_mm_control_agent_read,                    //                                              .read
		output wire [31:0] intel_vvp_vfb_0_av_mm_control_agent_readdata,                //                                              .readdata
		output wire        intel_vvp_vfb_0_av_mm_control_agent_readdatavalid,           //                                              .readdatavalid
		output wire        intel_vvp_vfb_0_av_mm_control_agent_waitrequest,             //                                              .waitrequest
		input  wire [23:0] lite_to_full_converter_axi4s_vid_in_tdata,                   //           lite_to_full_converter_axi4s_vid_in.tdata
		input  wire        lite_to_full_converter_axi4s_vid_in_tvalid,                  //                                              .tvalid
		output wire        lite_to_full_converter_axi4s_vid_in_tready,                  //                                              .tready
		input  wire        lite_to_full_converter_axi4s_vid_in_tlast,                   //                                              .tlast
		input  wire [2:0]  lite_to_full_converter_axi4s_vid_in_tuser,                   //                                              .tuser
		output wire [23:0] lite_to_full_converter_axi4s_vid_out_tdata,                  //          lite_to_full_converter_axi4s_vid_out.tdata
		output wire        lite_to_full_converter_axi4s_vid_out_tvalid,                 //                                              .tvalid
		input  wire        lite_to_full_converter_axi4s_vid_out_tready,                 //                                              .tready
		output wire        lite_to_full_converter_axi4s_vid_out_tlast,                  //                                              .tlast
		output wire [2:0]  lite_to_full_converter_axi4s_vid_out_tuser,                  //                                              .tuser
		output wire        mm_bridge_0_s0_waitrequest,                                  //                                mm_bridge_0_s0.waitrequest
		output wire [31:0] mm_bridge_0_s0_readdata,                                     //                                              .readdata
		output wire        mm_bridge_0_s0_readdatavalid,                                //                                              .readdatavalid
		input  wire [0:0]  mm_bridge_0_s0_burstcount,                                   //                                              .burstcount
		input  wire [31:0] mm_bridge_0_s0_writedata,                                    //                                              .writedata
		input  wire [12:0] mm_bridge_0_s0_address,                                      //                                              .address
		input  wire        mm_bridge_0_s0_write,                                        //                                              .write
		input  wire        mm_bridge_0_s0_read,                                         //                                              .read
		input  wire [3:0]  mm_bridge_0_s0_byteenable,                                   //                                              .byteenable
		input  wire        mm_bridge_0_s0_debugaccess,                                  //                                              .debugaccess
		input  wire        reset_reset                                                  //                                         reset.reset
	);

	wire          clock_in_out_clk_clk;                                                       // clock_in:out_clk -> [intel_vvp_clipper_0:main_clock_clk, intel_vvp_crs_0:main_clock_clk, intel_vvp_csc_0:main_clock_clk, intel_vvp_dil_0:main_clock_clk, intel_vvp_protocol_conv_0:main_clock_clk, intel_vvp_protocol_conv_1:main_clock_clk, intel_vvp_scaler_0:main_clock_clk, intel_vvp_tpg_0:main_clock_clk, intel_vvp_vfb_0:main_clock_clk, intel_vvp_vfb_0:mem_clock_clk, lite_to_full_converter:main_clock_clk, mm_bridge_0:clk, mm_interconnect_0:clock_in_out_clk_clk, mm_interconnect_1:clock_in_out_clk_clk, mm_interconnect_2:clock_in_out_clk_clk, onchip_memory2_0:clk, onchip_memory2_0:clk2, reset_in:clk, rst_controller:clk, rst_controller_001:clk]
	wire          intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest;                            // mm_interconnect_0:intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest -> intel_vvp_vfb_0:av_mm_mem_read_host_waitrequest
	wire  [255:0] intel_vvp_vfb_0_av_mm_mem_read_host_readdata;                               // mm_interconnect_0:intel_vvp_vfb_0_av_mm_mem_read_host_readdata -> intel_vvp_vfb_0:av_mm_mem_read_host_readdata
	wire   [31:0] intel_vvp_vfb_0_av_mm_mem_read_host_address;                                // intel_vvp_vfb_0:av_mm_mem_read_host_address -> mm_interconnect_0:intel_vvp_vfb_0_av_mm_mem_read_host_address
	wire          intel_vvp_vfb_0_av_mm_mem_read_host_read;                                   // intel_vvp_vfb_0:av_mm_mem_read_host_read -> mm_interconnect_0:intel_vvp_vfb_0_av_mm_mem_read_host_read
	wire          intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid;                          // mm_interconnect_0:intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid -> intel_vvp_vfb_0:av_mm_mem_read_host_readdatavalid
	wire    [3:0] intel_vvp_vfb_0_av_mm_mem_read_host_burstcount;                             // intel_vvp_vfb_0:av_mm_mem_read_host_burstcount -> mm_interconnect_0:intel_vvp_vfb_0_av_mm_mem_read_host_burstcount
	wire          mm_interconnect_0_onchip_memory2_0_s2_chipselect;                           // mm_interconnect_0:onchip_memory2_0_s2_chipselect -> onchip_memory2_0:chipselect2
	wire   [31:0] mm_interconnect_0_onchip_memory2_0_s2_readdata;                             // onchip_memory2_0:readdata2 -> mm_interconnect_0:onchip_memory2_0_s2_readdata
	wire    [9:0] mm_interconnect_0_onchip_memory2_0_s2_address;                              // mm_interconnect_0:onchip_memory2_0_s2_address -> onchip_memory2_0:address2
	wire    [3:0] mm_interconnect_0_onchip_memory2_0_s2_byteenable;                           // mm_interconnect_0:onchip_memory2_0_s2_byteenable -> onchip_memory2_0:byteenable2
	wire          mm_interconnect_0_onchip_memory2_0_s2_write;                                // mm_interconnect_0:onchip_memory2_0_s2_write -> onchip_memory2_0:write2
	wire   [31:0] mm_interconnect_0_onchip_memory2_0_s2_writedata;                            // mm_interconnect_0:onchip_memory2_0_s2_writedata -> onchip_memory2_0:writedata2
	wire          mm_interconnect_0_onchip_memory2_0_s2_clken;                                // mm_interconnect_0:onchip_memory2_0_s2_clken -> onchip_memory2_0:clken2
	wire          intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest;                           // mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest -> intel_vvp_vfb_0:av_mm_mem_write_host_waitrequest
	wire   [31:0] intel_vvp_vfb_0_av_mm_mem_write_host_address;                               // intel_vvp_vfb_0:av_mm_mem_write_host_address -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_address
	wire          intel_vvp_vfb_0_av_mm_mem_write_host_write;                                 // intel_vvp_vfb_0:av_mm_mem_write_host_write -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_write
	wire  [255:0] intel_vvp_vfb_0_av_mm_mem_write_host_writedata;                             // intel_vvp_vfb_0:av_mm_mem_write_host_writedata -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_writedata
	wire    [3:0] intel_vvp_vfb_0_av_mm_mem_write_host_burstcount;                            // intel_vvp_vfb_0:av_mm_mem_write_host_burstcount -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_burstcount
	wire          mm_interconnect_1_onchip_memory2_0_s1_chipselect;                           // mm_interconnect_1:onchip_memory2_0_s1_chipselect -> onchip_memory2_0:chipselect
	wire   [31:0] mm_interconnect_1_onchip_memory2_0_s1_readdata;                             // onchip_memory2_0:readdata -> mm_interconnect_1:onchip_memory2_0_s1_readdata
	wire    [9:0] mm_interconnect_1_onchip_memory2_0_s1_address;                              // mm_interconnect_1:onchip_memory2_0_s1_address -> onchip_memory2_0:address
	wire    [3:0] mm_interconnect_1_onchip_memory2_0_s1_byteenable;                           // mm_interconnect_1:onchip_memory2_0_s1_byteenable -> onchip_memory2_0:byteenable
	wire          mm_interconnect_1_onchip_memory2_0_s1_write;                                // mm_interconnect_1:onchip_memory2_0_s1_write -> onchip_memory2_0:write
	wire   [31:0] mm_interconnect_1_onchip_memory2_0_s1_writedata;                            // mm_interconnect_1:onchip_memory2_0_s1_writedata -> onchip_memory2_0:writedata
	wire          mm_interconnect_1_onchip_memory2_0_s1_clken;                                // mm_interconnect_1:onchip_memory2_0_s1_clken -> onchip_memory2_0:clken
	wire          mm_bridge_0_m0_waitrequest;                                                 // mm_interconnect_2:mm_bridge_0_m0_waitrequest -> mm_bridge_0:m0_waitrequest
	wire   [31:0] mm_bridge_0_m0_readdata;                                                    // mm_interconnect_2:mm_bridge_0_m0_readdata -> mm_bridge_0:m0_readdata
	wire          mm_bridge_0_m0_debugaccess;                                                 // mm_bridge_0:m0_debugaccess -> mm_interconnect_2:mm_bridge_0_m0_debugaccess
	wire   [12:0] mm_bridge_0_m0_address;                                                     // mm_bridge_0:m0_address -> mm_interconnect_2:mm_bridge_0_m0_address
	wire          mm_bridge_0_m0_read;                                                        // mm_bridge_0:m0_read -> mm_interconnect_2:mm_bridge_0_m0_read
	wire    [3:0] mm_bridge_0_m0_byteenable;                                                  // mm_bridge_0:m0_byteenable -> mm_interconnect_2:mm_bridge_0_m0_byteenable
	wire          mm_bridge_0_m0_readdatavalid;                                               // mm_interconnect_2:mm_bridge_0_m0_readdatavalid -> mm_bridge_0:m0_readdatavalid
	wire   [31:0] mm_bridge_0_m0_writedata;                                                   // mm_bridge_0:m0_writedata -> mm_interconnect_2:mm_bridge_0_m0_writedata
	wire          mm_bridge_0_m0_write;                                                       // mm_bridge_0:m0_write -> mm_interconnect_2:mm_bridge_0_m0_write
	wire    [0:0] mm_bridge_0_m0_burstcount;                                                  // mm_bridge_0:m0_burstcount -> mm_interconnect_2:mm_bridge_0_m0_burstcount
	wire   [31:0] mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_readdata;             // intel_vvp_csc_0:av_mm_control_agent_readdata -> mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_readdata
	wire          mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_waitrequest;          // intel_vvp_csc_0:av_mm_control_agent_waitrequest -> mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_address;              // mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_address -> intel_vvp_csc_0:av_mm_control_agent_address
	wire          mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_read;                 // mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_read -> intel_vvp_csc_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_byteenable;           // mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_byteenable -> intel_vvp_csc_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_readdatavalid;        // intel_vvp_csc_0:av_mm_control_agent_readdatavalid -> mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_write;                // mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_write -> intel_vvp_csc_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_writedata;            // mm_interconnect_2:intel_vvp_csc_0_av_mm_control_agent_writedata -> intel_vvp_csc_0:av_mm_control_agent_writedata
	wire   [31:0] mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_readdata;             // intel_vvp_crs_0:av_mm_control_agent_readdata -> mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_readdata
	wire          mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_waitrequest;          // intel_vvp_crs_0:av_mm_control_agent_waitrequest -> mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_address;              // mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_address -> intel_vvp_crs_0:av_mm_control_agent_address
	wire          mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_read;                 // mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_read -> intel_vvp_crs_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_byteenable;           // mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_byteenable -> intel_vvp_crs_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_readdatavalid;        // intel_vvp_crs_0:av_mm_control_agent_readdatavalid -> mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_write;                // mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_write -> intel_vvp_crs_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_writedata;            // mm_interconnect_2:intel_vvp_crs_0_av_mm_control_agent_writedata -> intel_vvp_crs_0:av_mm_control_agent_writedata
	wire   [31:0] mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_readdata;         // intel_vvp_clipper_0:av_mm_control_agent_readdata -> mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_readdata
	wire          mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_waitrequest;      // intel_vvp_clipper_0:av_mm_control_agent_waitrequest -> mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_address;          // mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_address -> intel_vvp_clipper_0:av_mm_control_agent_address
	wire          mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_read;             // mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_read -> intel_vvp_clipper_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_byteenable;       // mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_byteenable -> intel_vvp_clipper_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_readdatavalid;    // intel_vvp_clipper_0:av_mm_control_agent_readdatavalid -> mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_write;            // mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_write -> intel_vvp_clipper_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_writedata;        // mm_interconnect_2:intel_vvp_clipper_0_av_mm_control_agent_writedata -> intel_vvp_clipper_0:av_mm_control_agent_writedata
	wire   [31:0] mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_readdata;          // intel_vvp_scaler_0:av_mm_control_agent_readdata -> mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_readdata
	wire          mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_waitrequest;       // intel_vvp_scaler_0:av_mm_control_agent_waitrequest -> mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_address;           // mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_address -> intel_vvp_scaler_0:av_mm_control_agent_address
	wire          mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_read;              // mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_read -> intel_vvp_scaler_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_byteenable;        // mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_byteenable -> intel_vvp_scaler_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_readdatavalid;     // intel_vvp_scaler_0:av_mm_control_agent_readdatavalid -> mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_write;             // mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_write -> intel_vvp_scaler_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_writedata;         // mm_interconnect_2:intel_vvp_scaler_0_av_mm_control_agent_writedata -> intel_vvp_scaler_0:av_mm_control_agent_writedata
	wire   [31:0] mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_readdata;      // lite_to_full_converter:av_mm_control_agent_readdata -> mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_readdata
	wire          mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_waitrequest;   // lite_to_full_converter:av_mm_control_agent_waitrequest -> mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_address;       // mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_address -> lite_to_full_converter:av_mm_control_agent_address
	wire          mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_read;          // mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_read -> lite_to_full_converter:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_byteenable;    // mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_byteenable -> lite_to_full_converter:av_mm_control_agent_byteenable
	wire          mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_readdatavalid; // lite_to_full_converter:av_mm_control_agent_readdatavalid -> mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_write;         // mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_write -> lite_to_full_converter:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_writedata;     // mm_interconnect_2:lite_to_full_converter_av_mm_control_agent_writedata -> lite_to_full_converter:av_mm_control_agent_writedata
	wire          rst_controller_reset_out_reset;                                             // rst_controller:reset_out -> [intel_vvp_clipper_0:main_reset_reset, intel_vvp_crs_0:main_reset_reset, intel_vvp_csc_0:main_reset_reset, intel_vvp_dil_0:main_reset_reset, intel_vvp_protocol_conv_0:main_reset_reset, intel_vvp_protocol_conv_1:main_reset_reset, intel_vvp_scaler_0:main_reset_reset, intel_vvp_tpg_0:main_reset_reset, intel_vvp_vfb_0:main_reset_reset, intel_vvp_vfb_0:mem_reset_reset, lite_to_full_converter:main_reset_reset]
	wire          reset_in_out_reset_reset;                                                   // reset_in:out_reset -> [rst_controller:reset_in0, rst_controller_001:reset_in0]
	wire          rst_controller_001_reset_out_reset;                                         // rst_controller_001:reset_out -> [mm_bridge_0:reset, mm_interconnect_0:onchip_memory2_0_reset2_reset_bridge_in_reset_reset, mm_interconnect_1:onchip_memory2_0_reset1_reset_bridge_in_reset_reset, mm_interconnect_2:mm_bridge_0_reset_reset_bridge_in_reset_reset, onchip_memory2_0:reset, onchip_memory2_0:reset2, rst_translator:in_reset]
	wire          rst_controller_001_reset_out_reset_req;                                     // rst_controller_001:reset_req -> [onchip_memory2_0:reset_req, onchip_memory2_0:reset_req2, rst_translator:reset_req_in]

	pipeline_clock_in clock_in (
		.in_clk  (clk_clk),              //   input,  width = 1,  in_clk.clk
		.out_clk (clock_in_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	pipeline_intel_vvp_clipper_0 intel_vvp_clipper_0 (
		.main_clock_clk                    (clock_in_out_clk_clk),                                                    //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                          //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_clipper_0_axi4s_vid_in_tdata),                                  //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_clipper_0_axi4s_vid_in_tvalid),                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (intel_vvp_clipper_0_axi4s_vid_in_tready),                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (intel_vvp_clipper_0_axi4s_vid_in_tlast),                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (intel_vvp_clipper_0_axi4s_vid_in_tuser),                                  //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (intel_vvp_clipper_0_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_clipper_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_clipper_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_clipper_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_clipper_0_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_crs_0 intel_vvp_crs_0 (
		.main_clock_clk                    (clock_in_out_clk_clk),                                                //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                      //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_crs_0_axi4s_vid_in_tdata),                                  //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_crs_0_axi4s_vid_in_tvalid),                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (intel_vvp_crs_0_axi4s_vid_in_tready),                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (intel_vvp_crs_0_axi4s_vid_in_tlast),                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (intel_vvp_crs_0_axi4s_vid_in_tuser),                                  //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (intel_vvp_crs_0_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_crs_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_crs_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_crs_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_crs_0_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_csc_0 intel_vvp_csc_0 (
		.main_clock_clk                    (clock_in_out_clk_clk),                                                //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                      //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_csc_0_axi4s_vid_in_tdata),                                  //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_csc_0_axi4s_vid_in_tvalid),                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (intel_vvp_csc_0_axi4s_vid_in_tready),                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (intel_vvp_csc_0_axi4s_vid_in_tlast),                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (intel_vvp_csc_0_axi4s_vid_in_tuser),                                  //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (intel_vvp_csc_0_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_csc_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_csc_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_csc_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_csc_0_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_dil_0 intel_vvp_dil_0 (
		.main_clock_clk       (clock_in_out_clk_clk),                 //   input,   width = 1,    main_clock.clk
		.main_reset_reset     (rst_controller_reset_out_reset),       //   input,   width = 1,    main_reset.reset
		.axi4s_vid_in_tdata   (intel_vvp_dil_0_axi4s_vid_in_tdata),   //   input,  width = 24,  axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid  (intel_vvp_dil_0_axi4s_vid_in_tvalid),  //   input,   width = 1,              .tvalid
		.axi4s_vid_in_tready  (intel_vvp_dil_0_axi4s_vid_in_tready),  //  output,   width = 1,              .tready
		.axi4s_vid_in_tlast   (intel_vvp_dil_0_axi4s_vid_in_tlast),   //   input,   width = 1,              .tlast
		.axi4s_vid_in_tuser   (intel_vvp_dil_0_axi4s_vid_in_tuser),   //   input,   width = 3,              .tuser
		.axi4s_vid_out_tdata  (intel_vvp_dil_0_axi4s_vid_out_tdata),  //  output,  width = 24, axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid (intel_vvp_dil_0_axi4s_vid_out_tvalid), //  output,   width = 1,              .tvalid
		.axi4s_vid_out_tready (intel_vvp_dil_0_axi4s_vid_out_tready), //   input,   width = 1,              .tready
		.axi4s_vid_out_tlast  (intel_vvp_dil_0_axi4s_vid_out_tlast),  //  output,   width = 1,              .tlast
		.axi4s_vid_out_tuser  (intel_vvp_dil_0_axi4s_vid_out_tuser)   //  output,   width = 3,              .tuser
	);

	pipeline_intel_vvp_protocol_conv_0 intel_vvp_protocol_conv_0 (
		.main_clock_clk       (clock_in_out_clk_clk),                           //   input,   width = 1,    main_clock.clk
		.main_reset_reset     (rst_controller_reset_out_reset),                 //   input,   width = 1,    main_reset.reset
		.axi4s_vid_in_tdata   (intel_vvp_protocol_conv_0_axi4s_vid_in_tdata),   //   input,  width = 24,  axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid  (intel_vvp_protocol_conv_0_axi4s_vid_in_tvalid),  //   input,   width = 1,              .tvalid
		.axi4s_vid_in_tready  (intel_vvp_protocol_conv_0_axi4s_vid_in_tready),  //  output,   width = 1,              .tready
		.axi4s_vid_in_tlast   (intel_vvp_protocol_conv_0_axi4s_vid_in_tlast),   //   input,   width = 1,              .tlast
		.axi4s_vid_in_tuser   (intel_vvp_protocol_conv_0_axi4s_vid_in_tuser),   //   input,   width = 3,              .tuser
		.axi4s_vid_out_tdata  (intel_vvp_protocol_conv_0_axi4s_vid_out_tdata),  //  output,  width = 24, axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid (intel_vvp_protocol_conv_0_axi4s_vid_out_tvalid), //  output,   width = 1,              .tvalid
		.axi4s_vid_out_tready (intel_vvp_protocol_conv_0_axi4s_vid_out_tready), //   input,   width = 1,              .tready
		.axi4s_vid_out_tlast  (intel_vvp_protocol_conv_0_axi4s_vid_out_tlast),  //  output,   width = 1,              .tlast
		.axi4s_vid_out_tuser  (intel_vvp_protocol_conv_0_axi4s_vid_out_tuser)   //  output,   width = 3,              .tuser
	);

	pipeline_intel_vvp_protocol_conv_1 intel_vvp_protocol_conv_1 (
		.main_clock_clk                    (clock_in_out_clk_clk),                                        //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                              //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_protocol_conv_1_axi4s_vid_in_tdata),                //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_protocol_conv_1_axi4s_vid_in_tvalid),               //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (intel_vvp_protocol_conv_1_axi4s_vid_in_tready),               //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (intel_vvp_protocol_conv_1_axi4s_vid_in_tlast),                //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (intel_vvp_protocol_conv_1_axi4s_vid_in_tuser),                //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (intel_vvp_protocol_conv_1_axi4s_vid_out_tdata),               //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_protocol_conv_1_axi4s_vid_out_tvalid),              //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_protocol_conv_1_axi4s_vid_out_tready),              //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_protocol_conv_1_axi4s_vid_out_tlast),               //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_protocol_conv_1_axi4s_vid_out_tuser),               //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (intel_vvp_protocol_conv_1_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (intel_vvp_protocol_conv_1_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (intel_vvp_protocol_conv_1_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (intel_vvp_protocol_conv_1_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (intel_vvp_protocol_conv_1_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (intel_vvp_protocol_conv_1_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (intel_vvp_protocol_conv_1_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (intel_vvp_protocol_conv_1_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_scaler_0 intel_vvp_scaler_0 (
		.main_clock_clk                    (clock_in_out_clk_clk),                                                   //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                         //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_scaler_0_axi4s_vid_in_tdata),                                  //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_scaler_0_axi4s_vid_in_tvalid),                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (intel_vvp_scaler_0_axi4s_vid_in_tready),                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (intel_vvp_scaler_0_axi4s_vid_in_tlast),                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (intel_vvp_scaler_0_axi4s_vid_in_tuser),                                  //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (intel_vvp_scaler_0_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_scaler_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_scaler_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_scaler_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_scaler_0_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_tpg_0 intel_vvp_tpg_0 (
		.main_clock_clk                    (clock_in_out_clk_clk),                              //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                    //   input,   width = 1,          main_reset.reset
		.axi4s_vid_out_tdata               (intel_vvp_tpg_0_axi4s_vid_out_tdata),               //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_tpg_0_axi4s_vid_out_tvalid),              //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_tpg_0_axi4s_vid_out_tready),              //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_tpg_0_axi4s_vid_out_tlast),               //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_tpg_0_axi4s_vid_out_tuser),               //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (intel_vvp_tpg_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (intel_vvp_tpg_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (intel_vvp_tpg_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (intel_vvp_tpg_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (intel_vvp_tpg_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (intel_vvp_tpg_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (intel_vvp_tpg_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (intel_vvp_tpg_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_vfb_0 intel_vvp_vfb_0 (
		.main_clock_clk                    (clock_in_out_clk_clk),                              //   input,    width = 1,           main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                    //   input,    width = 1,           main_reset.reset
		.mem_clock_clk                     (clock_in_out_clk_clk),                              //   input,    width = 1,            mem_clock.clk
		.mem_reset_reset                   (rst_controller_reset_out_reset),                    //   input,    width = 1,            mem_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_vfb_0_axi4s_vid_in_tdata),                //   input,   width = 24,         axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_vfb_0_axi4s_vid_in_tvalid),               //   input,    width = 1,                     .tvalid
		.axi4s_vid_in_tready               (intel_vvp_vfb_0_axi4s_vid_in_tready),               //  output,    width = 1,                     .tready
		.axi4s_vid_in_tlast                (intel_vvp_vfb_0_axi4s_vid_in_tlast),                //   input,    width = 1,                     .tlast
		.axi4s_vid_in_tuser                (intel_vvp_vfb_0_axi4s_vid_in_tuser),                //   input,    width = 3,                     .tuser
		.axi4s_vid_out_tdata               (intel_vvp_vfb_0_axi4s_vid_out_tdata),               //  output,   width = 24,        axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_vfb_0_axi4s_vid_out_tvalid),              //  output,    width = 1,                     .tvalid
		.axi4s_vid_out_tready              (intel_vvp_vfb_0_axi4s_vid_out_tready),              //   input,    width = 1,                     .tready
		.axi4s_vid_out_tlast               (intel_vvp_vfb_0_axi4s_vid_out_tlast),               //  output,    width = 1,                     .tlast
		.axi4s_vid_out_tuser               (intel_vvp_vfb_0_axi4s_vid_out_tuser),               //  output,    width = 3,                     .tuser
		.av_mm_mem_write_host_address      (intel_vvp_vfb_0_av_mm_mem_write_host_address),      //  output,   width = 32, av_mm_mem_write_host.address
		.av_mm_mem_write_host_waitrequest  (intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest),  //   input,    width = 1,                     .waitrequest
		.av_mm_mem_write_host_burstcount   (intel_vvp_vfb_0_av_mm_mem_write_host_burstcount),   //  output,    width = 4,                     .burstcount
		.av_mm_mem_write_host_write        (intel_vvp_vfb_0_av_mm_mem_write_host_write),        //  output,    width = 1,                     .write
		.av_mm_mem_write_host_writedata    (intel_vvp_vfb_0_av_mm_mem_write_host_writedata),    //  output,  width = 256,                     .writedata
		.av_mm_mem_read_host_address       (intel_vvp_vfb_0_av_mm_mem_read_host_address),       //  output,   width = 32,  av_mm_mem_read_host.address
		.av_mm_mem_read_host_waitrequest   (intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest),   //   input,    width = 1,                     .waitrequest
		.av_mm_mem_read_host_burstcount    (intel_vvp_vfb_0_av_mm_mem_read_host_burstcount),    //  output,    width = 4,                     .burstcount
		.av_mm_mem_read_host_read          (intel_vvp_vfb_0_av_mm_mem_read_host_read),          //  output,    width = 1,                     .read
		.av_mm_mem_read_host_readdata      (intel_vvp_vfb_0_av_mm_mem_read_host_readdata),      //   input,  width = 256,                     .readdata
		.av_mm_mem_read_host_readdatavalid (intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid), //   input,    width = 1,                     .readdatavalid
		.av_mm_control_agent_address       (intel_vvp_vfb_0_av_mm_control_agent_address),       //   input,    width = 7,  av_mm_control_agent.address
		.av_mm_control_agent_write         (intel_vvp_vfb_0_av_mm_control_agent_write),         //   input,    width = 1,                     .write
		.av_mm_control_agent_byteenable    (intel_vvp_vfb_0_av_mm_control_agent_byteenable),    //   input,    width = 4,                     .byteenable
		.av_mm_control_agent_writedata     (intel_vvp_vfb_0_av_mm_control_agent_writedata),     //   input,   width = 32,                     .writedata
		.av_mm_control_agent_read          (intel_vvp_vfb_0_av_mm_control_agent_read),          //   input,    width = 1,                     .read
		.av_mm_control_agent_readdata      (intel_vvp_vfb_0_av_mm_control_agent_readdata),      //  output,   width = 32,                     .readdata
		.av_mm_control_agent_readdatavalid (intel_vvp_vfb_0_av_mm_control_agent_readdatavalid), //  output,    width = 1,                     .readdatavalid
		.av_mm_control_agent_waitrequest   (intel_vvp_vfb_0_av_mm_control_agent_waitrequest)    //  output,    width = 1,                     .waitrequest
	);

	pipeline_intel_vvp_protocol_conv_2 lite_to_full_converter (
		.main_clock_clk                    (clock_in_out_clk_clk),                                                       //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                             //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (lite_to_full_converter_axi4s_vid_in_tdata),                                  //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (lite_to_full_converter_axi4s_vid_in_tvalid),                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (lite_to_full_converter_axi4s_vid_in_tready),                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (lite_to_full_converter_axi4s_vid_in_tlast),                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (lite_to_full_converter_axi4s_vid_in_tuser),                                  //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (lite_to_full_converter_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (lite_to_full_converter_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (lite_to_full_converter_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (lite_to_full_converter_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (lite_to_full_converter_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_mm_bridge_0 mm_bridge_0 (
		.clk              (clock_in_out_clk_clk),               //   input,   width = 1,   clk.clk
		.reset            (rst_controller_001_reset_out_reset), //   input,   width = 1, reset.reset
		.s0_waitrequest   (mm_bridge_0_s0_waitrequest),         //  output,   width = 1,    s0.waitrequest
		.s0_readdata      (mm_bridge_0_s0_readdata),            //  output,  width = 32,      .readdata
		.s0_readdatavalid (mm_bridge_0_s0_readdatavalid),       //  output,   width = 1,      .readdatavalid
		.s0_burstcount    (mm_bridge_0_s0_burstcount),          //   input,   width = 1,      .burstcount
		.s0_writedata     (mm_bridge_0_s0_writedata),           //   input,  width = 32,      .writedata
		.s0_address       (mm_bridge_0_s0_address),             //   input,  width = 13,      .address
		.s0_write         (mm_bridge_0_s0_write),               //   input,   width = 1,      .write
		.s0_read          (mm_bridge_0_s0_read),                //   input,   width = 1,      .read
		.s0_byteenable    (mm_bridge_0_s0_byteenable),          //   input,   width = 4,      .byteenable
		.s0_debugaccess   (mm_bridge_0_s0_debugaccess),         //   input,   width = 1,      .debugaccess
		.m0_waitrequest   (mm_bridge_0_m0_waitrequest),         //   input,   width = 1,    m0.waitrequest
		.m0_readdata      (mm_bridge_0_m0_readdata),            //   input,  width = 32,      .readdata
		.m0_readdatavalid (mm_bridge_0_m0_readdatavalid),       //   input,   width = 1,      .readdatavalid
		.m0_burstcount    (mm_bridge_0_m0_burstcount),          //  output,   width = 1,      .burstcount
		.m0_writedata     (mm_bridge_0_m0_writedata),           //  output,  width = 32,      .writedata
		.m0_address       (mm_bridge_0_m0_address),             //  output,  width = 13,      .address
		.m0_write         (mm_bridge_0_m0_write),               //  output,   width = 1,      .write
		.m0_read          (mm_bridge_0_m0_read),                //  output,   width = 1,      .read
		.m0_byteenable    (mm_bridge_0_m0_byteenable),          //  output,   width = 4,      .byteenable
		.m0_debugaccess   (mm_bridge_0_m0_debugaccess)          //  output,   width = 1,      .debugaccess
	);

	pipeline_onchip_memory2_0 onchip_memory2_0 (
		.clk         (clock_in_out_clk_clk),                             //   input,   width = 1,   clk1.clk
		.address     (mm_interconnect_1_onchip_memory2_0_s1_address),    //   input,  width = 10,     s1.address
		.clken       (mm_interconnect_1_onchip_memory2_0_s1_clken),      //   input,   width = 1,       .clken
		.chipselect  (mm_interconnect_1_onchip_memory2_0_s1_chipselect), //   input,   width = 1,       .chipselect
		.write       (mm_interconnect_1_onchip_memory2_0_s1_write),      //   input,   width = 1,       .write
		.readdata    (mm_interconnect_1_onchip_memory2_0_s1_readdata),   //  output,  width = 32,       .readdata
		.writedata   (mm_interconnect_1_onchip_memory2_0_s1_writedata),  //   input,  width = 32,       .writedata
		.byteenable  (mm_interconnect_1_onchip_memory2_0_s1_byteenable), //   input,   width = 4,       .byteenable
		.reset       (rst_controller_001_reset_out_reset),               //   input,   width = 1, reset1.reset
		.reset_req   (rst_controller_001_reset_out_reset_req),           //   input,   width = 1,       .reset_req
		.address2    (mm_interconnect_0_onchip_memory2_0_s2_address),    //   input,  width = 10,     s2.address
		.chipselect2 (mm_interconnect_0_onchip_memory2_0_s2_chipselect), //   input,   width = 1,       .chipselect
		.clken2      (mm_interconnect_0_onchip_memory2_0_s2_clken),      //   input,   width = 1,       .clken
		.write2      (mm_interconnect_0_onchip_memory2_0_s2_write),      //   input,   width = 1,       .write
		.readdata2   (mm_interconnect_0_onchip_memory2_0_s2_readdata),   //  output,  width = 32,       .readdata
		.writedata2  (mm_interconnect_0_onchip_memory2_0_s2_writedata),  //   input,  width = 32,       .writedata
		.byteenable2 (mm_interconnect_0_onchip_memory2_0_s2_byteenable), //   input,   width = 4,       .byteenable
		.clk2        (clock_in_out_clk_clk),                             //   input,   width = 1,   clk2.clk
		.reset2      (rst_controller_001_reset_out_reset),               //   input,   width = 1, reset2.reset
		.reset_req2  (rst_controller_001_reset_out_reset_req)            //   input,   width = 1,       .reset_req
	);

	pipeline_reset_in reset_in (
		.clk       (clock_in_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset  (reset_reset),              //   input,  width = 1,  in_reset.reset
		.out_reset (reset_in_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	pipeline_altera_mm_interconnect_1920_5c5nkdi mm_interconnect_0 (
		.intel_vvp_vfb_0_av_mm_mem_read_host_address         (intel_vvp_vfb_0_av_mm_mem_read_host_address),       //   input,   width = 32,           intel_vvp_vfb_0_av_mm_mem_read_host.address
		.intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest     (intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest),   //  output,    width = 1,                                              .waitrequest
		.intel_vvp_vfb_0_av_mm_mem_read_host_burstcount      (intel_vvp_vfb_0_av_mm_mem_read_host_burstcount),    //   input,    width = 4,                                              .burstcount
		.intel_vvp_vfb_0_av_mm_mem_read_host_read            (intel_vvp_vfb_0_av_mm_mem_read_host_read),          //   input,    width = 1,                                              .read
		.intel_vvp_vfb_0_av_mm_mem_read_host_readdata        (intel_vvp_vfb_0_av_mm_mem_read_host_readdata),      //  output,  width = 256,                                              .readdata
		.intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid   (intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid), //  output,    width = 1,                                              .readdatavalid
		.onchip_memory2_0_s2_address                         (mm_interconnect_0_onchip_memory2_0_s2_address),     //  output,   width = 10,                           onchip_memory2_0_s2.address
		.onchip_memory2_0_s2_write                           (mm_interconnect_0_onchip_memory2_0_s2_write),       //  output,    width = 1,                                              .write
		.onchip_memory2_0_s2_readdata                        (mm_interconnect_0_onchip_memory2_0_s2_readdata),    //   input,   width = 32,                                              .readdata
		.onchip_memory2_0_s2_writedata                       (mm_interconnect_0_onchip_memory2_0_s2_writedata),   //  output,   width = 32,                                              .writedata
		.onchip_memory2_0_s2_byteenable                      (mm_interconnect_0_onchip_memory2_0_s2_byteenable),  //  output,    width = 4,                                              .byteenable
		.onchip_memory2_0_s2_chipselect                      (mm_interconnect_0_onchip_memory2_0_s2_chipselect),  //  output,    width = 1,                                              .chipselect
		.onchip_memory2_0_s2_clken                           (mm_interconnect_0_onchip_memory2_0_s2_clken),       //  output,    width = 1,                                              .clken
		.onchip_memory2_0_reset2_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                //   input,    width = 1, onchip_memory2_0_reset2_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                (clock_in_out_clk_clk)                               //   input,    width = 1,                              clock_in_out_clk.clk
	);

	pipeline_altera_mm_interconnect_1920_h5rdvxi mm_interconnect_1 (
		.intel_vvp_vfb_0_av_mm_mem_write_host_address        (intel_vvp_vfb_0_av_mm_mem_write_host_address),     //   input,   width = 32,          intel_vvp_vfb_0_av_mm_mem_write_host.address
		.intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest    (intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest), //  output,    width = 1,                                              .waitrequest
		.intel_vvp_vfb_0_av_mm_mem_write_host_burstcount     (intel_vvp_vfb_0_av_mm_mem_write_host_burstcount),  //   input,    width = 4,                                              .burstcount
		.intel_vvp_vfb_0_av_mm_mem_write_host_write          (intel_vvp_vfb_0_av_mm_mem_write_host_write),       //   input,    width = 1,                                              .write
		.intel_vvp_vfb_0_av_mm_mem_write_host_writedata      (intel_vvp_vfb_0_av_mm_mem_write_host_writedata),   //   input,  width = 256,                                              .writedata
		.onchip_memory2_0_s1_address                         (mm_interconnect_1_onchip_memory2_0_s1_address),    //  output,   width = 10,                           onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_write                           (mm_interconnect_1_onchip_memory2_0_s1_write),      //  output,    width = 1,                                              .write
		.onchip_memory2_0_s1_readdata                        (mm_interconnect_1_onchip_memory2_0_s1_readdata),   //   input,   width = 32,                                              .readdata
		.onchip_memory2_0_s1_writedata                       (mm_interconnect_1_onchip_memory2_0_s1_writedata),  //  output,   width = 32,                                              .writedata
		.onchip_memory2_0_s1_byteenable                      (mm_interconnect_1_onchip_memory2_0_s1_byteenable), //  output,    width = 4,                                              .byteenable
		.onchip_memory2_0_s1_chipselect                      (mm_interconnect_1_onchip_memory2_0_s1_chipselect), //  output,    width = 1,                                              .chipselect
		.onchip_memory2_0_s1_clken                           (mm_interconnect_1_onchip_memory2_0_s1_clken),      //  output,    width = 1,                                              .clken
		.onchip_memory2_0_reset1_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),               //   input,    width = 1, onchip_memory2_0_reset1_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                (clock_in_out_clk_clk)                              //   input,    width = 1,                              clock_in_out_clk.clk
	);

	pipeline_altera_mm_interconnect_1920_cwek6ja mm_interconnect_2 (
		.mm_bridge_0_m0_address                                   (mm_bridge_0_m0_address),                                                     //   input,  width = 13,                             mm_bridge_0_m0.address
		.mm_bridge_0_m0_waitrequest                               (mm_bridge_0_m0_waitrequest),                                                 //  output,   width = 1,                                           .waitrequest
		.mm_bridge_0_m0_burstcount                                (mm_bridge_0_m0_burstcount),                                                  //   input,   width = 1,                                           .burstcount
		.mm_bridge_0_m0_byteenable                                (mm_bridge_0_m0_byteenable),                                                  //   input,   width = 4,                                           .byteenable
		.mm_bridge_0_m0_read                                      (mm_bridge_0_m0_read),                                                        //   input,   width = 1,                                           .read
		.mm_bridge_0_m0_readdata                                  (mm_bridge_0_m0_readdata),                                                    //  output,  width = 32,                                           .readdata
		.mm_bridge_0_m0_readdatavalid                             (mm_bridge_0_m0_readdatavalid),                                               //  output,   width = 1,                                           .readdatavalid
		.mm_bridge_0_m0_write                                     (mm_bridge_0_m0_write),                                                       //   input,   width = 1,                                           .write
		.mm_bridge_0_m0_writedata                                 (mm_bridge_0_m0_writedata),                                                   //   input,  width = 32,                                           .writedata
		.mm_bridge_0_m0_debugaccess                               (mm_bridge_0_m0_debugaccess),                                                 //   input,   width = 1,                                           .debugaccess
		.intel_vvp_csc_0_av_mm_control_agent_address              (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_address),              //  output,   width = 7,        intel_vvp_csc_0_av_mm_control_agent.address
		.intel_vvp_csc_0_av_mm_control_agent_write                (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_write),                //  output,   width = 1,                                           .write
		.intel_vvp_csc_0_av_mm_control_agent_read                 (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_read),                 //  output,   width = 1,                                           .read
		.intel_vvp_csc_0_av_mm_control_agent_readdata             (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_readdata),             //   input,  width = 32,                                           .readdata
		.intel_vvp_csc_0_av_mm_control_agent_writedata            (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_writedata),            //  output,  width = 32,                                           .writedata
		.intel_vvp_csc_0_av_mm_control_agent_byteenable           (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_byteenable),           //  output,   width = 4,                                           .byteenable
		.intel_vvp_csc_0_av_mm_control_agent_readdatavalid        (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_readdatavalid),        //   input,   width = 1,                                           .readdatavalid
		.intel_vvp_csc_0_av_mm_control_agent_waitrequest          (mm_interconnect_2_intel_vvp_csc_0_av_mm_control_agent_waitrequest),          //   input,   width = 1,                                           .waitrequest
		.intel_vvp_crs_0_av_mm_control_agent_address              (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_address),              //  output,   width = 7,        intel_vvp_crs_0_av_mm_control_agent.address
		.intel_vvp_crs_0_av_mm_control_agent_write                (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_write),                //  output,   width = 1,                                           .write
		.intel_vvp_crs_0_av_mm_control_agent_read                 (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_read),                 //  output,   width = 1,                                           .read
		.intel_vvp_crs_0_av_mm_control_agent_readdata             (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_readdata),             //   input,  width = 32,                                           .readdata
		.intel_vvp_crs_0_av_mm_control_agent_writedata            (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_writedata),            //  output,  width = 32,                                           .writedata
		.intel_vvp_crs_0_av_mm_control_agent_byteenable           (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_byteenable),           //  output,   width = 4,                                           .byteenable
		.intel_vvp_crs_0_av_mm_control_agent_readdatavalid        (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_readdatavalid),        //   input,   width = 1,                                           .readdatavalid
		.intel_vvp_crs_0_av_mm_control_agent_waitrequest          (mm_interconnect_2_intel_vvp_crs_0_av_mm_control_agent_waitrequest),          //   input,   width = 1,                                           .waitrequest
		.intel_vvp_clipper_0_av_mm_control_agent_address          (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_address),          //  output,   width = 7,    intel_vvp_clipper_0_av_mm_control_agent.address
		.intel_vvp_clipper_0_av_mm_control_agent_write            (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_write),            //  output,   width = 1,                                           .write
		.intel_vvp_clipper_0_av_mm_control_agent_read             (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_read),             //  output,   width = 1,                                           .read
		.intel_vvp_clipper_0_av_mm_control_agent_readdata         (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_readdata),         //   input,  width = 32,                                           .readdata
		.intel_vvp_clipper_0_av_mm_control_agent_writedata        (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_writedata),        //  output,  width = 32,                                           .writedata
		.intel_vvp_clipper_0_av_mm_control_agent_byteenable       (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_byteenable),       //  output,   width = 4,                                           .byteenable
		.intel_vvp_clipper_0_av_mm_control_agent_readdatavalid    (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_readdatavalid),    //   input,   width = 1,                                           .readdatavalid
		.intel_vvp_clipper_0_av_mm_control_agent_waitrequest      (mm_interconnect_2_intel_vvp_clipper_0_av_mm_control_agent_waitrequest),      //   input,   width = 1,                                           .waitrequest
		.intel_vvp_scaler_0_av_mm_control_agent_address           (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_address),           //  output,   width = 7,     intel_vvp_scaler_0_av_mm_control_agent.address
		.intel_vvp_scaler_0_av_mm_control_agent_write             (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_write),             //  output,   width = 1,                                           .write
		.intel_vvp_scaler_0_av_mm_control_agent_read              (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_read),              //  output,   width = 1,                                           .read
		.intel_vvp_scaler_0_av_mm_control_agent_readdata          (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_readdata),          //   input,  width = 32,                                           .readdata
		.intel_vvp_scaler_0_av_mm_control_agent_writedata         (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_writedata),         //  output,  width = 32,                                           .writedata
		.intel_vvp_scaler_0_av_mm_control_agent_byteenable        (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_byteenable),        //  output,   width = 4,                                           .byteenable
		.intel_vvp_scaler_0_av_mm_control_agent_readdatavalid     (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_readdatavalid),     //   input,   width = 1,                                           .readdatavalid
		.intel_vvp_scaler_0_av_mm_control_agent_waitrequest       (mm_interconnect_2_intel_vvp_scaler_0_av_mm_control_agent_waitrequest),       //   input,   width = 1,                                           .waitrequest
		.lite_to_full_converter_av_mm_control_agent_address       (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_address),       //  output,   width = 7, lite_to_full_converter_av_mm_control_agent.address
		.lite_to_full_converter_av_mm_control_agent_write         (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_write),         //  output,   width = 1,                                           .write
		.lite_to_full_converter_av_mm_control_agent_read          (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_read),          //  output,   width = 1,                                           .read
		.lite_to_full_converter_av_mm_control_agent_readdata      (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_readdata),      //   input,  width = 32,                                           .readdata
		.lite_to_full_converter_av_mm_control_agent_writedata     (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_writedata),     //  output,  width = 32,                                           .writedata
		.lite_to_full_converter_av_mm_control_agent_byteenable    (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_byteenable),    //  output,   width = 4,                                           .byteenable
		.lite_to_full_converter_av_mm_control_agent_readdatavalid (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_readdatavalid), //   input,   width = 1,                                           .readdatavalid
		.lite_to_full_converter_av_mm_control_agent_waitrequest   (mm_interconnect_2_lite_to_full_converter_av_mm_control_agent_waitrequest),   //   input,   width = 1,                                           .waitrequest
		.mm_bridge_0_reset_reset_bridge_in_reset_reset            (rst_controller_001_reset_out_reset),                                         //   input,   width = 1,    mm_bridge_0_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                     (clock_in_out_clk_clk)                                                        //   input,   width = 1,                           clock_in_out_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset_in_out_reset_reset),       //   input,  width = 1, reset_in0.reset
		.clk            (clock_in_out_clk_clk),           //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (reset_in_out_reset_reset),               //   input,  width = 1, reset_in0.reset
		.clk            (clock_in_out_clk_clk),                   //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     //  output,  width = 1, reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //  output,  width = 1,          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated),                       
		.reset_in1      (1'b0),                                   // (terminated),                       
		.reset_req_in1  (1'b0),                                   // (terminated),                       
		.reset_in2      (1'b0),                                   // (terminated),                       
		.reset_req_in2  (1'b0),                                   // (terminated),                       
		.reset_in3      (1'b0),                                   // (terminated),                       
		.reset_req_in3  (1'b0),                                   // (terminated),                       
		.reset_in4      (1'b0),                                   // (terminated),                       
		.reset_req_in4  (1'b0),                                   // (terminated),                       
		.reset_in5      (1'b0),                                   // (terminated),                       
		.reset_req_in5  (1'b0),                                   // (terminated),                       
		.reset_in6      (1'b0),                                   // (terminated),                       
		.reset_req_in6  (1'b0),                                   // (terminated),                       
		.reset_in7      (1'b0),                                   // (terminated),                       
		.reset_req_in7  (1'b0),                                   // (terminated),                       
		.reset_in8      (1'b0),                                   // (terminated),                       
		.reset_req_in8  (1'b0),                                   // (terminated),                       
		.reset_in9      (1'b0),                                   // (terminated),                       
		.reset_req_in9  (1'b0),                                   // (terminated),                       
		.reset_in10     (1'b0),                                   // (terminated),                       
		.reset_req_in10 (1'b0),                                   // (terminated),                       
		.reset_in11     (1'b0),                                   // (terminated),                       
		.reset_req_in11 (1'b0),                                   // (terminated),                       
		.reset_in12     (1'b0),                                   // (terminated),                       
		.reset_req_in12 (1'b0),                                   // (terminated),                       
		.reset_in13     (1'b0),                                   // (terminated),                       
		.reset_req_in13 (1'b0),                                   // (terminated),                       
		.reset_in14     (1'b0),                                   // (terminated),                       
		.reset_req_in14 (1'b0),                                   // (terminated),                       
		.reset_in15     (1'b0),                                   // (terminated),                       
		.reset_req_in15 (1'b0)                                    // (terminated),                       
	);

endmodule
