// pipeline_intel_vvp_dil_0_intel_vvp_dil_2451_zskkody.v

// This file was auto-generated from intel_vvp_dil_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module pipeline_intel_vvp_dil_0_intel_vvp_dil_2451_zskkody #(
		parameter CLOCKS_ARE_SEPARATE    = 1,
		parameter P_AV_MM_DATA_WIDTH     = 32,
		parameter P_AV_MM_ADDR_WIDTH     = 32,
		parameter WRITE_BURST_TARGET     = 32,
		parameter READ_BURST_TARGET      = 32,
		parameter RUNTIME_CONTROL        = 0,
		parameter ENABLE_DEBUG           = 0,
		parameter PIXELS_IN_PARALLEL     = 1,
		parameter BPS                    = 8,
		parameter NUMBER_OF_COLOR_PLANES = 3,
		parameter MAX_WIDTH              = 2048,
		parameter PIPELINE_READY         = 0,
		parameter FIFO                   = 0
	) (
		input  wire        main_clock_clk,       //    main_clock.clk,   Clock Input
		input  wire        main_reset_reset,     //    main_reset.reset
		input  wire [23:0] axi4s_vid_in_tdata,   //  axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,  //              .tvalid
		output wire        axi4s_vid_in_tready,  //              .tready
		input  wire        axi4s_vid_in_tlast,   //              .tlast
		input  wire [2:0]  axi4s_vid_in_tuser,   //              .tuser
		output wire [23:0] axi4s_vid_out_tdata,  // axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid, //              .tvalid
		input  wire        axi4s_vid_out_tready, //              .tready
		output wire        axi4s_vid_out_tlast,  //              .tlast
		output wire [2:0]  axi4s_vid_out_tuser   //              .tuser
	);

	wire         main_rst_bridge_out_reset_reset;        // main_rst_bridge:out_rst -> [algo_comp:rst, duplicator:rst, iib:rst, line_buffer:rst, mux:rst, oib:rst, scheduler:rst]
	wire         iib_axi_st_data_out_tvalid;             // iib:axi_st_data_out_tvalid -> duplicator:axi_st_din_tvalid
	wire   [2:0] iib_axi_st_data_out_tuser;              // iib:axi_st_data_out_tuser -> duplicator:axi_st_din_tuser
	wire         iib_axi_st_data_out_tready;             // duplicator:axi_st_din_tready -> iib:axi_st_data_out_tready
	wire  [23:0] iib_axi_st_data_out_tdata;              // iib:axi_st_data_out_tdata -> duplicator:axi_st_din_tdata
	wire         iib_axi_st_data_out_tlast;              // iib:axi_st_data_out_tlast -> duplicator:axi_st_din_tlast
	wire         duplicator_axi_st_dout_0_tvalid;        // duplicator:axi_st_dout_0_tvalid -> mux:axi_st_din_0_tvalid
	wire   [2:0] duplicator_axi_st_dout_0_tuser;         // duplicator:axi_st_dout_0_tuser -> mux:axi_st_din_0_tuser
	wire         duplicator_axi_st_dout_0_tready;        // mux:axi_st_din_0_tready -> duplicator:axi_st_dout_0_tready
	wire  [23:0] duplicator_axi_st_dout_0_tdata;         // duplicator:axi_st_dout_0_tdata -> mux:axi_st_din_0_tdata
	wire         duplicator_axi_st_dout_0_tlast;         // duplicator:axi_st_dout_0_tlast -> mux:axi_st_din_0_tlast
	wire         duplicator_axi_st_dout_1_tvalid;        // duplicator:axi_st_dout_1_tvalid -> line_buffer:axi_st_data_in_tvalid
	wire   [2:0] duplicator_axi_st_dout_1_tuser;         // duplicator:axi_st_dout_1_tuser -> line_buffer:axi_st_data_in_tuser
	wire         duplicator_axi_st_dout_1_tready;        // line_buffer:axi_st_data_in_tready -> duplicator:axi_st_dout_1_tready
	wire  [23:0] duplicator_axi_st_dout_1_tdata;         // duplicator:axi_st_dout_1_tdata -> line_buffer:axi_st_data_in_tdata
	wire         duplicator_axi_st_dout_1_tlast;         // duplicator:axi_st_dout_1_tlast -> line_buffer:axi_st_data_in_tlast
	wire         iib_axi_st_ctrl_out_tvalid;             // iib:axi_st_ctrl_out_tvalid -> scheduler:axi_st_ctrl_in_tvalid
	wire   [1:0] iib_axi_st_ctrl_out_tuser;              // iib:axi_st_ctrl_out_tuser -> scheduler:axi_st_ctrl_in_tuser
	wire         iib_axi_st_ctrl_out_tready;             // scheduler:axi_st_ctrl_in_tready -> iib:axi_st_ctrl_out_tready
	wire  [15:0] iib_axi_st_ctrl_out_tdata;              // iib:axi_st_ctrl_out_tdata -> scheduler:axi_st_ctrl_in_tdata
	wire         iib_axi_st_ctrl_out_tlast;              // iib:axi_st_ctrl_out_tlast -> scheduler:axi_st_ctrl_in_tlast
	wire         scheduler_axi_st_ctrl_out_tvalid;       // scheduler:axi_st_ctrl_out_tvalid -> oib:axi_st_ctrl_in_tvalid
	wire   [1:0] scheduler_axi_st_ctrl_out_tuser;        // scheduler:axi_st_ctrl_out_tuser -> oib:axi_st_ctrl_in_tuser
	wire         scheduler_axi_st_ctrl_out_tready;       // oib:axi_st_ctrl_in_tready -> scheduler:axi_st_ctrl_out_tready
	wire  [15:0] scheduler_axi_st_ctrl_out_tdata;        // scheduler:axi_st_ctrl_out_tdata -> oib:axi_st_ctrl_in_tdata
	wire         scheduler_axi_st_ctrl_out_tlast;        // scheduler:axi_st_ctrl_out_tlast -> oib:axi_st_ctrl_in_tlast
	wire         line_buffer_axi_st_data_out_tvalid;     // line_buffer:axi_st_data_out_tvalid -> algo_comp:axi_st_data_in_tvalid
	wire   [5:0] line_buffer_axi_st_data_out_tuser;      // line_buffer:axi_st_data_out_tuser -> algo_comp:axi_st_data_in_tuser
	wire         line_buffer_axi_st_data_out_tready;     // algo_comp:axi_st_data_in_tready -> line_buffer:axi_st_data_out_tready
	wire  [47:0] line_buffer_axi_st_data_out_tdata;      // line_buffer:axi_st_data_out_tdata -> algo_comp:axi_st_data_in_tdata
	wire         line_buffer_axi_st_data_out_tlast;      // line_buffer:axi_st_data_out_tlast -> algo_comp:axi_st_data_in_tlast
	wire         algo_comp_axi_st_data_out_tvalid;       // algo_comp:axi_st_data_out_tvalid -> mux:axi_st_din_1_tvalid
	wire   [2:0] algo_comp_axi_st_data_out_tuser;        // algo_comp:axi_st_data_out_tuser -> mux:axi_st_din_1_tuser
	wire         algo_comp_axi_st_data_out_tready;       // mux:axi_st_din_1_tready -> algo_comp:axi_st_data_out_tready
	wire  [23:0] algo_comp_axi_st_data_out_tdata;        // algo_comp:axi_st_data_out_tdata -> mux:axi_st_din_1_tdata
	wire         algo_comp_axi_st_data_out_tlast;        // algo_comp:axi_st_data_out_tlast -> mux:axi_st_din_1_tlast
	wire         mux_axi_st_dout_tvalid;                 // mux:axi_st_dout_tvalid -> oib:axi_st_data_in_tvalid
	wire   [2:0] mux_axi_st_dout_tuser;                  // mux:axi_st_dout_tuser -> oib:axi_st_data_in_tuser
	wire         mux_axi_st_dout_tready;                 // oib:axi_st_data_in_tready -> mux:axi_st_dout_tready
	wire  [23:0] mux_axi_st_dout_tdata;                  // mux:axi_st_dout_tdata -> oib:axi_st_data_in_tdata
	wire         mux_axi_st_dout_tlast;                  // mux:axi_st_dout_tlast -> oib:axi_st_data_in_tlast
	wire         scheduler_axi_st_cmd_buff_tvalid;       // scheduler:axi_st_cmd_buff_tvalid -> line_buffer:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_buff_tready;       // line_buffer:axi_st_cmd_tready -> scheduler:axi_st_cmd_buff_tready
	wire  [23:0] scheduler_axi_st_cmd_buff_tdata;        // scheduler:axi_st_cmd_buff_tdata -> line_buffer:axi_st_cmd_tdata
	wire         scheduler_axi_st_cmd_duplicator_tvalid; // scheduler:axi_st_cmd_duplicator_tvalid -> duplicator:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_duplicator_tready; // duplicator:axi_st_cmd_tready -> scheduler:axi_st_cmd_duplicator_tready
	wire  [15:0] scheduler_axi_st_cmd_duplicator_tdata;  // scheduler:axi_st_cmd_duplicator_tdata -> duplicator:axi_st_cmd_tdata
	wire         scheduler_axi_st_cmd_mux_tvalid;        // scheduler:axi_st_cmd_mux_tvalid -> mux:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_mux_tready;        // mux:axi_st_cmd_tready -> scheduler:axi_st_cmd_mux_tready
	wire   [7:0] scheduler_axi_st_cmd_mux_tdata;         // scheduler:axi_st_cmd_mux_tdata -> mux:axi_st_cmd_tdata
	wire         scheduler_axi_st_cmd_tvalid;            // scheduler:axi_st_cmd_tvalid -> algo_comp:axi_st_cmd_tvalid
	wire         scheduler_axi_st_cmd_tready;            // algo_comp:axi_st_cmd_tready -> scheduler:axi_st_cmd_tready
	wire   [7:0] scheduler_axi_st_cmd_tdata;             // scheduler:axi_st_cmd_tdata -> algo_comp:axi_st_cmd_tdata
	wire   [1:0] mux_axi_st_din_tready;                  // port fragment
	wire  [47:0] duplicator_axi_st_dout_tdata;           // port fragment
	wire   [1:0] duplicator_axi_st_dout_tvalid;          // port fragment
	wire   [1:0] duplicator_axi_st_dout_tlast;           // port fragment
	wire   [5:0] duplicator_axi_st_dout_tuser;           // port fragment

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (CLOCKS_ARE_SEPARATE != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					clocks_are_separate_check ( .error(1'b1) );
		end
		if (P_AV_MM_DATA_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					p_av_mm_data_width_check ( .error(1'b1) );
		end
		if (P_AV_MM_ADDR_WIDTH != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					p_av_mm_addr_width_check ( .error(1'b1) );
		end
		if (WRITE_BURST_TARGET != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					write_burst_target_check ( .error(1'b1) );
		end
		if (READ_BURST_TARGET != 32)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					read_burst_target_check ( .error(1'b1) );
		end
		if (RUNTIME_CONTROL != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					runtime_control_check ( .error(1'b1) );
		end
		if (ENABLE_DEBUG != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					enable_debug_check ( .error(1'b1) );
		end
		if (PIXELS_IN_PARALLEL != 1)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pixels_in_parallel_check ( .error(1'b1) );
		end
		if (BPS != 8)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					bps_check ( .error(1'b1) );
		end
		if (NUMBER_OF_COLOR_PLANES != 3)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					number_of_color_planes_check ( .error(1'b1) );
		end
		if (MAX_WIDTH != 2048)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					max_width_check ( .error(1'b1) );
		end
		if (PIPELINE_READY != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					pipeline_ready_check ( .error(1'b1) );
		end
		if (FIFO != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					fifo_check ( .error(1'b1) );
		end
	endgenerate

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_input_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) iib (
		.clk                    (main_clock_clk),                  //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset), //   input,   width = 1,      main_reset.reset
		.axi_st_ccd_in_tdata    (axi4s_vid_in_tdata),              //   input,  width = 24,   axi_st_ccd_in.tdata
		.axi_st_ccd_in_tvalid   (axi4s_vid_in_tvalid),             //   input,   width = 1,                .tvalid
		.axi_st_ccd_in_tready   (axi4s_vid_in_tready),             //  output,   width = 1,                .tready
		.axi_st_ccd_in_tlast    (axi4s_vid_in_tlast),              //   input,   width = 1,                .tlast
		.axi_st_ccd_in_tuser    (axi4s_vid_in_tuser),              //   input,   width = 3,                .tuser
		.axi_st_ctrl_out_tdata  (iib_axi_st_ctrl_out_tdata),       //  output,  width = 16, axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid (iib_axi_st_ctrl_out_tvalid),      //  output,   width = 1,                .tvalid
		.axi_st_ctrl_out_tready (iib_axi_st_ctrl_out_tready),      //   input,   width = 1,                .tready
		.axi_st_ctrl_out_tlast  (iib_axi_st_ctrl_out_tlast),       //  output,   width = 1,                .tlast
		.axi_st_ctrl_out_tuser  (iib_axi_st_ctrl_out_tuser),       //  output,   width = 2,                .tuser
		.axi_st_data_out_tdata  (iib_axi_st_data_out_tdata),       //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (iib_axi_st_data_out_tvalid),      //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (iib_axi_st_data_out_tready),      //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (iib_axi_st_data_out_tlast),       //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (iib_axi_st_data_out_tuser)        //  output,   width = 3,                .tuser
	);

	intel_vvp_pkt_mux #(
		.NUM_INPUTS     (2),
		.PIPELINE_READY (0),
		.DATA_WIDTH     (24)
	) mux (
		.clk                (main_clock_clk),                                                               //   input,   width = 1,   main_clock.clk
		.rst                (main_rst_bridge_out_reset_reset),                                              //   input,   width = 1,   main_reset.reset
		.axi_st_cmd_tdata   (scheduler_axi_st_cmd_mux_tdata),                                               //   input,   width = 8,   axi_st_cmd.tdata
		.axi_st_cmd_tvalid  (scheduler_axi_st_cmd_mux_tvalid),                                              //   input,   width = 1,             .tvalid
		.axi_st_cmd_tready  (scheduler_axi_st_cmd_mux_tready),                                              //  output,   width = 1,             .tready
		.axi_st_din_tdata   ({algo_comp_axi_st_data_out_tdata[23:0],duplicator_axi_st_dout_0_tdata[23:0]}), //   input,  width = 48, axi_st_din_0.tdata
		.axi_st_din_tvalid  ({algo_comp_axi_st_data_out_tvalid,duplicator_axi_st_dout_0_tvalid}),           //   input,   width = 2,             .tvalid
		.axi_st_din_tready  ({mux_axi_st_din_tready[1],mux_axi_st_din_tready[0]}),                          //  output,   width = 2,             .tready
		.axi_st_din_tlast   ({algo_comp_axi_st_data_out_tlast,duplicator_axi_st_dout_0_tlast}),             //   input,   width = 2,             .tlast
		.axi_st_din_tuser   ({algo_comp_axi_st_data_out_tuser[2:0],duplicator_axi_st_dout_0_tuser[2:0]}),   //   input,   width = 6,             .tuser
		.axi_st_dout_tdata  (mux_axi_st_dout_tdata),                                                        //  output,  width = 24,  axi_st_dout.tdata
		.axi_st_dout_tvalid (mux_axi_st_dout_tvalid),                                                       //  output,   width = 1,             .tvalid
		.axi_st_dout_tready (mux_axi_st_dout_tready),                                                       //   input,   width = 1,             .tready
		.axi_st_dout_tlast  (mux_axi_st_dout_tlast),                                                        //  output,   width = 1,             .tlast
		.axi_st_dout_tuser  (mux_axi_st_dout_tuser)                                                         //  output,   width = 3,             .tuser
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) oib (
		.clk                   (main_clock_clk),                   //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),  //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi_st_ctrl_out_tdata),  //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi_st_ctrl_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi_st_ctrl_out_tready), //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi_st_ctrl_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi_st_ctrl_out_tuser),  //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (mux_axi_st_dout_tdata),            //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (mux_axi_st_dout_tvalid),           //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (mux_axi_st_dout_tready),           //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (mux_axi_st_dout_tlast),            //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (mux_axi_st_dout_tuser),            //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),              //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),             //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),             //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),              //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)               //  output,   width = 3,               .tuser
	);

	intel_vvp_pkt_duplicator #(
		.ALWAYS_DUP_ALL (0),
		.NUM_OUTPUTS    (2),
		.PIPELINE_READY (0),
		.DATA_WIDTH     (24),
		.TOKEN_MODE     (0)
	) duplicator (
		.clk                (main_clock_clk),                                                           //   input,   width = 1,    main_clock.clk
		.rst                (main_rst_bridge_out_reset_reset),                                          //   input,   width = 1,    main_reset.reset
		.axi_st_cmd_tdata   (scheduler_axi_st_cmd_duplicator_tdata),                                    //   input,  width = 16,    axi_st_cmd.tdata
		.axi_st_cmd_tvalid  (scheduler_axi_st_cmd_duplicator_tvalid),                                   //   input,   width = 1,              .tvalid
		.axi_st_cmd_tready  (scheduler_axi_st_cmd_duplicator_tready),                                   //  output,   width = 1,              .tready
		.axi_st_din_tdata   (iib_axi_st_data_out_tdata),                                                //   input,  width = 24,    axi_st_din.tdata
		.axi_st_din_tvalid  (iib_axi_st_data_out_tvalid),                                               //   input,   width = 1,              .tvalid
		.axi_st_din_tready  (iib_axi_st_data_out_tready),                                               //  output,   width = 1,              .tready
		.axi_st_din_tlast   (iib_axi_st_data_out_tlast),                                                //   input,   width = 1,              .tlast
		.axi_st_din_tuser   (iib_axi_st_data_out_tuser),                                                //   input,   width = 3,              .tuser
		.axi_st_dout_tdata  ({duplicator_axi_st_dout_tdata[47:24],duplicator_axi_st_dout_tdata[23:0]}), //  output,  width = 48, axi_st_dout_0.tdata
		.axi_st_dout_tvalid ({duplicator_axi_st_dout_tvalid[1],duplicator_axi_st_dout_tvalid[0]}),      //  output,   width = 2,              .tvalid
		.axi_st_dout_tready ({duplicator_axi_st_dout_1_tready,duplicator_axi_st_dout_0_tready}),        //   input,   width = 2,              .tready
		.axi_st_dout_tlast  ({duplicator_axi_st_dout_tlast[1],duplicator_axi_st_dout_tlast[0]}),        //  output,   width = 2,              .tlast
		.axi_st_dout_tuser  ({duplicator_axi_st_dout_tuser[5:3],duplicator_axi_st_dout_tuser[2:0]})     //  output,   width = 6,              .tuser
	);

	intel_vvp_dil_bob_algo_comp #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0)
	) algo_comp (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_cmd_tdata),         //   input,   width = 8,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_cmd_tvalid),        //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_cmd_tready),        //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (line_buffer_axi_st_data_out_tdata),  //   input,  width = 48,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (line_buffer_axi_st_data_out_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (line_buffer_axi_st_data_out_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (line_buffer_axi_st_data_out_tlast),  //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (line_buffer_axi_st_data_out_tuser),  //   input,   width = 6,                .tuser
		.axi_st_data_out_tdata  (algo_comp_axi_st_data_out_tdata),    //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (algo_comp_axi_st_data_out_tvalid),   //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (algo_comp_axi_st_data_out_tready),   //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (algo_comp_axi_st_data_out_tlast),    //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (algo_comp_axi_st_data_out_tuser)     //  output,   width = 3,                .tuser
	);

	intel_vvp_dil_bob_scheduler #(
		.RUNTIME_CONTROL (0),
		.EXTERNAL_MODE   (0),
		.ENABLE_DEBUG    (0),
		.PIPELINE_READY  (0),
		.BOB_DIL_MODE    ("DEINTERLACE_F0_ONLY")
	) scheduler (
		.clk                          (main_clock_clk),                         //   input,   width = 1,            main_clock.clk
		.rst                          (main_rst_bridge_out_reset_reset),        //   input,   width = 1,            main_reset.reset
		.axi_st_ctrl_in_tdata         (iib_axi_st_ctrl_out_tdata),              //   input,  width = 16,        axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid        (iib_axi_st_ctrl_out_tvalid),             //   input,   width = 1,                      .tvalid
		.axi_st_ctrl_in_tready        (iib_axi_st_ctrl_out_tready),             //  output,   width = 1,                      .tready
		.axi_st_ctrl_in_tlast         (iib_axi_st_ctrl_out_tlast),              //   input,   width = 1,                      .tlast
		.axi_st_ctrl_in_tuser         (iib_axi_st_ctrl_out_tuser),              //   input,   width = 2,                      .tuser
		.axi_st_ctrl_out_tdata        (scheduler_axi_st_ctrl_out_tdata),        //  output,  width = 16,       axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid       (scheduler_axi_st_ctrl_out_tvalid),       //  output,   width = 1,                      .tvalid
		.axi_st_ctrl_out_tready       (scheduler_axi_st_ctrl_out_tready),       //   input,   width = 1,                      .tready
		.axi_st_ctrl_out_tlast        (scheduler_axi_st_ctrl_out_tlast),        //  output,   width = 1,                      .tlast
		.axi_st_ctrl_out_tuser        (scheduler_axi_st_ctrl_out_tuser),        //  output,   width = 2,                      .tuser
		.axi_st_cmd_duplicator_tdata  (scheduler_axi_st_cmd_duplicator_tdata),  //  output,  width = 16, axi_st_cmd_duplicator.tdata
		.axi_st_cmd_duplicator_tvalid (scheduler_axi_st_cmd_duplicator_tvalid), //  output,   width = 1,                      .tvalid
		.axi_st_cmd_duplicator_tready (scheduler_axi_st_cmd_duplicator_tready), //   input,   width = 1,                      .tready
		.axi_st_cmd_mux_tdata         (scheduler_axi_st_cmd_mux_tdata),         //  output,   width = 8,        axi_st_cmd_mux.tdata
		.axi_st_cmd_mux_tvalid        (scheduler_axi_st_cmd_mux_tvalid),        //  output,   width = 1,                      .tvalid
		.axi_st_cmd_mux_tready        (scheduler_axi_st_cmd_mux_tready),        //   input,   width = 1,                      .tready
		.axi_st_cmd_buff_tdata        (scheduler_axi_st_cmd_buff_tdata),        //  output,  width = 24,       axi_st_cmd_buff.tdata
		.axi_st_cmd_buff_tvalid       (scheduler_axi_st_cmd_buff_tvalid),       //  output,   width = 1,                      .tvalid
		.axi_st_cmd_buff_tready       (scheduler_axi_st_cmd_buff_tready),       //   input,   width = 1,                      .tready
		.axi_st_cmd_tdata             (scheduler_axi_st_cmd_tdata),             //  output,   width = 8,            axi_st_cmd.tdata
		.axi_st_cmd_tvalid            (scheduler_axi_st_cmd_tvalid),            //  output,   width = 1,                      .tvalid
		.axi_st_cmd_tready            (scheduler_axi_st_cmd_tready),            //   input,   width = 1,                      .tready
		.av_mm_slave_address          (5'b00000),                               // (terminated),                                    
		.av_mm_slave_write            (1'b0),                                   // (terminated),                                    
		.av_mm_slave_byteenable       (4'b0000),                                // (terminated),                                    
		.av_mm_slave_writedata        (32'b00000000000000000000000000000000),   // (terminated),                                    
		.av_mm_slave_read             (1'b0),                                   // (terminated),                                    
		.av_mm_slave_readdata         (),                                       // (terminated),                                    
		.av_mm_slave_readdatavalid    (),                                       // (terminated),                                    
		.av_mm_slave_waitrequest      ()                                        // (terminated),                                    
	);

	intel_vvp_line_buffer #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.MAX_WIDTH              (2048),
		.NUM_LINES              (2),
		.ENABLE_RESEND          (1),
		.CMD_COMPATIBILITY      (0),
		.ENABLE_RESPONSE        (0),
		.PIPELINE_READY         (0),
		.DEVICE_FAMILY          ("Cyclone 10 GX")
	) line_buffer (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_cmd_buff_tdata),    //   input,  width = 24,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_cmd_buff_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_cmd_buff_tready),   //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (duplicator_axi_st_dout_1_tdata),     //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (duplicator_axi_st_dout_1_tvalid),    //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (duplicator_axi_st_dout_1_tready),    //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (duplicator_axi_st_dout_1_tlast),     //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (duplicator_axi_st_dout_1_tuser),     //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (line_buffer_axi_st_data_out_tdata),  //  output,  width = 48, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (line_buffer_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (line_buffer_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (line_buffer_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (line_buffer_axi_st_data_out_tuser),  //  output,   width = 6,                .tuser
		.axi_st_resp_tdata      (),                                   // (terminated),                              
		.axi_st_resp_tvalid     (),                                   // (terminated),                              
		.axi_st_resp_tready     (1'b0)                                // (terminated),                              
	);

	assign algo_comp_axi_st_data_out_tready = { mux_axi_st_din_tready[1] };

	assign duplicator_axi_st_dout_0_tdata = { duplicator_axi_st_dout_tdata[23:0] };

	assign duplicator_axi_st_dout_0_tlast = { duplicator_axi_st_dout_tlast[0] };

	assign duplicator_axi_st_dout_0_tready = { mux_axi_st_din_tready[0] };

	assign duplicator_axi_st_dout_0_tuser = { duplicator_axi_st_dout_tuser[2:0] };

	assign duplicator_axi_st_dout_0_tvalid = { duplicator_axi_st_dout_tvalid[0] };

	assign duplicator_axi_st_dout_1_tdata = { duplicator_axi_st_dout_tdata[47:24] };

	assign duplicator_axi_st_dout_1_tlast = { duplicator_axi_st_dout_tlast[1] };

	assign duplicator_axi_st_dout_1_tuser = { duplicator_axi_st_dout_tuser[5:3] };

	assign duplicator_axi_st_dout_1_tvalid = { duplicator_axi_st_dout_tvalid[1] };

endmodule
