
namespace eval pipeline_intel_vvp_scaler_0 {
  proc get_design_libraries {} {
    set libraries [dict create]
    dict set libraries altera_common_sv_packages              1
    dict set libraries intel_vvp_reset_sync_2440              1
    dict set libraries intel_vvp_input_interface_bridge_2440  1
    dict set libraries intel_vvp_output_interface_bridge_2440 1
    dict set libraries intel_vvp_line_buffer_2440             1
    dict set libraries intel_vvp_vert_scaler_scheduler_2451   1
    dict set libraries intel_vvp_scaler_line_select_2451      1
    dict set libraries intel_vvp_vert_scaler_algo_comp_2451   1
    dict set libraries intel_vvp_round_sat_algo_comp_2450     1
    dict set libraries intel_vvp_reset_bridge_2440            1
    dict set libraries intel_vvp_horiz_scaler_cmd_2451        1
    dict set libraries intel_vvp_scaler_luma_split_2451       1
    dict set libraries intel_vvp_scaler_output_switch_2451    1
    dict set libraries intel_vvp_fifo_core_2440               1
    dict set libraries intel_vvp_horiz_scaler_algo_comp_2451  1
    dict set libraries intel_vvp_scaler_seq_par_luma_2451     1
    dict set libraries intel_vvp_pkt_duplicator_2450          1
    dict set libraries intel_vvp_scaler_seq_par_chroma_2451   1
    dict set libraries intel_vvp_scaler_h_macro_2451          1
    dict set libraries intel_vvp_ro_reg_servicer_2441         1
    dict set libraries intel_vvp_slave_data_split_2441        1
    dict set libraries intel_vvp_mm_agent_reset_hold_2440     1
    dict set libraries altera_merlin_master_translator_193    1
    dict set libraries altera_merlin_slave_translator_191     1
    dict set libraries altera_mm_interconnect_1920            1
    dict set libraries intel_vvp_slave_front_end_2441         1
    dict set libraries intel_vvp_scaler_coeff_handler_2451    1
    dict set libraries intel_vvp_scaler_2451                  1
    dict set libraries pipeline_intel_vvp_scaler_0            1
    return $libraries
  }
  
  proc get_memory_files {QSYS_SIMDIR QUARTUS_INSTALL_DIR} {
    set memory_files [list]
    return $memory_files
  }
  
  proc get_common_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR} {
    set design_files [dict create]
    dict set design_files "altera_common_sv_packages::mentor_intel_vvp_common_pkg"  "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_input_interface_bridge_2440/sim/mentor/intel_vvp_common_pkg.sv"]\"  -work altera_common_sv_packages"
    dict set design_files "altera_common_sv_packages::mentor_intel_mtm_common_pkg"  "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/intel_mtm_common_pkg.sv"]\"  -work altera_common_sv_packages"           
    dict set design_files "altera_common_sv_packages::mentor_intel_vvp_utility_pkg" "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/intel_vvp_utility_pkg.sv"]\"  -work altera_common_sv_packages"          
    dict set design_files "altera_common_sv_packages::mentor_intel_vvp_scaler_pkg"  "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/intel_vvp_scaler_pkg.sv"]\"  -work altera_common_sv_packages" 
    return $design_files
  }
  
  proc get_design_files {USER_DEFINED_COMPILE_OPTIONS USER_DEFINED_VERILOG_COMPILE_OPTIONS USER_DEFINED_VHDL_COMPILE_OPTIONS QSYS_SIMDIR QUARTUS_INSTALL_DIR} {
    set design_files [list]
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_reset_sync_2440/sim/mentor/src_hdl/intel_vvp_reset_sync.sv"]\" -L altera_common_sv_packages -work intel_vvp_reset_sync_2440"                                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_input_interface_bridge_2440/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_input_interface_bridge_2440"                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_input_interface_bridge_2440/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_input_interface_bridge_2440"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_input_interface_bridge_2440/sim/mentor/src_hdl/intel_vvp_input_interface_bridge.sv"]\" -L altera_common_sv_packages -work intel_vvp_input_interface_bridge_2440"                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_output_interface_bridge_2440/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_output_interface_bridge_2440"                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_output_interface_bridge_2440/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_output_interface_bridge_2440"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_output_interface_bridge_2440/sim/mentor/src_hdl/intel_vvp_output_interface_bridge.sv"]\" -L altera_common_sv_packages -work intel_vvp_output_interface_bridge_2440"                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/src_hdl/intel_vvp_line_buffer_no_resend.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/src_hdl/intel_vvp_line_buffer_resend.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/src_hdl/intel_vvp_line_buffer_ram.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/src_hdl/intel_vvp_line_buffer_cmd_mngr.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_line_buffer_2440/sim/mentor/src_hdl/intel_vvp_line_buffer.sv"]\" -L altera_common_sv_packages -work intel_vvp_line_buffer_2440"                                                     
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/intel_vvp_pipelined_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/intel_vvp_common_slave_interface.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/intel_vvp_serial_divider.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_scheduler_ext_ctrl.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_scheduler_int_ctrl.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_scheduler_ctrl_out.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_scheduler_main.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_scheduler_init.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_scheduler_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_scheduler.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_scheduler_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_line_select_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_line_select_2451"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_line_select_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_line_select_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_line_select_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_line_select_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_line_select_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_line_select_2451"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_line_select_2451/sim/mentor/src_hdl/intel_vvp_scaler_line_select.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_line_select_2451"                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_add_tree.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_mult.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_2_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_3_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_4_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_pipelined_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_edge_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_mirror.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_algo_comp_bl.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_algo_comp_coeff.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_vert_scaler_algo_comp.sv"]\" -L altera_common_sv_packages -work intel_vvp_vert_scaler_algo_comp_2451"                       
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_vert_scaler_algo_comp_2451/sim/pipeline_intel_vvp_scaler_0_intel_vvp_vert_scaler_algo_comp_2451_7rzm5sa.v"]\"  -work intel_vvp_vert_scaler_algo_comp_2451"                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_round_sat_algo_comp_2450/sim/mentor/intel_vvp_round_sat.sv"]\" -L altera_common_sv_packages -work intel_vvp_round_sat_algo_comp_2450"                                               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_round_sat_algo_comp_2450/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_round_sat_algo_comp_2450"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_round_sat_algo_comp_2450/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_round_sat_algo_comp_2450"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_round_sat_algo_comp_2450/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_round_sat_algo_comp_2450"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_round_sat_algo_comp_2450/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_round_sat_algo_comp_2450"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_round_sat_algo_comp_2450/sim/mentor/src_hdl/intel_vvp_round_sat_algo_comp.sv"]\" -L altera_common_sv_packages -work intel_vvp_round_sat_algo_comp_2450"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_reset_bridge_2440/sim/mentor/src_hdl/intel_vvp_reset_bridge.sv"]\" -L altera_common_sv_packages -work intel_vvp_reset_bridge_2440"                                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_cmd_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_cmd.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_cmd_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_luma_split_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_luma_split_2451"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_luma_split_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_luma_split_2451"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_luma_split_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_luma_split_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_luma_split_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_luma_split_2451"                                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_luma_split_2451/sim/mentor/src_hdl/intel_vvp_scaler_luma_split.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_luma_split_2451"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_output_switch_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_output_switch_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_output_switch_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_output_switch_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_output_switch_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_output_switch_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_output_switch_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_output_switch_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_output_switch_2451/sim/mentor/src_hdl/intel_vvp_scaler_output_switch.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_output_switch_2451"                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_binary_to_gray.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_gray_to_binary.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_counter_clock_crosser.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_fifo_output.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_common_fifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                                 
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_axi_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_axi_fifo_output.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/intel_vvp_axi_fifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_fifo_core_2440/sim/mentor/src_hdl/intel_vvp_fifo_core.sv"]\" -L altera_common_sv_packages -work intel_vvp_fifo_core_2440"                                                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_add_tree.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_mult.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_2_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_3_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_4_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_round_sat.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_rotate_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_pip_bunch.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_pip_merge.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_shift_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_pipelined_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                     
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_edge_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_mirror.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_h_kernel.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_h_kernel_mirror.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_h_kernel_422.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_serial_divider.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_binary_to_gray.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_gray_to_binary.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_counter_clock_crosser.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_fifo_output.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_common_fifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_fifo_output.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_fifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_token_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_base.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_init_ready.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_init_valid.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_init_phase.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_ctrl.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_coeff.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_infifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_outfifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_backend.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                    
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/pipeline_intel_vvp_scaler_0_intel_vvp_horiz_scaler_algo_comp_2451_vr7r2ma.v"]\"  -work intel_vvp_horiz_scaler_algo_comp_2451"                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_shift_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_pack_simple.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_unpack_simple.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_pack_hard.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_unpack_hard.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_luma_2451/sim/mentor/src_hdl/intel_vvp_scaler_seq_par_luma.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_luma_2451"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_pkt_duplicator_2450/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_pkt_duplicator_2450"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_pkt_duplicator_2450/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_pkt_duplicator_2450"                                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_pkt_duplicator_2450/sim/mentor/src_hdl/intel_vvp_pkt_duplicator.sv"]\" -L altera_common_sv_packages -work intel_vvp_pkt_duplicator_2450"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_add_tree.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_mult.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_2_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_3_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_4_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_mult_add.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_round_sat.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_rotate_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_pip_bunch.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_pip_merge.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_shift_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_pipelined_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                     
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_edge_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_mirror.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_h_kernel.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_h_kernel_mirror.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_h_kernel_422.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_serial_divider.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_binary_to_gray.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_gray_to_binary.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_counter_clock_crosser.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_fifo_output.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_common_fifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_fifo_output.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_fifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_token_fifo_input.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_base.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_init_ready.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_init_valid.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/intel_vvp_scaler_iterative_init_phase.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_ctrl.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_coeff.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"              
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_infifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_outfifo.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp_backend.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/mentor/src_hdl/intel_vvp_horiz_scaler_algo_comp.sv"]\" -L altera_common_sv_packages -work intel_vvp_horiz_scaler_algo_comp_2451"                    
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_horiz_scaler_algo_comp_2451/sim/pipeline_intel_vvp_scaler_0_intel_vvp_horiz_scaler_algo_comp_2451_dexbd5q.v"]\"  -work intel_vvp_horiz_scaler_algo_comp_2451"                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_shift_mux.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_pack_simple.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_unpack_simple.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                       
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_pack_hard.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                           
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_unpack_hard.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                  
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_seq_par_chroma_2451/sim/mentor/src_hdl/intel_vvp_scaler_seq_par_chroma.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_seq_par_chroma_2451"                       
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_h_macro_2451/sim/pipeline_intel_vvp_scaler_0_intel_vvp_scaler_h_macro_2451_puxeyxi.v"]\"  -work intel_vvp_scaler_h_macro_2451"                                                   
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_ro_reg_servicer_2441/sim/mentor/src_hdl/intel_vvp_ro_reg_servicer.sv"]\" -L altera_common_sv_packages -work intel_vvp_ro_reg_servicer_2441"                                         
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_ro_reg_servicer_2441/sim/pipeline_intel_vvp_scaler_0_intel_vvp_ro_reg_servicer_2441_tki25pi.sv"]\" -L altera_common_sv_packages -work intel_vvp_ro_reg_servicer_2441"               
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_slave_data_split_2441/sim/mentor/src_hdl/intel_vvp_slave_data_split.sv"]\" -L altera_common_sv_packages -work intel_vvp_slave_data_split_2441"                                      
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_mm_agent_reset_hold_2440/sim/mentor/src_hdl/intel_vvp_mm_agent_reset_hold.sv"]\" -L altera_common_sv_packages -work intel_vvp_mm_agent_reset_hold_2440"                             
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_merlin_master_translator_193/sim/pipeline_intel_vvp_scaler_0_altera_merlin_master_translator_193_lgcew2q.sv"]\" -L altera_common_sv_packages -work altera_merlin_master_translator_193"
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_merlin_slave_translator_191/sim/pipeline_intel_vvp_scaler_0_altera_merlin_slave_translator_191_xg7rzxi.sv"]\" -L altera_common_sv_packages -work altera_merlin_slave_translator_191"   
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_mm_interconnect_1920/sim/pipeline_intel_vvp_scaler_0_altera_mm_interconnect_1920_xv3tk3a.v"]\"  -work altera_mm_interconnect_1920"                                                         
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_mm_interconnect_1920/sim/pipeline_intel_vvp_scaler_0_altera_mm_interconnect_1920_uaqnt7y.v"]\"  -work altera_mm_interconnect_1920"                                                         
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_slave_front_end_2441/sim/pipeline_intel_vvp_scaler_0_intel_vvp_slave_front_end_2441_im77voa.v"]\"  -work intel_vvp_slave_front_end_2441"                                                
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_coeff_handler_2451/sim/mentor/intel_vvp_axi_zero_pad.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_coeff_handler_2451"                                          
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_coeff_handler_2451/sim/mentor/intel_vvp_axi_zero_strip.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_coeff_handler_2451"                                        
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_coeff_handler_2451/sim/mentor/intel_vvp_axi_pipeline_stage.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_coeff_handler_2451"                                    
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_coeff_handler_2451/sim/mentor/intel_vvp_axi_master.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_coeff_handler_2451"                                            
    lappend design_files "vlog -sv $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_coeff_handler_2451/sim/mentor/src_hdl/intel_vvp_scaler_coeff_handler.sv"]\" -L altera_common_sv_packages -work intel_vvp_scaler_coeff_handler_2451"                          
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_mm_interconnect_1920/sim/pipeline_intel_vvp_scaler_0_altera_mm_interconnect_1920_vevxpda.v"]\"  -work altera_mm_interconnect_1920"                                                         
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../altera_mm_interconnect_1920/sim/pipeline_intel_vvp_scaler_0_altera_mm_interconnect_1920_vg4v6pi.v"]\"  -work altera_mm_interconnect_1920"                                                         
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/../intel_vvp_scaler_2451/sim/pipeline_intel_vvp_scaler_0_intel_vvp_scaler_2451_t4an5sa.v"]\"  -work intel_vvp_scaler_2451"                                                                           
    lappend design_files "vlog $USER_DEFINED_VERILOG_COMPILE_OPTIONS $USER_DEFINED_COMPILE_OPTIONS  \"[normalize_path "$QSYS_SIMDIR/pipeline_intel_vvp_scaler_0.v"]\"  -work pipeline_intel_vvp_scaler_0"                                                                                                                                
    return $design_files
  }
  
  proc get_non_duplicate_elab_option {ELAB_OPTIONS NEW_ELAB_OPTION} {
    set IS_DUPLICATE [string first $NEW_ELAB_OPTION $ELAB_OPTIONS]
    if {$IS_DUPLICATE == -1} {
      return $NEW_ELAB_OPTION
    } else {
      return ""
    }
  }
  
  
  proc get_elab_options {SIMULATOR_TOOL_BITNESS} {
    set ELAB_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ELAB_OPTIONS
  }
  
  
  proc get_sim_options {SIMULATOR_TOOL_BITNESS} {
    set SIM_OPTIONS ""
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $SIM_OPTIONS
  }
  
  
  proc get_env_variables {SIMULATOR_TOOL_BITNESS} {
    set ENV_VARIABLES [dict create]
    set LD_LIBRARY_PATH [dict create]
    dict set ENV_VARIABLES "LD_LIBRARY_PATH" $LD_LIBRARY_PATH
    if ![ string match "bit_64" $SIMULATOR_TOOL_BITNESS ] {
    } else {
    }
    return $ENV_VARIABLES
  }
  
  
  proc normalize_path {FILEPATH} {
      if {[catch { package require fileutil } err]} { 
          return $FILEPATH 
      } 
      set path [fileutil::lexnormalize [file join [pwd] $FILEPATH]]  
      if {[file pathtype $FILEPATH] eq "relative"} { 
          set path [fileutil::relative [pwd] $path] 
      } 
      return $path 
  } 
  proc get_dpi_libraries {QSYS_SIMDIR} {
    set libraries [dict create]
    
    return $libraries
  }
  
}
