// system.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system (
		input  wire        clk_clk,                              //                           clk.clk
		input  wire [23:0] intel_vvp_crs_0_axi4s_vid_in_tdata,   //  intel_vvp_crs_0_axi4s_vid_in.tdata
		input  wire        intel_vvp_crs_0_axi4s_vid_in_tvalid,  //                              .tvalid
		output wire        intel_vvp_crs_0_axi4s_vid_in_tready,  //                              .tready
		input  wire        intel_vvp_crs_0_axi4s_vid_in_tlast,   //                              .tlast
		input  wire [2:0]  intel_vvp_crs_0_axi4s_vid_in_tuser,   //                              .tuser
		output wire [23:0] intel_vvp_crs_0_axi4s_vid_out_tdata,  // intel_vvp_crs_0_axi4s_vid_out.tdata
		output wire        intel_vvp_crs_0_axi4s_vid_out_tvalid, //                              .tvalid
		input  wire        intel_vvp_crs_0_axi4s_vid_out_tready, //                              .tready
		output wire        intel_vvp_crs_0_axi4s_vid_out_tlast,  //                              .tlast
		output wire [2:0]  intel_vvp_crs_0_axi4s_vid_out_tuser,  //                              .tuser
		output wire [23:0] intel_vvp_tpg_0_axi4s_vid_out_tdata,  // intel_vvp_tpg_0_axi4s_vid_out.tdata
		output wire        intel_vvp_tpg_0_axi4s_vid_out_tvalid, //                              .tvalid
		input  wire        intel_vvp_tpg_0_axi4s_vid_out_tready, //                              .tready
		output wire        intel_vvp_tpg_0_axi4s_vid_out_tlast,  //                              .tlast
		output wire [2:0]  intel_vvp_tpg_0_axi4s_vid_out_tuser,  //                              .tuser
		input  wire        reset_reset                           //                         reset.reset
	);

	wire    clock_in_out_clk_clk;           // clock_in:out_clk -> [intel_vvp_crs_0:main_clock_clk, intel_vvp_tpg_0:main_clock_clk, reset_in:clk, rst_controller:clk]
	wire    rst_controller_reset_out_reset; // rst_controller:reset_out -> [intel_vvp_crs_0:main_reset_reset, intel_vvp_tpg_0:main_reset_reset]
	wire    reset_in_out_reset_reset;       // reset_in:out_reset -> rst_controller:reset_in0

	system_clock_in clock_in (
		.in_clk  (clk_clk),              //   input,  width = 1,  in_clk.clk
		.out_clk (clock_in_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	system_intel_vvp_crs_0 intel_vvp_crs_0 (
		.main_clock_clk       (clock_in_out_clk_clk),                 //   input,   width = 1,    main_clock.clk
		.main_reset_reset     (rst_controller_reset_out_reset),       //   input,   width = 1,    main_reset.reset
		.axi4s_vid_in_tdata   (intel_vvp_crs_0_axi4s_vid_in_tdata),   //   input,  width = 24,  axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid  (intel_vvp_crs_0_axi4s_vid_in_tvalid),  //   input,   width = 1,              .tvalid
		.axi4s_vid_in_tready  (intel_vvp_crs_0_axi4s_vid_in_tready),  //  output,   width = 1,              .tready
		.axi4s_vid_in_tlast   (intel_vvp_crs_0_axi4s_vid_in_tlast),   //   input,   width = 1,              .tlast
		.axi4s_vid_in_tuser   (intel_vvp_crs_0_axi4s_vid_in_tuser),   //   input,   width = 3,              .tuser
		.axi4s_vid_out_tdata  (intel_vvp_crs_0_axi4s_vid_out_tdata),  //  output,  width = 24, axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid (intel_vvp_crs_0_axi4s_vid_out_tvalid), //  output,   width = 1,              .tvalid
		.axi4s_vid_out_tready (intel_vvp_crs_0_axi4s_vid_out_tready), //   input,   width = 1,              .tready
		.axi4s_vid_out_tlast  (intel_vvp_crs_0_axi4s_vid_out_tlast),  //  output,   width = 1,              .tlast
		.axi4s_vid_out_tuser  (intel_vvp_crs_0_axi4s_vid_out_tuser)   //  output,   width = 3,              .tuser
	);

	system_intel_vvp_tpg_0 intel_vvp_tpg_0 (
		.main_clock_clk       (clock_in_out_clk_clk),                 //   input,   width = 1,    main_clock.clk
		.main_reset_reset     (rst_controller_reset_out_reset),       //   input,   width = 1,    main_reset.reset
		.axi4s_vid_out_tdata  (intel_vvp_tpg_0_axi4s_vid_out_tdata),  //  output,  width = 24, axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid (intel_vvp_tpg_0_axi4s_vid_out_tvalid), //  output,   width = 1,              .tvalid
		.axi4s_vid_out_tready (intel_vvp_tpg_0_axi4s_vid_out_tready), //   input,   width = 1,              .tready
		.axi4s_vid_out_tlast  (intel_vvp_tpg_0_axi4s_vid_out_tlast),  //  output,   width = 1,              .tlast
		.axi4s_vid_out_tuser  (intel_vvp_tpg_0_axi4s_vid_out_tuser)   //  output,   width = 3,              .tuser
	);

	system_reset_in reset_in (
		.clk       (clock_in_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset  (reset_reset),              //   input,  width = 1,  in_reset.reset
		.out_reset (reset_in_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset_in_out_reset_reset),       //   input,  width = 1, reset_in0.reset
		.clk            (clock_in_out_clk_clk),           //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

endmodule
