// pipeline_intel_vvp_pipeline2_0_intel_vvp_pipeline2_10_s53v24q.v

// This file was auto-generated from intel_vvp_pipeline2_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module pipeline_intel_vvp_pipeline2_0_intel_vvp_pipeline2_10_s53v24q (
		input  wire        clk_clk,                          //                  clk.clk,           Clock Input
		input  wire        reset_reset,                      //                reset.reset,         Reset Input
		output wire        s0_waitrequest,                   //                   s0.waitrequest,   Wait request to Avalon Memory Mapped Host, indicates agent is not ready
		output wire [31:0] s0_readdata,                      //                     .readdata,      Read Data output from Avalon Memory Mapped Agent
		output wire        s0_readdatavalid,                 //                     .readdatavalid, Valid read data indication from Avalon Memory Mapped Agent
		input  wire [0:0]  s0_burstcount,                    //                     .burstcount,    Indicates number of burst transfers in each burst
		input  wire [31:0] s0_writedata,                     //                     .writedata,     Write Data from Avalon Memory Mapped Host
		input  wire [27:0] s0_address,                       //                     .address,       Address output from Avalon Memory Mapped Host
		input  wire        s0_write,                         //                     .write,         Write command from Avalon Memory Mapped Host
		input  wire        s0_read,                          //                     .read,          Read command from Avalon Memory Mapped Host
		input  wire [3:0]  s0_byteenable,                    //                     .byteenable,    Indicates valid read/write data location
		input  wire        s0_debugaccess,                   //                     .debugaccess
		input  wire [23:0] s_axis_video_in_tdata,            //      s_axis_video_in.tdata
		input  wire        s_axis_video_in_tvalid,           //                     .tvalid
		output wire        s_axis_video_in_tready,           //                     .tready
		input  wire        s_axis_video_in_tlast,            //                     .tlast
		input  wire [2:0]  s_axis_video_in_tuser,            //                     .tuser
		output wire [23:0] m_axis_video_out_tdata,           //     m_axis_video_out.tdata
		output wire        m_axis_video_out_tvalid,          //                     .tvalid
		input  wire        m_axis_video_out_tready,          //                     .tready
		output wire        m_axis_video_out_tlast,           //                     .tlast
		output wire [2:0]  m_axis_video_out_tuser,           //                     .tuser
		output wire [0:0]  frc_emif_mem_mem_cke,             //         frc_emif_mem.mem_cke,       Clock Enable channel 0.
		output wire [0:0]  frc_emif_mem_mem_odt,             //                     .mem_odt,       On-Die Termination channel 0.
		output wire [0:0]  frc_emif_mem_mem_cs_n,            //                     .mem_cs_n,      Chip Select channel 0.
		output wire [16:0] frc_emif_mem_mem_a,               //                     .mem_a,         Address channel 0.
		output wire [1:0]  frc_emif_mem_mem_ba,              //                     .mem_ba,        Bank Address channel 0.
		output wire [0:0]  frc_emif_mem_mem_bg,              //                     .mem_bg,        Bank Group channel 0.
		output wire        frc_emif_mem_mem_act_n,           //                     .mem_act_n,     Activation Command channel 0.
		output wire        frc_emif_mem_mem_par,             //                     .mem_par,       Command/Address Parity channel 0.
		inout  wire [31:0] frc_emif_mem_mem_dq,              //                     .mem_dq,        Data (read/write) channel 0.
		inout  wire [3:0]  frc_emif_mem_mem_dqs_t,           //                     .mem_dqs_t,     Data Strobe (true) channel 0.
		inout  wire [3:0]  frc_emif_mem_mem_dqs_c,           //                     .mem_dqs_c,     Data Strobe (complement) channel 0.
		input  wire        frc_emif_mem_mem_alert_n,         //                     .mem_alert_n,   Indicates Write CRC Error channel 0.
		output wire [0:0]  frc_emif_mem_ck_mem_ck_t,         //      frc_emif_mem_ck.mem_ck_t,      CK Clock (true) channel 0.
		output wire [0:0]  frc_emif_mem_ck_mem_ck_c,         //                     .mem_ck_c,      CK Clock (complement) channel 0.
		output wire        frc_emif_mem_reset_n_mem_reset_n, // frc_emif_mem_reset_n.mem_reset_n,   Asynchronous Reset channel 0.
		input  wire        frc_emif_oct_oct_rzqin,           //         frc_emif_oct.oct_rzqin,     Calibrated On-Chip Termination (OCT) input pin channel 0.
		input  wire        frc_emif_ref_clk_clk              //     frc_emif_ref_clk.clk,           PLL reference clock input.
	);

	wire          intel_vvp_scaler_0_axi4s_vid_out_tvalid;                                // intel_vvp_scaler_0:axi4s_vid_out_tvalid -> ltf_conv_0:axi4s_vid_in_tvalid
	wire    [2:0] intel_vvp_scaler_0_axi4s_vid_out_tuser;                                 // intel_vvp_scaler_0:axi4s_vid_out_tuser -> ltf_conv_0:axi4s_vid_in_tuser
	wire          intel_vvp_scaler_0_axi4s_vid_out_tready;                                // ltf_conv_0:axi4s_vid_in_tready -> intel_vvp_scaler_0:axi4s_vid_out_tready
	wire   [23:0] intel_vvp_scaler_0_axi4s_vid_out_tdata;                                 // intel_vvp_scaler_0:axi4s_vid_out_tdata -> ltf_conv_0:axi4s_vid_in_tdata
	wire          intel_vvp_scaler_0_axi4s_vid_out_tlast;                                 // intel_vvp_scaler_0:axi4s_vid_out_tlast -> ltf_conv_0:axi4s_vid_in_tlast
	wire          ltf_conv_0_axi4s_vid_out_tvalid;                                        // ltf_conv_0:axi4s_vid_out_tvalid -> intel_vvp_vfb_0:axi4s_vid_in_tvalid
	wire    [2:0] ltf_conv_0_axi4s_vid_out_tuser;                                         // ltf_conv_0:axi4s_vid_out_tuser -> intel_vvp_vfb_0:axi4s_vid_in_tuser
	wire          ltf_conv_0_axi4s_vid_out_tready;                                        // intel_vvp_vfb_0:axi4s_vid_in_tready -> ltf_conv_0:axi4s_vid_out_tready
	wire   [23:0] ltf_conv_0_axi4s_vid_out_tdata;                                         // ltf_conv_0:axi4s_vid_out_tdata -> intel_vvp_vfb_0:axi4s_vid_in_tdata
	wire          ltf_conv_0_axi4s_vid_out_tlast;                                         // ltf_conv_0:axi4s_vid_out_tlast -> intel_vvp_vfb_0:axi4s_vid_in_tlast
	wire          mm_bridge_0_m0_waitrequest;                                             // mm_interconnect_0:mm_bridge_0_m0_waitrequest -> mm_bridge_0:m0_waitrequest
	wire   [31:0] mm_bridge_0_m0_readdata;                                                // mm_interconnect_0:mm_bridge_0_m0_readdata -> mm_bridge_0:m0_readdata
	wire          mm_bridge_0_m0_debugaccess;                                             // mm_bridge_0:m0_debugaccess -> mm_interconnect_0:mm_bridge_0_m0_debugaccess
	wire   [27:0] mm_bridge_0_m0_address;                                                 // mm_bridge_0:m0_address -> mm_interconnect_0:mm_bridge_0_m0_address
	wire          mm_bridge_0_m0_read;                                                    // mm_bridge_0:m0_read -> mm_interconnect_0:mm_bridge_0_m0_read
	wire    [3:0] mm_bridge_0_m0_byteenable;                                              // mm_bridge_0:m0_byteenable -> mm_interconnect_0:mm_bridge_0_m0_byteenable
	wire          mm_bridge_0_m0_readdatavalid;                                           // mm_interconnect_0:mm_bridge_0_m0_readdatavalid -> mm_bridge_0:m0_readdatavalid
	wire   [31:0] mm_bridge_0_m0_writedata;                                               // mm_bridge_0:m0_writedata -> mm_interconnect_0:mm_bridge_0_m0_writedata
	wire          mm_bridge_0_m0_write;                                                   // mm_bridge_0:m0_write -> mm_interconnect_0:mm_bridge_0_m0_write
	wire    [0:0] mm_bridge_0_m0_burstcount;                                              // mm_bridge_0:m0_burstcount -> mm_interconnect_0:mm_bridge_0_m0_burstcount
	wire   [31:0] mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_readdata;      // intel_vvp_scaler_0:av_mm_control_agent_readdata -> mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_readdata
	wire          mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_waitrequest;   // intel_vvp_scaler_0:av_mm_control_agent_waitrequest -> mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_address;       // mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_address -> intel_vvp_scaler_0:av_mm_control_agent_address
	wire          mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_read;          // mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_read -> intel_vvp_scaler_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_byteenable;    // mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_byteenable -> intel_vvp_scaler_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_readdatavalid; // intel_vvp_scaler_0:av_mm_control_agent_readdatavalid -> mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_write;         // mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_write -> intel_vvp_scaler_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_writedata;     // mm_interconnect_0:intel_vvp_scaler_0_av_mm_control_agent_writedata -> intel_vvp_scaler_0:av_mm_control_agent_writedata
	wire   [31:0] mm_interconnect_0_ltf_conv_0_av_mm_control_agent_readdata;              // ltf_conv_0:av_mm_control_agent_readdata -> mm_interconnect_0:ltf_conv_0_av_mm_control_agent_readdata
	wire          mm_interconnect_0_ltf_conv_0_av_mm_control_agent_waitrequest;           // ltf_conv_0:av_mm_control_agent_waitrequest -> mm_interconnect_0:ltf_conv_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_0_ltf_conv_0_av_mm_control_agent_address;               // mm_interconnect_0:ltf_conv_0_av_mm_control_agent_address -> ltf_conv_0:av_mm_control_agent_address
	wire          mm_interconnect_0_ltf_conv_0_av_mm_control_agent_read;                  // mm_interconnect_0:ltf_conv_0_av_mm_control_agent_read -> ltf_conv_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_0_ltf_conv_0_av_mm_control_agent_byteenable;            // mm_interconnect_0:ltf_conv_0_av_mm_control_agent_byteenable -> ltf_conv_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_0_ltf_conv_0_av_mm_control_agent_readdatavalid;         // ltf_conv_0:av_mm_control_agent_readdatavalid -> mm_interconnect_0:ltf_conv_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_0_ltf_conv_0_av_mm_control_agent_write;                 // mm_interconnect_0:ltf_conv_0_av_mm_control_agent_write -> ltf_conv_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_0_ltf_conv_0_av_mm_control_agent_writedata;             // mm_interconnect_0:ltf_conv_0_av_mm_control_agent_writedata -> ltf_conv_0:av_mm_control_agent_writedata
	wire   [31:0] mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_readdata;         // intel_vvp_vfb_0:av_mm_control_agent_readdata -> mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_readdata
	wire          mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_waitrequest;      // intel_vvp_vfb_0:av_mm_control_agent_waitrequest -> mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_waitrequest
	wire    [6:0] mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_address;          // mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_address -> intel_vvp_vfb_0:av_mm_control_agent_address
	wire          mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_read;             // mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_read -> intel_vvp_vfb_0:av_mm_control_agent_read
	wire    [3:0] mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_byteenable;       // mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_byteenable -> intel_vvp_vfb_0:av_mm_control_agent_byteenable
	wire          mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_readdatavalid;    // intel_vvp_vfb_0:av_mm_control_agent_readdatavalid -> mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_readdatavalid
	wire          mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_write;            // mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_write -> intel_vvp_vfb_0:av_mm_control_agent_write
	wire   [31:0] mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_writedata;        // mm_interconnect_0:intel_vvp_vfb_0_av_mm_control_agent_writedata -> intel_vvp_vfb_0:av_mm_control_agent_writedata
	wire   [26:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_awaddr;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_awaddr -> frc_emif_0:s0_axi4lite_awaddr
	wire    [1:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_bresp;                         // frc_emif_0:s0_axi4lite_bresp -> mm_interconnect_0:frc_emif_0_s0_axi4lite_bresp
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_arready;                       // frc_emif_0:s0_axi4lite_arready -> mm_interconnect_0:frc_emif_0_s0_axi4lite_arready
	wire   [31:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_rdata;                         // frc_emif_0:s0_axi4lite_rdata -> mm_interconnect_0:frc_emif_0_s0_axi4lite_rdata
	wire    [3:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_wstrb;                         // mm_interconnect_0:frc_emif_0_s0_axi4lite_wstrb -> frc_emif_0:s0_axi4lite_wstrb
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_wready;                        // frc_emif_0:s0_axi4lite_wready -> mm_interconnect_0:frc_emif_0_s0_axi4lite_wready
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_awready;                       // frc_emif_0:s0_axi4lite_awready -> mm_interconnect_0:frc_emif_0_s0_axi4lite_awready
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_rready;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_rready -> frc_emif_0:s0_axi4lite_rready
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_bready;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_bready -> frc_emif_0:s0_axi4lite_bready
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_wvalid;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_wvalid -> frc_emif_0:s0_axi4lite_wvalid
	wire   [26:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_araddr;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_araddr -> frc_emif_0:s0_axi4lite_araddr
	wire    [2:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_arprot;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_arprot -> frc_emif_0:s0_axi4lite_arprot
	wire    [1:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_rresp;                         // frc_emif_0:s0_axi4lite_rresp -> mm_interconnect_0:frc_emif_0_s0_axi4lite_rresp
	wire    [2:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_awprot;                        // mm_interconnect_0:frc_emif_0_s0_axi4lite_awprot -> frc_emif_0:s0_axi4lite_awprot
	wire   [31:0] mm_interconnect_0_frc_emif_0_s0_axi4lite_wdata;                         // mm_interconnect_0:frc_emif_0_s0_axi4lite_wdata -> frc_emif_0:s0_axi4lite_wdata
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_arvalid;                       // mm_interconnect_0:frc_emif_0_s0_axi4lite_arvalid -> frc_emif_0:s0_axi4lite_arvalid
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_bvalid;                        // frc_emif_0:s0_axi4lite_bvalid -> mm_interconnect_0:frc_emif_0_s0_axi4lite_bvalid
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_awvalid;                       // mm_interconnect_0:frc_emif_0_s0_axi4lite_awvalid -> frc_emif_0:s0_axi4lite_awvalid
	wire          mm_interconnect_0_frc_emif_0_s0_axi4lite_rvalid;                        // frc_emif_0:s0_axi4lite_rvalid -> mm_interconnect_0:frc_emif_0_s0_axi4lite_rvalid
	wire          intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest;                       // mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest -> intel_vvp_vfb_0:av_mm_mem_write_host_waitrequest
	wire   [31:0] intel_vvp_vfb_0_av_mm_mem_write_host_address;                           // intel_vvp_vfb_0:av_mm_mem_write_host_address -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_address
	wire          intel_vvp_vfb_0_av_mm_mem_write_host_write;                             // intel_vvp_vfb_0:av_mm_mem_write_host_write -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_write
	wire  [255:0] intel_vvp_vfb_0_av_mm_mem_write_host_writedata;                         // intel_vvp_vfb_0:av_mm_mem_write_host_writedata -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_writedata
	wire    [3:0] intel_vvp_vfb_0_av_mm_mem_write_host_burstcount;                        // intel_vvp_vfb_0:av_mm_mem_write_host_burstcount -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_write_host_burstcount
	wire          intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest;                        // mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest -> intel_vvp_vfb_0:av_mm_mem_read_host_waitrequest
	wire  [255:0] intel_vvp_vfb_0_av_mm_mem_read_host_readdata;                           // mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_read_host_readdata -> intel_vvp_vfb_0:av_mm_mem_read_host_readdata
	wire   [31:0] intel_vvp_vfb_0_av_mm_mem_read_host_address;                            // intel_vvp_vfb_0:av_mm_mem_read_host_address -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_read_host_address
	wire          intel_vvp_vfb_0_av_mm_mem_read_host_read;                               // intel_vvp_vfb_0:av_mm_mem_read_host_read -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_read_host_read
	wire          intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid;                      // mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid -> intel_vvp_vfb_0:av_mm_mem_read_host_readdatavalid
	wire    [3:0] intel_vvp_vfb_0_av_mm_mem_read_host_burstcount;                         // intel_vvp_vfb_0:av_mm_mem_read_host_burstcount -> mm_interconnect_1:intel_vvp_vfb_0_av_mm_mem_read_host_burstcount
	wire    [1:0] mm_interconnect_1_frc_emif_0_s0_axi4_awburst;                           // mm_interconnect_1:frc_emif_0_s0_axi4_awburst -> frc_emif_0:s0_axi4_awburst
	wire   [13:0] mm_interconnect_1_frc_emif_0_s0_axi4_awuser;                            // mm_interconnect_1:frc_emif_0_s0_axi4_awuser -> frc_emif_0:s0_axi4_awuser
	wire    [7:0] mm_interconnect_1_frc_emif_0_s0_axi4_arlen;                             // mm_interconnect_1:frc_emif_0_s0_axi4_arlen -> frc_emif_0:s0_axi4_arlen
	wire    [3:0] mm_interconnect_1_frc_emif_0_s0_axi4_arqos;                             // mm_interconnect_1:frc_emif_0_s0_axi4_arqos -> frc_emif_0:s0_axi4_arqos
	wire   [31:0] mm_interconnect_1_frc_emif_0_s0_axi4_wstrb;                             // mm_interconnect_1:frc_emif_0_s0_axi4_wstrb -> frc_emif_0:s0_axi4_wstrb
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_wready;                            // frc_emif_0:s0_axi4_wready -> mm_interconnect_1:frc_emif_0_s0_axi4_wready
	wire    [6:0] mm_interconnect_1_frc_emif_0_s0_axi4_rid;                               // frc_emif_0:s0_axi4_rid -> mm_interconnect_1:frc_emif_0_s0_axi4_rid
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_rready;                            // mm_interconnect_1:frc_emif_0_s0_axi4_rready -> frc_emif_0:s0_axi4_rready
	wire    [7:0] mm_interconnect_1_frc_emif_0_s0_axi4_awlen;                             // mm_interconnect_1:frc_emif_0_s0_axi4_awlen -> frc_emif_0:s0_axi4_awlen
	wire    [3:0] mm_interconnect_1_frc_emif_0_s0_axi4_awqos;                             // mm_interconnect_1:frc_emif_0_s0_axi4_awqos -> frc_emif_0:s0_axi4_awqos
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_wvalid;                            // mm_interconnect_1:frc_emif_0_s0_axi4_wvalid -> frc_emif_0:s0_axi4_wvalid
	wire   [30:0] mm_interconnect_1_frc_emif_0_s0_axi4_araddr;                            // mm_interconnect_1:frc_emif_0_s0_axi4_araddr -> frc_emif_0:s0_axi4_araddr
	wire    [2:0] mm_interconnect_1_frc_emif_0_s0_axi4_arprot;                            // mm_interconnect_1:frc_emif_0_s0_axi4_arprot -> frc_emif_0:s0_axi4_arprot
	wire    [2:0] mm_interconnect_1_frc_emif_0_s0_axi4_awprot;                            // mm_interconnect_1:frc_emif_0_s0_axi4_awprot -> frc_emif_0:s0_axi4_awprot
	wire  [255:0] mm_interconnect_1_frc_emif_0_s0_axi4_wdata;                             // mm_interconnect_1:frc_emif_0_s0_axi4_wdata -> frc_emif_0:s0_axi4_wdata
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_arvalid;                           // mm_interconnect_1:frc_emif_0_s0_axi4_arvalid -> frc_emif_0:s0_axi4_arvalid
	wire    [6:0] mm_interconnect_1_frc_emif_0_s0_axi4_arid;                              // mm_interconnect_1:frc_emif_0_s0_axi4_arid -> frc_emif_0:s0_axi4_arid
	wire    [0:0] mm_interconnect_1_frc_emif_0_s0_axi4_arlock;                            // mm_interconnect_1:frc_emif_0_s0_axi4_arlock -> frc_emif_0:s0_axi4_arlock
	wire    [0:0] mm_interconnect_1_frc_emif_0_s0_axi4_awlock;                            // mm_interconnect_1:frc_emif_0_s0_axi4_awlock -> frc_emif_0:s0_axi4_awlock
	wire   [30:0] mm_interconnect_1_frc_emif_0_s0_axi4_awaddr;                            // mm_interconnect_1:frc_emif_0_s0_axi4_awaddr -> frc_emif_0:s0_axi4_awaddr
	wire    [1:0] mm_interconnect_1_frc_emif_0_s0_axi4_bresp;                             // frc_emif_0:s0_axi4_bresp -> mm_interconnect_1:frc_emif_0_s0_axi4_bresp
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_arready;                           // frc_emif_0:s0_axi4_arready -> mm_interconnect_1:frc_emif_0_s0_axi4_arready
	wire  [255:0] mm_interconnect_1_frc_emif_0_s0_axi4_rdata;                             // frc_emif_0:s0_axi4_rdata -> mm_interconnect_1:frc_emif_0_s0_axi4_rdata
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_awready;                           // frc_emif_0:s0_axi4_awready -> mm_interconnect_1:frc_emif_0_s0_axi4_awready
	wire    [1:0] mm_interconnect_1_frc_emif_0_s0_axi4_arburst;                           // mm_interconnect_1:frc_emif_0_s0_axi4_arburst -> frc_emif_0:s0_axi4_arburst
	wire    [2:0] mm_interconnect_1_frc_emif_0_s0_axi4_arsize;                            // mm_interconnect_1:frc_emif_0_s0_axi4_arsize -> frc_emif_0:s0_axi4_arsize
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_bready;                            // mm_interconnect_1:frc_emif_0_s0_axi4_bready -> frc_emif_0:s0_axi4_bready
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_rlast;                             // frc_emif_0:s0_axi4_rlast -> mm_interconnect_1:frc_emif_0_s0_axi4_rlast
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_wlast;                             // mm_interconnect_1:frc_emif_0_s0_axi4_wlast -> frc_emif_0:s0_axi4_wlast
	wire    [1:0] mm_interconnect_1_frc_emif_0_s0_axi4_rresp;                             // frc_emif_0:s0_axi4_rresp -> mm_interconnect_1:frc_emif_0_s0_axi4_rresp
	wire    [6:0] mm_interconnect_1_frc_emif_0_s0_axi4_awid;                              // mm_interconnect_1:frc_emif_0_s0_axi4_awid -> frc_emif_0:s0_axi4_awid
	wire    [6:0] mm_interconnect_1_frc_emif_0_s0_axi4_bid;                               // frc_emif_0:s0_axi4_bid -> mm_interconnect_1:frc_emif_0_s0_axi4_bid
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_bvalid;                            // frc_emif_0:s0_axi4_bvalid -> mm_interconnect_1:frc_emif_0_s0_axi4_bvalid
	wire    [2:0] mm_interconnect_1_frc_emif_0_s0_axi4_awsize;                            // mm_interconnect_1:frc_emif_0_s0_axi4_awsize -> frc_emif_0:s0_axi4_awsize
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_awvalid;                           // mm_interconnect_1:frc_emif_0_s0_axi4_awvalid -> frc_emif_0:s0_axi4_awvalid
	wire   [13:0] mm_interconnect_1_frc_emif_0_s0_axi4_aruser;                            // mm_interconnect_1:frc_emif_0_s0_axi4_aruser -> frc_emif_0:s0_axi4_aruser
	wire          mm_interconnect_1_frc_emif_0_s0_axi4_rvalid;                            // frc_emif_0:s0_axi4_rvalid -> mm_interconnect_1:frc_emif_0_s0_axi4_rvalid
	wire          rst_controller_reset_out_reset;                                         // rst_controller:reset_out -> [intel_vvp_scaler_0:main_reset_reset, intel_vvp_vfb_0:main_reset_reset, intel_vvp_vfb_0:mem_reset_reset, ltf_conv_0:main_reset_reset]
	wire          rst_controller_001_reset_out_reset;                                     // rst_controller_001:reset_out -> mm_interconnect_1:frc_emif_0_s0_axi4_translator_clk_reset_reset_bridge_in_reset_reset
	wire          frc_emif_0_s0_axi4_ctrl_ready_reset;                                    // frc_emif_0:s0_axi4_reset_n -> rst_controller_001:reset_in0

	pipeline_intel_vvp_pipeline2_0_altera_avalon_mm_bridge_2010_tex5a4i #(
		.DATA_WIDTH               (32),
		.SYMBOL_WIDTH             (8),
		.HDL_ADDR_WIDTH           (28),
		.BURSTCOUNT_WIDTH         (1),
		.PIPELINE_COMMAND         (1),
		.PIPELINE_RESPONSE        (1),
		.SYNC_RESET               (0),
		.USE_WRITERESPONSE        (0),
		.S0_WAITREQUEST_ALLOWANCE (0),
		.M0_WAITREQUEST_ALLOWANCE (0)
	) mm_bridge_0 (
		.clk                   (clk_clk),                      //   input,   width = 1,   clk.clk
		.reset                 (reset_reset),                  //   input,   width = 1, reset.reset
		.s0_waitrequest        (s0_waitrequest),               //  output,   width = 1,    s0.waitrequest
		.s0_readdata           (s0_readdata),                  //  output,  width = 32,      .readdata
		.s0_readdatavalid      (s0_readdatavalid),             //  output,   width = 1,      .readdatavalid
		.s0_burstcount         (s0_burstcount),                //   input,   width = 1,      .burstcount
		.s0_writedata          (s0_writedata),                 //   input,  width = 32,      .writedata
		.s0_address            (s0_address),                   //   input,  width = 28,      .address
		.s0_write              (s0_write),                     //   input,   width = 1,      .write
		.s0_read               (s0_read),                      //   input,   width = 1,      .read
		.s0_byteenable         (s0_byteenable),                //   input,   width = 4,      .byteenable
		.s0_debugaccess        (s0_debugaccess),               //   input,   width = 1,      .debugaccess
		.m0_waitrequest        (mm_bridge_0_m0_waitrequest),   //   input,   width = 1,    m0.waitrequest
		.m0_readdata           (mm_bridge_0_m0_readdata),      //   input,  width = 32,      .readdata
		.m0_readdatavalid      (mm_bridge_0_m0_readdatavalid), //   input,   width = 1,      .readdatavalid
		.m0_burstcount         (mm_bridge_0_m0_burstcount),    //  output,   width = 1,      .burstcount
		.m0_writedata          (mm_bridge_0_m0_writedata),     //  output,  width = 32,      .writedata
		.m0_address            (mm_bridge_0_m0_address),       //  output,  width = 28,      .address
		.m0_write              (mm_bridge_0_m0_write),         //  output,   width = 1,      .write
		.m0_read               (mm_bridge_0_m0_read),          //  output,   width = 1,      .read
		.m0_byteenable         (mm_bridge_0_m0_byteenable),    //  output,   width = 4,      .byteenable
		.m0_debugaccess        (mm_bridge_0_m0_debugaccess),   //  output,   width = 1,      .debugaccess
		.s0_response           (),                             // (terminated),                    
		.s0_writeresponsevalid (),                             // (terminated),                    
		.m0_response           (2'b00),                        // (terminated),                    
		.m0_writeresponsevalid (1'b0)                          // (terminated),                    
	);

	pipeline_intel_vvp_pipeline2_0_intel_vvp_scaler_2451_tf4nbta intel_vvp_scaler_0 (
		.main_clock_clk                    (clk_clk),                                                                //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                         //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (s_axis_video_in_tdata),                                                  //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (s_axis_video_in_tvalid),                                                 //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (s_axis_video_in_tready),                                                 //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (s_axis_video_in_tlast),                                                  //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (s_axis_video_in_tuser),                                                  //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (intel_vvp_scaler_0_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (intel_vvp_scaler_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (intel_vvp_scaler_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (intel_vvp_scaler_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (intel_vvp_scaler_0_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_pipeline2_0_intel_vvp_protocol_conv_2460_pwotnfq ltf_conv_0 (
		.main_clock_clk                    (clk_clk),                                                        //   input,   width = 1,          main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                 //   input,   width = 1,          main_reset.reset
		.axi4s_vid_in_tdata                (intel_vvp_scaler_0_axi4s_vid_out_tdata),                         //   input,  width = 24,        axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (intel_vvp_scaler_0_axi4s_vid_out_tvalid),                        //   input,   width = 1,                    .tvalid
		.axi4s_vid_in_tready               (intel_vvp_scaler_0_axi4s_vid_out_tready),                        //  output,   width = 1,                    .tready
		.axi4s_vid_in_tlast                (intel_vvp_scaler_0_axi4s_vid_out_tlast),                         //   input,   width = 1,                    .tlast
		.axi4s_vid_in_tuser                (intel_vvp_scaler_0_axi4s_vid_out_tuser),                         //   input,   width = 3,                    .tuser
		.axi4s_vid_out_tdata               (ltf_conv_0_axi4s_vid_out_tdata),                                 //  output,  width = 24,       axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (ltf_conv_0_axi4s_vid_out_tvalid),                                //  output,   width = 1,                    .tvalid
		.axi4s_vid_out_tready              (ltf_conv_0_axi4s_vid_out_tready),                                //   input,   width = 1,                    .tready
		.axi4s_vid_out_tlast               (ltf_conv_0_axi4s_vid_out_tlast),                                 //  output,   width = 1,                    .tlast
		.axi4s_vid_out_tuser               (ltf_conv_0_axi4s_vid_out_tuser),                                 //  output,   width = 3,                    .tuser
		.av_mm_control_agent_address       (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_address),       //   input,   width = 7, av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_write),         //   input,   width = 1,                    .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_byteenable),    //   input,   width = 4,                    .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_writedata),     //   input,  width = 32,                    .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_read),          //   input,   width = 1,                    .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_readdata),      //  output,  width = 32,                    .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_readdatavalid), //  output,   width = 1,                    .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_waitrequest)    //  output,   width = 1,                    .waitrequest
	);

	pipeline_intel_vvp_pipeline2_0_intel_vvp_vfb_2451_pdxh2ti #(
		.MAX_HEIGHT             (96),
		.MAX_WIDTH              (128),
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.CLOCKS_ARE_SEPARATE    (1),
		.P_AV_MM_DATA_WIDTH     (256),
		.P_AV_MM_ADDR_WIDTH     (32),
		.WRITE_BURST_TARGET     (8),
		.READ_BURST_TARGET      (8)
	) intel_vvp_vfb_0 (
		.main_clock_clk                    (clk_clk),                                                             //   input,    width = 1,           main_clock.clk
		.main_reset_reset                  (rst_controller_reset_out_reset),                                      //   input,    width = 1,           main_reset.reset
		.mem_clock_clk                     (clk_clk),                                                             //   input,    width = 1,            mem_clock.clk
		.mem_reset_reset                   (rst_controller_reset_out_reset),                                      //   input,    width = 1,            mem_reset.reset
		.axi4s_vid_in_tdata                (ltf_conv_0_axi4s_vid_out_tdata),                                      //   input,   width = 24,         axi4s_vid_in.tdata
		.axi4s_vid_in_tvalid               (ltf_conv_0_axi4s_vid_out_tvalid),                                     //   input,    width = 1,                     .tvalid
		.axi4s_vid_in_tready               (ltf_conv_0_axi4s_vid_out_tready),                                     //  output,    width = 1,                     .tready
		.axi4s_vid_in_tlast                (ltf_conv_0_axi4s_vid_out_tlast),                                      //   input,    width = 1,                     .tlast
		.axi4s_vid_in_tuser                (ltf_conv_0_axi4s_vid_out_tuser),                                      //   input,    width = 3,                     .tuser
		.axi4s_vid_out_tdata               (m_axis_video_out_tdata),                                              //  output,   width = 24,        axi4s_vid_out.tdata
		.axi4s_vid_out_tvalid              (m_axis_video_out_tvalid),                                             //  output,    width = 1,                     .tvalid
		.axi4s_vid_out_tready              (m_axis_video_out_tready),                                             //   input,    width = 1,                     .tready
		.axi4s_vid_out_tlast               (m_axis_video_out_tlast),                                              //  output,    width = 1,                     .tlast
		.axi4s_vid_out_tuser               (m_axis_video_out_tuser),                                              //  output,    width = 3,                     .tuser
		.av_mm_mem_write_host_address      (intel_vvp_vfb_0_av_mm_mem_write_host_address),                        //  output,   width = 32, av_mm_mem_write_host.address
		.av_mm_mem_write_host_waitrequest  (intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest),                    //   input,    width = 1,                     .waitrequest
		.av_mm_mem_write_host_burstcount   (intel_vvp_vfb_0_av_mm_mem_write_host_burstcount),                     //  output,    width = 4,                     .burstcount
		.av_mm_mem_write_host_write        (intel_vvp_vfb_0_av_mm_mem_write_host_write),                          //  output,    width = 1,                     .write
		.av_mm_mem_write_host_writedata    (intel_vvp_vfb_0_av_mm_mem_write_host_writedata),                      //  output,  width = 256,                     .writedata
		.av_mm_mem_read_host_address       (intel_vvp_vfb_0_av_mm_mem_read_host_address),                         //  output,   width = 32,  av_mm_mem_read_host.address
		.av_mm_mem_read_host_waitrequest   (intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest),                     //   input,    width = 1,                     .waitrequest
		.av_mm_mem_read_host_burstcount    (intel_vvp_vfb_0_av_mm_mem_read_host_burstcount),                      //  output,    width = 4,                     .burstcount
		.av_mm_mem_read_host_read          (intel_vvp_vfb_0_av_mm_mem_read_host_read),                            //  output,    width = 1,                     .read
		.av_mm_mem_read_host_readdata      (intel_vvp_vfb_0_av_mm_mem_read_host_readdata),                        //   input,  width = 256,                     .readdata
		.av_mm_mem_read_host_readdatavalid (intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid),                   //   input,    width = 1,                     .readdatavalid
		.av_mm_control_agent_address       (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_address),       //   input,    width = 7,  av_mm_control_agent.address
		.av_mm_control_agent_write         (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_write),         //   input,    width = 1,                     .write
		.av_mm_control_agent_byteenable    (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_byteenable),    //   input,    width = 4,                     .byteenable
		.av_mm_control_agent_writedata     (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_writedata),     //   input,   width = 32,                     .writedata
		.av_mm_control_agent_read          (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_read),          //   input,    width = 1,                     .read
		.av_mm_control_agent_readdata      (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_readdata),      //  output,   width = 32,                     .readdata
		.av_mm_control_agent_readdatavalid (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_readdatavalid), //  output,    width = 1,                     .readdatavalid
		.av_mm_control_agent_waitrequest   (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_waitrequest)    //  output,    width = 1,                     .waitrequest
	);

	pipeline_intel_vvp_pipeline2_0_emif_io96b_ddr4comp_400_pftbeyi frc_emif_0 (
		.s0_axi4_clock_in    (clk_clk),                                          //   input,    width = 1,    s0_axi4_clock_in.clk
		.s0_axi4_reset_n     (frc_emif_0_s0_axi4_ctrl_ready_reset),              //  output,    width = 1,  s0_axi4_ctrl_ready.reset_n
		.core_init_n         (~reset_reset),                                     //   input,    width = 1,         core_init_n.reset_n
		.s0_axi4_awaddr      (mm_interconnect_1_frc_emif_0_s0_axi4_awaddr),      //   input,   width = 31,             s0_axi4.awaddr
		.s0_axi4_awburst     (mm_interconnect_1_frc_emif_0_s0_axi4_awburst),     //   input,    width = 2,                    .awburst
		.s0_axi4_awid        (mm_interconnect_1_frc_emif_0_s0_axi4_awid),        //   input,    width = 7,                    .awid
		.s0_axi4_awlen       (mm_interconnect_1_frc_emif_0_s0_axi4_awlen),       //   input,    width = 8,                    .awlen
		.s0_axi4_awlock      (mm_interconnect_1_frc_emif_0_s0_axi4_awlock),      //   input,    width = 1,                    .awlock
		.s0_axi4_awqos       (mm_interconnect_1_frc_emif_0_s0_axi4_awqos),       //   input,    width = 4,                    .awqos
		.s0_axi4_awsize      (mm_interconnect_1_frc_emif_0_s0_axi4_awsize),      //   input,    width = 3,                    .awsize
		.s0_axi4_awvalid     (mm_interconnect_1_frc_emif_0_s0_axi4_awvalid),     //   input,    width = 1,                    .awvalid
		.s0_axi4_awuser      (mm_interconnect_1_frc_emif_0_s0_axi4_awuser),      //   input,   width = 14,                    .awuser
		.s0_axi4_awprot      (mm_interconnect_1_frc_emif_0_s0_axi4_awprot),      //   input,    width = 3,                    .awprot
		.s0_axi4_awready     (mm_interconnect_1_frc_emif_0_s0_axi4_awready),     //  output,    width = 1,                    .awready
		.s0_axi4_araddr      (mm_interconnect_1_frc_emif_0_s0_axi4_araddr),      //   input,   width = 31,                    .araddr
		.s0_axi4_arburst     (mm_interconnect_1_frc_emif_0_s0_axi4_arburst),     //   input,    width = 2,                    .arburst
		.s0_axi4_arid        (mm_interconnect_1_frc_emif_0_s0_axi4_arid),        //   input,    width = 7,                    .arid
		.s0_axi4_arlen       (mm_interconnect_1_frc_emif_0_s0_axi4_arlen),       //   input,    width = 8,                    .arlen
		.s0_axi4_arlock      (mm_interconnect_1_frc_emif_0_s0_axi4_arlock),      //   input,    width = 1,                    .arlock
		.s0_axi4_arqos       (mm_interconnect_1_frc_emif_0_s0_axi4_arqos),       //   input,    width = 4,                    .arqos
		.s0_axi4_arsize      (mm_interconnect_1_frc_emif_0_s0_axi4_arsize),      //   input,    width = 3,                    .arsize
		.s0_axi4_arvalid     (mm_interconnect_1_frc_emif_0_s0_axi4_arvalid),     //   input,    width = 1,                    .arvalid
		.s0_axi4_aruser      (mm_interconnect_1_frc_emif_0_s0_axi4_aruser),      //   input,   width = 14,                    .aruser
		.s0_axi4_arprot      (mm_interconnect_1_frc_emif_0_s0_axi4_arprot),      //   input,    width = 3,                    .arprot
		.s0_axi4_arready     (mm_interconnect_1_frc_emif_0_s0_axi4_arready),     //  output,    width = 1,                    .arready
		.s0_axi4_wdata       (mm_interconnect_1_frc_emif_0_s0_axi4_wdata),       //   input,  width = 256,                    .wdata
		.s0_axi4_wstrb       (mm_interconnect_1_frc_emif_0_s0_axi4_wstrb),       //   input,   width = 32,                    .wstrb
		.s0_axi4_wlast       (mm_interconnect_1_frc_emif_0_s0_axi4_wlast),       //   input,    width = 1,                    .wlast
		.s0_axi4_wvalid      (mm_interconnect_1_frc_emif_0_s0_axi4_wvalid),      //   input,    width = 1,                    .wvalid
		.s0_axi4_wready      (mm_interconnect_1_frc_emif_0_s0_axi4_wready),      //  output,    width = 1,                    .wready
		.s0_axi4_bready      (mm_interconnect_1_frc_emif_0_s0_axi4_bready),      //   input,    width = 1,                    .bready
		.s0_axi4_bid         (mm_interconnect_1_frc_emif_0_s0_axi4_bid),         //  output,    width = 7,                    .bid
		.s0_axi4_bresp       (mm_interconnect_1_frc_emif_0_s0_axi4_bresp),       //  output,    width = 2,                    .bresp
		.s0_axi4_bvalid      (mm_interconnect_1_frc_emif_0_s0_axi4_bvalid),      //  output,    width = 1,                    .bvalid
		.s0_axi4_rready      (mm_interconnect_1_frc_emif_0_s0_axi4_rready),      //   input,    width = 1,                    .rready
		.s0_axi4_rdata       (mm_interconnect_1_frc_emif_0_s0_axi4_rdata),       //  output,  width = 256,                    .rdata
		.s0_axi4_rid         (mm_interconnect_1_frc_emif_0_s0_axi4_rid),         //  output,    width = 7,                    .rid
		.s0_axi4_rlast       (mm_interconnect_1_frc_emif_0_s0_axi4_rlast),       //  output,    width = 1,                    .rlast
		.s0_axi4_rresp       (mm_interconnect_1_frc_emif_0_s0_axi4_rresp),       //  output,    width = 2,                    .rresp
		.s0_axi4_rvalid      (mm_interconnect_1_frc_emif_0_s0_axi4_rvalid),      //  output,    width = 1,                    .rvalid
		.s0_axi4lite_clock   (clk_clk),                                          //   input,    width = 1,   s0_axi4lite_clock.clk
		.s0_axi4lite_reset_n (~reset_reset),                                     //   input,    width = 1, s0_axi4lite_reset_n.reset_n
		.s0_axi4lite_awaddr  (mm_interconnect_0_frc_emif_0_s0_axi4lite_awaddr),  //   input,   width = 27,         s0_axi4lite.awaddr
		.s0_axi4lite_awprot  (mm_interconnect_0_frc_emif_0_s0_axi4lite_awprot),  //   input,    width = 3,                    .awprot
		.s0_axi4lite_awvalid (mm_interconnect_0_frc_emif_0_s0_axi4lite_awvalid), //   input,    width = 1,                    .awvalid
		.s0_axi4lite_awready (mm_interconnect_0_frc_emif_0_s0_axi4lite_awready), //  output,    width = 1,                    .awready
		.s0_axi4lite_araddr  (mm_interconnect_0_frc_emif_0_s0_axi4lite_araddr),  //   input,   width = 27,                    .araddr
		.s0_axi4lite_arprot  (mm_interconnect_0_frc_emif_0_s0_axi4lite_arprot),  //   input,    width = 3,                    .arprot
		.s0_axi4lite_arvalid (mm_interconnect_0_frc_emif_0_s0_axi4lite_arvalid), //   input,    width = 1,                    .arvalid
		.s0_axi4lite_arready (mm_interconnect_0_frc_emif_0_s0_axi4lite_arready), //  output,    width = 1,                    .arready
		.s0_axi4lite_wdata   (mm_interconnect_0_frc_emif_0_s0_axi4lite_wdata),   //   input,   width = 32,                    .wdata
		.s0_axi4lite_wstrb   (mm_interconnect_0_frc_emif_0_s0_axi4lite_wstrb),   //   input,    width = 4,                    .wstrb
		.s0_axi4lite_wvalid  (mm_interconnect_0_frc_emif_0_s0_axi4lite_wvalid),  //   input,    width = 1,                    .wvalid
		.s0_axi4lite_wready  (mm_interconnect_0_frc_emif_0_s0_axi4lite_wready),  //  output,    width = 1,                    .wready
		.s0_axi4lite_bready  (mm_interconnect_0_frc_emif_0_s0_axi4lite_bready),  //   input,    width = 1,                    .bready
		.s0_axi4lite_bresp   (mm_interconnect_0_frc_emif_0_s0_axi4lite_bresp),   //  output,    width = 2,                    .bresp
		.s0_axi4lite_bvalid  (mm_interconnect_0_frc_emif_0_s0_axi4lite_bvalid),  //  output,    width = 1,                    .bvalid
		.s0_axi4lite_rready  (mm_interconnect_0_frc_emif_0_s0_axi4lite_rready),  //   input,    width = 1,                    .rready
		.s0_axi4lite_rdata   (mm_interconnect_0_frc_emif_0_s0_axi4lite_rdata),   //  output,   width = 32,                    .rdata
		.s0_axi4lite_rresp   (mm_interconnect_0_frc_emif_0_s0_axi4lite_rresp),   //  output,    width = 2,                    .rresp
		.s0_axi4lite_rvalid  (mm_interconnect_0_frc_emif_0_s0_axi4lite_rvalid),  //  output,    width = 1,                    .rvalid
		.mem_0_cke           (frc_emif_mem_mem_cke),                             //  output,    width = 1,               mem_0.mem_cke
		.mem_0_odt           (frc_emif_mem_mem_odt),                             //  output,    width = 1,                    .mem_odt
		.mem_0_cs_n          (frc_emif_mem_mem_cs_n),                            //  output,    width = 1,                    .mem_cs_n
		.mem_0_a             (frc_emif_mem_mem_a),                               //  output,   width = 17,                    .mem_a
		.mem_0_ba            (frc_emif_mem_mem_ba),                              //  output,    width = 2,                    .mem_ba
		.mem_0_bg            (frc_emif_mem_mem_bg),                              //  output,    width = 1,                    .mem_bg
		.mem_0_act_n         (frc_emif_mem_mem_act_n),                           //  output,    width = 1,                    .mem_act_n
		.mem_0_par           (frc_emif_mem_mem_par),                             //  output,    width = 1,                    .mem_par
		.mem_0_dq            (frc_emif_mem_mem_dq),                              //   inout,   width = 32,                    .mem_dq
		.mem_0_dqs_t         (frc_emif_mem_mem_dqs_t),                           //   inout,    width = 4,                    .mem_dqs_t
		.mem_0_dqs_c         (frc_emif_mem_mem_dqs_c),                           //   inout,    width = 4,                    .mem_dqs_c
		.mem_0_alert_n       (frc_emif_mem_mem_alert_n),                         //   input,    width = 1,                    .mem_alert_n
		.mem_0_ck_t          (frc_emif_mem_ck_mem_ck_t),                         //  output,    width = 1,            mem_ck_0.mem_ck_t
		.mem_0_ck_c          (frc_emif_mem_ck_mem_ck_c),                         //  output,    width = 1,                    .mem_ck_c
		.mem_0_reset_n       (frc_emif_mem_reset_n_mem_reset_n),                 //  output,    width = 1,         mem_reset_n.mem_reset_n
		.oct_rzqin_0         (frc_emif_oct_oct_rzqin),                           //   input,    width = 1,               oct_0.oct_rzqin
		.ref_clk             (frc_emif_ref_clk_clk)                              //   input,    width = 1,             ref_clk.clk
	);

	pipeline_intel_vvp_pipeline2_0_altera_mm_interconnect_1920_wxu54kq mm_interconnect_0 (
		.mm_bridge_0_m0_address                               (mm_bridge_0_m0_address),                                                 //   input,  width = 28,                          mm_bridge_0_m0.address
		.mm_bridge_0_m0_waitrequest                           (mm_bridge_0_m0_waitrequest),                                             //  output,   width = 1,                                        .waitrequest
		.mm_bridge_0_m0_burstcount                            (mm_bridge_0_m0_burstcount),                                              //   input,   width = 1,                                        .burstcount
		.mm_bridge_0_m0_byteenable                            (mm_bridge_0_m0_byteenable),                                              //   input,   width = 4,                                        .byteenable
		.mm_bridge_0_m0_read                                  (mm_bridge_0_m0_read),                                                    //   input,   width = 1,                                        .read
		.mm_bridge_0_m0_readdata                              (mm_bridge_0_m0_readdata),                                                //  output,  width = 32,                                        .readdata
		.mm_bridge_0_m0_readdatavalid                         (mm_bridge_0_m0_readdatavalid),                                           //  output,   width = 1,                                        .readdatavalid
		.mm_bridge_0_m0_write                                 (mm_bridge_0_m0_write),                                                   //   input,   width = 1,                                        .write
		.mm_bridge_0_m0_writedata                             (mm_bridge_0_m0_writedata),                                               //   input,  width = 32,                                        .writedata
		.mm_bridge_0_m0_debugaccess                           (mm_bridge_0_m0_debugaccess),                                             //   input,   width = 1,                                        .debugaccess
		.intel_vvp_scaler_0_av_mm_control_agent_address       (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_address),       //  output,   width = 7,  intel_vvp_scaler_0_av_mm_control_agent.address
		.intel_vvp_scaler_0_av_mm_control_agent_write         (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_write),         //  output,   width = 1,                                        .write
		.intel_vvp_scaler_0_av_mm_control_agent_read          (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_read),          //  output,   width = 1,                                        .read
		.intel_vvp_scaler_0_av_mm_control_agent_readdata      (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_readdata),      //   input,  width = 32,                                        .readdata
		.intel_vvp_scaler_0_av_mm_control_agent_writedata     (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_writedata),     //  output,  width = 32,                                        .writedata
		.intel_vvp_scaler_0_av_mm_control_agent_byteenable    (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_byteenable),    //  output,   width = 4,                                        .byteenable
		.intel_vvp_scaler_0_av_mm_control_agent_readdatavalid (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_readdatavalid), //   input,   width = 1,                                        .readdatavalid
		.intel_vvp_scaler_0_av_mm_control_agent_waitrequest   (mm_interconnect_0_intel_vvp_scaler_0_av_mm_control_agent_waitrequest),   //   input,   width = 1,                                        .waitrequest
		.ltf_conv_0_av_mm_control_agent_address               (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_address),               //  output,   width = 7,          ltf_conv_0_av_mm_control_agent.address
		.ltf_conv_0_av_mm_control_agent_write                 (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_write),                 //  output,   width = 1,                                        .write
		.ltf_conv_0_av_mm_control_agent_read                  (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_read),                  //  output,   width = 1,                                        .read
		.ltf_conv_0_av_mm_control_agent_readdata              (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_readdata),              //   input,  width = 32,                                        .readdata
		.ltf_conv_0_av_mm_control_agent_writedata             (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_writedata),             //  output,  width = 32,                                        .writedata
		.ltf_conv_0_av_mm_control_agent_byteenable            (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_byteenable),            //  output,   width = 4,                                        .byteenable
		.ltf_conv_0_av_mm_control_agent_readdatavalid         (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_readdatavalid),         //   input,   width = 1,                                        .readdatavalid
		.ltf_conv_0_av_mm_control_agent_waitrequest           (mm_interconnect_0_ltf_conv_0_av_mm_control_agent_waitrequest),           //   input,   width = 1,                                        .waitrequest
		.intel_vvp_vfb_0_av_mm_control_agent_address          (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_address),          //  output,   width = 7,     intel_vvp_vfb_0_av_mm_control_agent.address
		.intel_vvp_vfb_0_av_mm_control_agent_write            (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_write),            //  output,   width = 1,                                        .write
		.intel_vvp_vfb_0_av_mm_control_agent_read             (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_read),             //  output,   width = 1,                                        .read
		.intel_vvp_vfb_0_av_mm_control_agent_readdata         (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_readdata),         //   input,  width = 32,                                        .readdata
		.intel_vvp_vfb_0_av_mm_control_agent_writedata        (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_writedata),        //  output,  width = 32,                                        .writedata
		.intel_vvp_vfb_0_av_mm_control_agent_byteenable       (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_byteenable),       //  output,   width = 4,                                        .byteenable
		.intel_vvp_vfb_0_av_mm_control_agent_readdatavalid    (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_readdatavalid),    //   input,   width = 1,                                        .readdatavalid
		.intel_vvp_vfb_0_av_mm_control_agent_waitrequest      (mm_interconnect_0_intel_vvp_vfb_0_av_mm_control_agent_waitrequest),      //   input,   width = 1,                                        .waitrequest
		.frc_emif_0_s0_axi4lite_awaddr                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_awaddr),                        //  output,  width = 27,                  frc_emif_0_s0_axi4lite.awaddr
		.frc_emif_0_s0_axi4lite_awprot                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_awprot),                        //  output,   width = 3,                                        .awprot
		.frc_emif_0_s0_axi4lite_awvalid                       (mm_interconnect_0_frc_emif_0_s0_axi4lite_awvalid),                       //  output,   width = 1,                                        .awvalid
		.frc_emif_0_s0_axi4lite_awready                       (mm_interconnect_0_frc_emif_0_s0_axi4lite_awready),                       //   input,   width = 1,                                        .awready
		.frc_emif_0_s0_axi4lite_wdata                         (mm_interconnect_0_frc_emif_0_s0_axi4lite_wdata),                         //  output,  width = 32,                                        .wdata
		.frc_emif_0_s0_axi4lite_wstrb                         (mm_interconnect_0_frc_emif_0_s0_axi4lite_wstrb),                         //  output,   width = 4,                                        .wstrb
		.frc_emif_0_s0_axi4lite_wvalid                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_wvalid),                        //  output,   width = 1,                                        .wvalid
		.frc_emif_0_s0_axi4lite_wready                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_wready),                        //   input,   width = 1,                                        .wready
		.frc_emif_0_s0_axi4lite_bresp                         (mm_interconnect_0_frc_emif_0_s0_axi4lite_bresp),                         //   input,   width = 2,                                        .bresp
		.frc_emif_0_s0_axi4lite_bvalid                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_bvalid),                        //   input,   width = 1,                                        .bvalid
		.frc_emif_0_s0_axi4lite_bready                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_bready),                        //  output,   width = 1,                                        .bready
		.frc_emif_0_s0_axi4lite_araddr                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_araddr),                        //  output,  width = 27,                                        .araddr
		.frc_emif_0_s0_axi4lite_arprot                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_arprot),                        //  output,   width = 3,                                        .arprot
		.frc_emif_0_s0_axi4lite_arvalid                       (mm_interconnect_0_frc_emif_0_s0_axi4lite_arvalid),                       //  output,   width = 1,                                        .arvalid
		.frc_emif_0_s0_axi4lite_arready                       (mm_interconnect_0_frc_emif_0_s0_axi4lite_arready),                       //   input,   width = 1,                                        .arready
		.frc_emif_0_s0_axi4lite_rdata                         (mm_interconnect_0_frc_emif_0_s0_axi4lite_rdata),                         //   input,  width = 32,                                        .rdata
		.frc_emif_0_s0_axi4lite_rresp                         (mm_interconnect_0_frc_emif_0_s0_axi4lite_rresp),                         //   input,   width = 2,                                        .rresp
		.frc_emif_0_s0_axi4lite_rvalid                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_rvalid),                        //   input,   width = 1,                                        .rvalid
		.frc_emif_0_s0_axi4lite_rready                        (mm_interconnect_0_frc_emif_0_s0_axi4lite_rready),                        //  output,   width = 1,                                        .rready
		.mm_bridge_0_reset_reset_bridge_in_reset_reset        (reset_reset),                                                            //   input,   width = 1, mm_bridge_0_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                 (clk_clk)                                                                 //   input,   width = 1,                        clock_in_out_clk.clk
	);

	pipeline_intel_vvp_pipeline2_0_altera_mm_interconnect_1920_vhgsboq mm_interconnect_1 (
		.intel_vvp_vfb_0_av_mm_mem_write_host_address                                      (intel_vvp_vfb_0_av_mm_mem_write_host_address),      //   input,   width = 32,                                        intel_vvp_vfb_0_av_mm_mem_write_host.address
		.intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest                                  (intel_vvp_vfb_0_av_mm_mem_write_host_waitrequest),  //  output,    width = 1,                                                                            .waitrequest
		.intel_vvp_vfb_0_av_mm_mem_write_host_burstcount                                   (intel_vvp_vfb_0_av_mm_mem_write_host_burstcount),   //   input,    width = 4,                                                                            .burstcount
		.intel_vvp_vfb_0_av_mm_mem_write_host_write                                        (intel_vvp_vfb_0_av_mm_mem_write_host_write),        //   input,    width = 1,                                                                            .write
		.intel_vvp_vfb_0_av_mm_mem_write_host_writedata                                    (intel_vvp_vfb_0_av_mm_mem_write_host_writedata),    //   input,  width = 256,                                                                            .writedata
		.intel_vvp_vfb_0_av_mm_mem_read_host_address                                       (intel_vvp_vfb_0_av_mm_mem_read_host_address),       //   input,   width = 32,                                         intel_vvp_vfb_0_av_mm_mem_read_host.address
		.intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest                                   (intel_vvp_vfb_0_av_mm_mem_read_host_waitrequest),   //  output,    width = 1,                                                                            .waitrequest
		.intel_vvp_vfb_0_av_mm_mem_read_host_burstcount                                    (intel_vvp_vfb_0_av_mm_mem_read_host_burstcount),    //   input,    width = 4,                                                                            .burstcount
		.intel_vvp_vfb_0_av_mm_mem_read_host_read                                          (intel_vvp_vfb_0_av_mm_mem_read_host_read),          //   input,    width = 1,                                                                            .read
		.intel_vvp_vfb_0_av_mm_mem_read_host_readdata                                      (intel_vvp_vfb_0_av_mm_mem_read_host_readdata),      //  output,  width = 256,                                                                            .readdata
		.intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid                                 (intel_vvp_vfb_0_av_mm_mem_read_host_readdatavalid), //  output,    width = 1,                                                                            .readdatavalid
		.frc_emif_0_s0_axi4_awid                                                           (mm_interconnect_1_frc_emif_0_s0_axi4_awid),         //  output,    width = 7,                                                          frc_emif_0_s0_axi4.awid
		.frc_emif_0_s0_axi4_awaddr                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_awaddr),       //  output,   width = 31,                                                                            .awaddr
		.frc_emif_0_s0_axi4_awlen                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_awlen),        //  output,    width = 8,                                                                            .awlen
		.frc_emif_0_s0_axi4_awsize                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_awsize),       //  output,    width = 3,                                                                            .awsize
		.frc_emif_0_s0_axi4_awburst                                                        (mm_interconnect_1_frc_emif_0_s0_axi4_awburst),      //  output,    width = 2,                                                                            .awburst
		.frc_emif_0_s0_axi4_awlock                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_awlock),       //  output,    width = 1,                                                                            .awlock
		.frc_emif_0_s0_axi4_awprot                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_awprot),       //  output,    width = 3,                                                                            .awprot
		.frc_emif_0_s0_axi4_awuser                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_awuser),       //  output,   width = 14,                                                                            .awuser
		.frc_emif_0_s0_axi4_awqos                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_awqos),        //  output,    width = 4,                                                                            .awqos
		.frc_emif_0_s0_axi4_awvalid                                                        (mm_interconnect_1_frc_emif_0_s0_axi4_awvalid),      //  output,    width = 1,                                                                            .awvalid
		.frc_emif_0_s0_axi4_awready                                                        (mm_interconnect_1_frc_emif_0_s0_axi4_awready),      //   input,    width = 1,                                                                            .awready
		.frc_emif_0_s0_axi4_wdata                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_wdata),        //  output,  width = 256,                                                                            .wdata
		.frc_emif_0_s0_axi4_wstrb                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_wstrb),        //  output,   width = 32,                                                                            .wstrb
		.frc_emif_0_s0_axi4_wlast                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_wlast),        //  output,    width = 1,                                                                            .wlast
		.frc_emif_0_s0_axi4_wvalid                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_wvalid),       //  output,    width = 1,                                                                            .wvalid
		.frc_emif_0_s0_axi4_wready                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_wready),       //   input,    width = 1,                                                                            .wready
		.frc_emif_0_s0_axi4_bid                                                            (mm_interconnect_1_frc_emif_0_s0_axi4_bid),          //   input,    width = 7,                                                                            .bid
		.frc_emif_0_s0_axi4_bresp                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_bresp),        //   input,    width = 2,                                                                            .bresp
		.frc_emif_0_s0_axi4_bvalid                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_bvalid),       //   input,    width = 1,                                                                            .bvalid
		.frc_emif_0_s0_axi4_bready                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_bready),       //  output,    width = 1,                                                                            .bready
		.frc_emif_0_s0_axi4_arid                                                           (mm_interconnect_1_frc_emif_0_s0_axi4_arid),         //  output,    width = 7,                                                                            .arid
		.frc_emif_0_s0_axi4_araddr                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_araddr),       //  output,   width = 31,                                                                            .araddr
		.frc_emif_0_s0_axi4_arlen                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_arlen),        //  output,    width = 8,                                                                            .arlen
		.frc_emif_0_s0_axi4_arsize                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_arsize),       //  output,    width = 3,                                                                            .arsize
		.frc_emif_0_s0_axi4_arburst                                                        (mm_interconnect_1_frc_emif_0_s0_axi4_arburst),      //  output,    width = 2,                                                                            .arburst
		.frc_emif_0_s0_axi4_arlock                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_arlock),       //  output,    width = 1,                                                                            .arlock
		.frc_emif_0_s0_axi4_arprot                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_arprot),       //  output,    width = 3,                                                                            .arprot
		.frc_emif_0_s0_axi4_aruser                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_aruser),       //  output,   width = 14,                                                                            .aruser
		.frc_emif_0_s0_axi4_arqos                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_arqos),        //  output,    width = 4,                                                                            .arqos
		.frc_emif_0_s0_axi4_arvalid                                                        (mm_interconnect_1_frc_emif_0_s0_axi4_arvalid),      //  output,    width = 1,                                                                            .arvalid
		.frc_emif_0_s0_axi4_arready                                                        (mm_interconnect_1_frc_emif_0_s0_axi4_arready),      //   input,    width = 1,                                                                            .arready
		.frc_emif_0_s0_axi4_rid                                                            (mm_interconnect_1_frc_emif_0_s0_axi4_rid),          //   input,    width = 7,                                                                            .rid
		.frc_emif_0_s0_axi4_rdata                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_rdata),        //   input,  width = 256,                                                                            .rdata
		.frc_emif_0_s0_axi4_rresp                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_rresp),        //   input,    width = 2,                                                                            .rresp
		.frc_emif_0_s0_axi4_rlast                                                          (mm_interconnect_1_frc_emif_0_s0_axi4_rlast),        //   input,    width = 1,                                                                            .rlast
		.frc_emif_0_s0_axi4_rvalid                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_rvalid),       //   input,    width = 1,                                                                            .rvalid
		.frc_emif_0_s0_axi4_rready                                                         (mm_interconnect_1_frc_emif_0_s0_axi4_rready),       //  output,    width = 1,                                                                            .rready
		.intel_vvp_vfb_0_av_mm_mem_write_host_translator_reset_reset_bridge_in_reset_reset (reset_reset),                                       //   input,    width = 1, intel_vvp_vfb_0_av_mm_mem_write_host_translator_reset_reset_bridge_in_reset.reset
		.frc_emif_0_s0_axi4_translator_clk_reset_reset_bridge_in_reset_reset               (rst_controller_001_reset_out_reset),                //   input,    width = 1,               frc_emif_0_s0_axi4_translator_clk_reset_reset_bridge_in_reset.reset
		.clock_in_out_clk_clk                                                              (clk_clk)                                            //   input,    width = 1,                                                            clock_in_out_clk.clk
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("both"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset_reset),                    //   input,  width = 1, reset_in0.reset
		.clk            (clk_clk),                        //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_reset_out_reset), //  output,  width = 1, reset_out.reset
		.reset_req      (),                               // (terminated),                       
		.reset_req_in0  (1'b0),                           // (terminated),                       
		.reset_in1      (1'b0),                           // (terminated),                       
		.reset_req_in1  (1'b0),                           // (terminated),                       
		.reset_in2      (1'b0),                           // (terminated),                       
		.reset_req_in2  (1'b0),                           // (terminated),                       
		.reset_in3      (1'b0),                           // (terminated),                       
		.reset_req_in3  (1'b0),                           // (terminated),                       
		.reset_in4      (1'b0),                           // (terminated),                       
		.reset_req_in4  (1'b0),                           // (terminated),                       
		.reset_in5      (1'b0),                           // (terminated),                       
		.reset_req_in5  (1'b0),                           // (terminated),                       
		.reset_in6      (1'b0),                           // (terminated),                       
		.reset_req_in6  (1'b0),                           // (terminated),                       
		.reset_in7      (1'b0),                           // (terminated),                       
		.reset_req_in7  (1'b0),                           // (terminated),                       
		.reset_in8      (1'b0),                           // (terminated),                       
		.reset_req_in8  (1'b0),                           // (terminated),                       
		.reset_in9      (1'b0),                           // (terminated),                       
		.reset_req_in9  (1'b0),                           // (terminated),                       
		.reset_in10     (1'b0),                           // (terminated),                       
		.reset_req_in10 (1'b0),                           // (terminated),                       
		.reset_in11     (1'b0),                           // (terminated),                       
		.reset_req_in11 (1'b0),                           // (terminated),                       
		.reset_in12     (1'b0),                           // (terminated),                       
		.reset_req_in12 (1'b0),                           // (terminated),                       
		.reset_in13     (1'b0),                           // (terminated),                       
		.reset_req_in13 (1'b0),                           // (terminated),                       
		.reset_in14     (1'b0),                           // (terminated),                       
		.reset_req_in14 (1'b0),                           // (terminated),                       
		.reset_in15     (1'b0),                           // (terminated),                       
		.reset_req_in15 (1'b0)                            // (terminated),                       
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~frc_emif_0_s0_axi4_ctrl_ready_reset), //   input,  width = 1, reset_in0.reset
		.clk            (clk_clk),                              //   input,  width = 1,       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),   //  output,  width = 1, reset_out.reset
		.reset_req      (),                                     // (terminated),                       
		.reset_req_in0  (1'b0),                                 // (terminated),                       
		.reset_in1      (1'b0),                                 // (terminated),                       
		.reset_req_in1  (1'b0),                                 // (terminated),                       
		.reset_in2      (1'b0),                                 // (terminated),                       
		.reset_req_in2  (1'b0),                                 // (terminated),                       
		.reset_in3      (1'b0),                                 // (terminated),                       
		.reset_req_in3  (1'b0),                                 // (terminated),                       
		.reset_in4      (1'b0),                                 // (terminated),                       
		.reset_req_in4  (1'b0),                                 // (terminated),                       
		.reset_in5      (1'b0),                                 // (terminated),                       
		.reset_req_in5  (1'b0),                                 // (terminated),                       
		.reset_in6      (1'b0),                                 // (terminated),                       
		.reset_req_in6  (1'b0),                                 // (terminated),                       
		.reset_in7      (1'b0),                                 // (terminated),                       
		.reset_req_in7  (1'b0),                                 // (terminated),                       
		.reset_in8      (1'b0),                                 // (terminated),                       
		.reset_req_in8  (1'b0),                                 // (terminated),                       
		.reset_in9      (1'b0),                                 // (terminated),                       
		.reset_req_in9  (1'b0),                                 // (terminated),                       
		.reset_in10     (1'b0),                                 // (terminated),                       
		.reset_req_in10 (1'b0),                                 // (terminated),                       
		.reset_in11     (1'b0),                                 // (terminated),                       
		.reset_req_in11 (1'b0),                                 // (terminated),                       
		.reset_in12     (1'b0),                                 // (terminated),                       
		.reset_req_in12 (1'b0),                                 // (terminated),                       
		.reset_in13     (1'b0),                                 // (terminated),                       
		.reset_req_in13 (1'b0),                                 // (terminated),                       
		.reset_in14     (1'b0),                                 // (terminated),                       
		.reset_req_in14 (1'b0),                                 // (terminated),                       
		.reset_in15     (1'b0),                                 // (terminated),                       
		.reset_req_in15 (1'b0)                                  // (terminated),                       
	);

endmodule
