// niosv_intel_vvp_scaler_0_intel_vvp_scaler_2451_6cusdfa.v

// This file was auto-generated from intel_vvp_scaler_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module niosv_intel_vvp_scaler_0_intel_vvp_scaler_2451_6cusdfa (
		input  wire        main_clock_clk,                    //          main_clock.clk,          Clock Input
		input  wire        main_reset_reset,                  //          main_reset.reset
		input  wire [23:0] axi4s_vid_in_tdata,                //        axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,               //                    .tvalid
		output wire        axi4s_vid_in_tready,               //                    .tready
		input  wire        axi4s_vid_in_tlast,                //                    .tlast
		input  wire [2:0]  axi4s_vid_in_tuser,                //                    .tuser
		output wire [23:0] axi4s_vid_out_tdata,               //       axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid,              //                    .tvalid
		input  wire        axi4s_vid_out_tready,              //                    .tready
		output wire        axi4s_vid_out_tlast,               //                    .tlast
		output wire [2:0]  axi4s_vid_out_tuser,               //                    .tuser
		input  wire [7:0]  av_mm_control_agent_address,       // av_mm_control_agent.address
		input  wire        av_mm_control_agent_write,         //                    .write
		input  wire [3:0]  av_mm_control_agent_byteenable,    //                    .byteenable
		input  wire [31:0] av_mm_control_agent_writedata,     //                    .writedata
		input  wire        av_mm_control_agent_read,          //                    .read
		output wire [31:0] av_mm_control_agent_readdata,      //                    .readdata
		output wire        av_mm_control_agent_readdatavalid, //                    .readdatavalid
		output wire        av_mm_control_agent_waitrequest    //                    .waitrequest
	);

	wire          main_rst_bridge_out_reset_reset;                         // main_rst_bridge:out_rst -> [coeff_handler:rst, h_algo_comp:coeff_reset_reset, h_algo_comp:main_reset_reset, in_bridge:rst, line_buffer:rst, mm_interconnect_0:slave_interface_av_mm_master_translator_reset_reset_bridge_in_reset_reset, mm_interconnect_1:slave_interface_av_mm_data_master_translator_reset_reset_bridge_in_reset_reset, out_bridge:rst, scheduler:rst, slave_interface:main_reset_reset, v_algo_comp:coeff_rst, v_algo_comp:rst, v_round_sat:rst]
	wire          in_bridge_axi_st_data_out_tvalid;                        // in_bridge:axi_st_data_out_tvalid -> line_buffer:axi_st_data_in_tvalid
	wire    [2:0] in_bridge_axi_st_data_out_tuser;                         // in_bridge:axi_st_data_out_tuser -> line_buffer:axi_st_data_in_tuser
	wire          in_bridge_axi_st_data_out_tready;                        // line_buffer:axi_st_data_in_tready -> in_bridge:axi_st_data_out_tready
	wire   [23:0] in_bridge_axi_st_data_out_tdata;                         // in_bridge:axi_st_data_out_tdata -> line_buffer:axi_st_data_in_tdata
	wire          in_bridge_axi_st_data_out_tlast;                         // in_bridge:axi_st_data_out_tlast -> line_buffer:axi_st_data_in_tlast
	wire          in_bridge_axi_st_ctrl_out_tvalid;                        // in_bridge:axi_st_ctrl_out_tvalid -> scheduler:axi_st_ctrl_in_tvalid
	wire    [1:0] in_bridge_axi_st_ctrl_out_tuser;                         // in_bridge:axi_st_ctrl_out_tuser -> scheduler:axi_st_ctrl_in_tuser
	wire          in_bridge_axi_st_ctrl_out_tready;                        // scheduler:axi_st_ctrl_in_tready -> in_bridge:axi_st_ctrl_out_tready
	wire   [15:0] in_bridge_axi_st_ctrl_out_tdata;                         // in_bridge:axi_st_ctrl_out_tdata -> scheduler:axi_st_ctrl_in_tdata
	wire          in_bridge_axi_st_ctrl_out_tlast;                         // in_bridge:axi_st_ctrl_out_tlast -> scheduler:axi_st_ctrl_in_tlast
	wire          scheduler_axi_st_ctrl_out_tvalid;                        // scheduler:axi_st_ctrl_out_tvalid -> out_bridge:axi_st_ctrl_in_tvalid
	wire    [1:0] scheduler_axi_st_ctrl_out_tuser;                         // scheduler:axi_st_ctrl_out_tuser -> out_bridge:axi_st_ctrl_in_tuser
	wire          scheduler_axi_st_ctrl_out_tready;                        // out_bridge:axi_st_ctrl_in_tready -> scheduler:axi_st_ctrl_out_tready
	wire   [15:0] scheduler_axi_st_ctrl_out_tdata;                         // scheduler:axi_st_ctrl_out_tdata -> out_bridge:axi_st_ctrl_in_tdata
	wire          scheduler_axi_st_ctrl_out_tlast;                         // scheduler:axi_st_ctrl_out_tlast -> out_bridge:axi_st_ctrl_in_tlast
	wire          scheduler_axi_st_lb_cmd_tvalid;                          // scheduler:axi_st_lb_cmd_tvalid -> line_buffer:axi_st_cmd_tvalid
	wire          scheduler_axi_st_lb_cmd_tready;                          // line_buffer:axi_st_cmd_tready -> scheduler:axi_st_lb_cmd_tready
	wire   [23:0] scheduler_axi_st_lb_cmd_tdata;                           // scheduler:axi_st_lb_cmd_tdata -> line_buffer:axi_st_cmd_tdata
	wire          line_buffer_axi_st_data_out_tvalid;                      // line_buffer:axi_st_data_out_tvalid -> v_algo_comp:axi_st_data_in_tvalid
	wire   [17:0] line_buffer_axi_st_data_out_tuser;                       // line_buffer:axi_st_data_out_tuser -> v_algo_comp:axi_st_data_in_tuser
	wire          line_buffer_axi_st_data_out_tready;                      // v_algo_comp:axi_st_data_in_tready -> line_buffer:axi_st_data_out_tready
	wire  [143:0] line_buffer_axi_st_data_out_tdata;                       // line_buffer:axi_st_data_out_tdata -> v_algo_comp:axi_st_data_in_tdata
	wire          line_buffer_axi_st_data_out_tlast;                       // line_buffer:axi_st_data_out_tlast -> v_algo_comp:axi_st_data_in_tlast
	wire          v_algo_comp_axi_st_data_out_tvalid;                      // v_algo_comp:axi_st_data_out_tvalid -> v_round_sat:axi_st_data_in_tvalid
	wire    [7:0] v_algo_comp_axi_st_data_out_tuser;                       // v_algo_comp:axi_st_data_out_tuser -> v_round_sat:axi_st_data_in_tuser
	wire          v_algo_comp_axi_st_data_out_tready;                      // v_round_sat:axi_st_data_in_tready -> v_algo_comp:axi_st_data_out_tready
	wire   [63:0] v_algo_comp_axi_st_data_out_tdata;                       // v_algo_comp:axi_st_data_out_tdata -> v_round_sat:axi_st_data_in_tdata
	wire          v_algo_comp_axi_st_data_out_tlast;                       // v_algo_comp:axi_st_data_out_tlast -> v_round_sat:axi_st_data_in_tlast
	wire          scheduler_axi_st_v_core_cmd_tvalid;                      // scheduler:axi_st_v_core_cmd_tvalid -> v_algo_comp:axi_st_cmd_tvalid
	wire          scheduler_axi_st_v_core_cmd_tready;                      // v_algo_comp:axi_st_cmd_tready -> scheduler:axi_st_v_core_cmd_tready
	wire   [55:0] scheduler_axi_st_v_core_cmd_tdata;                       // scheduler:axi_st_v_core_cmd_tdata -> v_algo_comp:axi_st_cmd_tdata
	wire          scheduler_axi_st_h_core_cmd_tvalid;                      // scheduler:axi_st_h_core_cmd_tvalid -> h_algo_comp:axi_st_cmd_tvalid
	wire          scheduler_axi_st_h_core_cmd_tready;                      // h_algo_comp:axi_st_cmd_tready -> scheduler:axi_st_h_core_cmd_tready
	wire  [127:0] scheduler_axi_st_h_core_cmd_tdata;                       // scheduler:axi_st_h_core_cmd_tdata -> h_algo_comp:axi_st_cmd_tdata
	wire          v_round_sat_axi_st_data_out_tvalid;                      // v_round_sat:axi_st_data_out_tvalid -> h_algo_comp:axi_st_data_in_tvalid
	wire    [3:0] v_round_sat_axi_st_data_out_tuser;                       // v_round_sat:axi_st_data_out_tuser -> h_algo_comp:axi_st_data_in_tuser
	wire          v_round_sat_axi_st_data_out_tready;                      // h_algo_comp:axi_st_data_in_tready -> v_round_sat:axi_st_data_out_tready
	wire   [31:0] v_round_sat_axi_st_data_out_tdata;                       // v_round_sat:axi_st_data_out_tdata -> h_algo_comp:axi_st_data_in_tdata
	wire          v_round_sat_axi_st_data_out_tlast;                       // v_round_sat:axi_st_data_out_tlast -> h_algo_comp:axi_st_data_in_tlast
	wire          h_algo_comp_axi_st_data_out_tvalid;                      // h_algo_comp:axi_st_data_out_tvalid -> out_bridge:axi_st_data_in_tvalid
	wire    [2:0] h_algo_comp_axi_st_data_out_tuser;                       // h_algo_comp:axi_st_data_out_tuser -> out_bridge:axi_st_data_in_tuser
	wire          h_algo_comp_axi_st_data_out_tready;                      // out_bridge:axi_st_data_in_tready -> h_algo_comp:axi_st_data_out_tready
	wire   [23:0] h_algo_comp_axi_st_data_out_tdata;                       // h_algo_comp:axi_st_data_out_tdata -> out_bridge:axi_st_data_in_tdata
	wire          h_algo_comp_axi_st_data_out_tlast;                       // h_algo_comp:axi_st_data_out_tlast -> out_bridge:axi_st_data_in_tlast
	wire          coeff_handler_axi_st_horiz_coeff_tvalid;                 // coeff_handler:axi_st_horiz_coeff_tvalid -> h_algo_comp:axi_st_coeff_tvalid
	wire    [6:0] coeff_handler_axi_st_horiz_coeff_tuser;                  // coeff_handler:axi_st_horiz_coeff_tuser -> h_algo_comp:axi_st_coeff_tuser
	wire          coeff_handler_axi_st_horiz_coeff_tready;                 // h_algo_comp:axi_st_coeff_tready -> coeff_handler:axi_st_horiz_coeff_tready
	wire   [55:0] coeff_handler_axi_st_horiz_coeff_tdata;                  // coeff_handler:axi_st_horiz_coeff_tdata -> h_algo_comp:axi_st_coeff_tdata
	wire          coeff_handler_axi_st_horiz_coeff_tlast;                  // coeff_handler:axi_st_horiz_coeff_tlast -> h_algo_comp:axi_st_coeff_tlast
	wire          coeff_handler_axi_st_vert_coeff_tvalid;                  // coeff_handler:axi_st_vert_coeff_tvalid -> v_algo_comp:axi_st_coeff_tvalid
	wire    [2:0] coeff_handler_axi_st_vert_coeff_tuser;                   // coeff_handler:axi_st_vert_coeff_tuser -> v_algo_comp:axi_st_coeff_tuser
	wire          coeff_handler_axi_st_vert_coeff_tready;                  // v_algo_comp:axi_st_coeff_tready -> coeff_handler:axi_st_vert_coeff_tready
	wire   [23:0] coeff_handler_axi_st_vert_coeff_tdata;                   // coeff_handler:axi_st_vert_coeff_tdata -> v_algo_comp:axi_st_coeff_tdata
	wire          coeff_handler_axi_st_vert_coeff_tlast;                   // coeff_handler:axi_st_vert_coeff_tlast -> v_algo_comp:axi_st_coeff_tlast
	wire          slave_interface_av_mm_master_waitrequest;                // mm_interconnect_0:slave_interface_av_mm_master_waitrequest -> slave_interface:av_mm_master_waitrequest
	wire   [31:0] slave_interface_av_mm_master_readdata;                   // mm_interconnect_0:slave_interface_av_mm_master_readdata -> slave_interface:av_mm_master_readdata
	wire    [7:0] slave_interface_av_mm_master_address;                    // slave_interface:av_mm_master_address -> mm_interconnect_0:slave_interface_av_mm_master_address
	wire    [3:0] slave_interface_av_mm_master_byteenable;                 // slave_interface:av_mm_master_byteenable -> mm_interconnect_0:slave_interface_av_mm_master_byteenable
	wire          slave_interface_av_mm_master_read;                       // slave_interface:av_mm_master_read -> mm_interconnect_0:slave_interface_av_mm_master_read
	wire          slave_interface_av_mm_master_readdatavalid;              // mm_interconnect_0:slave_interface_av_mm_master_readdatavalid -> slave_interface:av_mm_master_readdatavalid
	wire          slave_interface_av_mm_master_write;                      // slave_interface:av_mm_master_write -> mm_interconnect_0:slave_interface_av_mm_master_write
	wire   [31:0] slave_interface_av_mm_master_writedata;                  // slave_interface:av_mm_master_writedata -> mm_interconnect_0:slave_interface_av_mm_master_writedata
	wire   [31:0] mm_interconnect_0_scheduler_av_mm_slave_readdata;        // scheduler:av_mm_slave_readdata -> mm_interconnect_0:scheduler_av_mm_slave_readdata
	wire          mm_interconnect_0_scheduler_av_mm_slave_waitrequest;     // scheduler:av_mm_slave_waitrequest -> mm_interconnect_0:scheduler_av_mm_slave_waitrequest
	wire    [5:0] mm_interconnect_0_scheduler_av_mm_slave_address;         // mm_interconnect_0:scheduler_av_mm_slave_address -> scheduler:av_mm_slave_address
	wire          mm_interconnect_0_scheduler_av_mm_slave_read;            // mm_interconnect_0:scheduler_av_mm_slave_read -> scheduler:av_mm_slave_read
	wire    [3:0] mm_interconnect_0_scheduler_av_mm_slave_byteenable;      // mm_interconnect_0:scheduler_av_mm_slave_byteenable -> scheduler:av_mm_slave_byteenable
	wire          mm_interconnect_0_scheduler_av_mm_slave_readdatavalid;   // scheduler:av_mm_slave_readdatavalid -> mm_interconnect_0:scheduler_av_mm_slave_readdatavalid
	wire          mm_interconnect_0_scheduler_av_mm_slave_write;           // mm_interconnect_0:scheduler_av_mm_slave_write -> scheduler:av_mm_slave_write
	wire   [31:0] mm_interconnect_0_scheduler_av_mm_slave_writedata;       // mm_interconnect_0:scheduler_av_mm_slave_writedata -> scheduler:av_mm_slave_writedata
	wire          slave_interface_av_mm_data_master_waitrequest;           // mm_interconnect_1:slave_interface_av_mm_data_master_waitrequest -> slave_interface:av_mm_data_master_waitrequest
	wire    [8:0] slave_interface_av_mm_data_master_address;               // slave_interface:av_mm_data_master_address -> mm_interconnect_1:slave_interface_av_mm_data_master_address
	wire    [3:0] slave_interface_av_mm_data_master_byteenable;            // slave_interface:av_mm_data_master_byteenable -> mm_interconnect_1:slave_interface_av_mm_data_master_byteenable
	wire          slave_interface_av_mm_data_master_write;                 // slave_interface:av_mm_data_master_write -> mm_interconnect_1:slave_interface_av_mm_data_master_write
	wire   [31:0] slave_interface_av_mm_data_master_writedata;             // slave_interface:av_mm_data_master_writedata -> mm_interconnect_1:slave_interface_av_mm_data_master_writedata
	wire          mm_interconnect_1_coeff_handler_av_mm_slave_waitrequest; // coeff_handler:av_mm_slave_waitrequest -> mm_interconnect_1:coeff_handler_av_mm_slave_waitrequest
	wire    [6:0] mm_interconnect_1_coeff_handler_av_mm_slave_address;     // mm_interconnect_1:coeff_handler_av_mm_slave_address -> coeff_handler:av_mm_slave_address
	wire    [3:0] mm_interconnect_1_coeff_handler_av_mm_slave_byteenable;  // mm_interconnect_1:coeff_handler_av_mm_slave_byteenable -> coeff_handler:av_mm_slave_byteenable
	wire          mm_interconnect_1_coeff_handler_av_mm_slave_write;       // mm_interconnect_1:coeff_handler_av_mm_slave_write -> coeff_handler:av_mm_slave_write
	wire   [31:0] mm_interconnect_1_coeff_handler_av_mm_slave_writedata;   // mm_interconnect_1:coeff_handler_av_mm_slave_writedata -> coeff_handler:av_mm_slave_writedata

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_input_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) in_bridge (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_ccd_in_tdata    (axi4s_vid_in_tdata),               //   input,  width = 24,   axi_st_ccd_in.tdata
		.axi_st_ccd_in_tvalid   (axi4s_vid_in_tvalid),              //   input,   width = 1,                .tvalid
		.axi_st_ccd_in_tready   (axi4s_vid_in_tready),              //  output,   width = 1,                .tready
		.axi_st_ccd_in_tlast    (axi4s_vid_in_tlast),               //   input,   width = 1,                .tlast
		.axi_st_ccd_in_tuser    (axi4s_vid_in_tuser),               //   input,   width = 3,                .tuser
		.axi_st_ctrl_out_tdata  (in_bridge_axi_st_ctrl_out_tdata),  //  output,  width = 16, axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid (in_bridge_axi_st_ctrl_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_ctrl_out_tready (in_bridge_axi_st_ctrl_out_tready), //   input,   width = 1,                .tready
		.axi_st_ctrl_out_tlast  (in_bridge_axi_st_ctrl_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_ctrl_out_tuser  (in_bridge_axi_st_ctrl_out_tuser),  //  output,   width = 2,                .tuser
		.axi_st_data_out_tdata  (in_bridge_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (in_bridge_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (in_bridge_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (in_bridge_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (in_bridge_axi_st_data_out_tuser)   //  output,   width = 3,                .tuser
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (1),
		.EXTERNAL_MODE          (0)
	) out_bridge (
		.clk                   (main_clock_clk),                     //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),    //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi_st_ctrl_out_tdata),    //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi_st_ctrl_out_tvalid),   //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi_st_ctrl_out_tready),   //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi_st_ctrl_out_tlast),    //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi_st_ctrl_out_tuser),    //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (h_algo_comp_axi_st_data_out_tdata),  //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (h_algo_comp_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (h_algo_comp_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (h_algo_comp_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (h_algo_comp_axi_st_data_out_tuser),  //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),                //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),               //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),               //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),                //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)                 //  output,   width = 3,               .tuser
	);

	intel_vvp_line_buffer #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.MAX_WIDTH              (8192),
		.NUM_LINES              (6),
		.ENABLE_RESEND          (1),
		.CMD_COMPATIBILITY      (0),
		.ENABLE_RESPONSE        (0),
		.PIPELINE_READY         (1),
		.DEVICE_FAMILY          ("Agilex 5")
	) line_buffer (
		.clk                    (main_clock_clk),                     //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_lb_cmd_tdata),      //   input,   width = 24,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_lb_cmd_tvalid),     //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_lb_cmd_tready),     //  output,    width = 1,                .tready
		.axi_st_data_in_tdata   (in_bridge_axi_st_data_out_tdata),    //   input,   width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (in_bridge_axi_st_data_out_tvalid),   //   input,    width = 1,                .tvalid
		.axi_st_data_in_tready  (in_bridge_axi_st_data_out_tready),   //  output,    width = 1,                .tready
		.axi_st_data_in_tlast   (in_bridge_axi_st_data_out_tlast),    //   input,    width = 1,                .tlast
		.axi_st_data_in_tuser   (in_bridge_axi_st_data_out_tuser),    //   input,    width = 3,                .tuser
		.axi_st_data_out_tdata  (line_buffer_axi_st_data_out_tdata),  //  output,  width = 144, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (line_buffer_axi_st_data_out_tvalid), //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (line_buffer_axi_st_data_out_tready), //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (line_buffer_axi_st_data_out_tlast),  //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (line_buffer_axi_st_data_out_tuser),  //  output,   width = 18,                .tuser
		.axi_st_resp_tdata      (),                                   // (terminated),                               
		.axi_st_resp_tvalid     (),                                   // (terminated),                               
		.axi_st_resp_tready     (1'b0)                                // (terminated),                               
	);

	intel_vvp_vert_scaler_scheduler #(
		.EXTERNAL_MODE          (0),
		.H_PARTIAL_SCALING      (0),
		.V_PARTIAL_SCALING      (0),
		.ENABLE_V_CORE          (1),
		.ENABLE_H_CORE          (1),
		.ENABLE_444             (1),
		.ENABLE_422             (0),
		.ENABLE_420             (0),
		.ENABLE_420_MIRROR      (0),
		.H_TAPS                 (6),
		.V_TAPS                 (6),
		.V_PHASES               (64),
		.NO_BLANKING            (0),
		.PIXELS_IN_PARALLEL     (1),
		.MAX_IN_WIDTH           (8192),
		.MAX_OUT_WIDTH          (8192),
		.OUTPUT_HEIGHT          (4320),
		.RUNTIME_CONTROL        (1),
		.ENABLE_DEBUG           (0),
		.P_UPDATE_CMD_SUPPORTED (0),
		.P_CORE_CTRL_ID         (0),
		.H_BANKS                (1),
		.V_BANKS                (1),
		.PIPELINE_READY         (0),
		.SLAVE_ADDRESS_WIDTH    (6)
	) scheduler (
		.clk                       (main_clock_clk),                                        //   input,    width = 1,        main_clock.clk
		.rst                       (main_rst_bridge_out_reset_reset),                       //   input,    width = 1,        main_reset.reset
		.av_mm_slave_address       (mm_interconnect_0_scheduler_av_mm_slave_address),       //   input,    width = 6,       av_mm_slave.address
		.av_mm_slave_write         (mm_interconnect_0_scheduler_av_mm_slave_write),         //   input,    width = 1,                  .write
		.av_mm_slave_byteenable    (mm_interconnect_0_scheduler_av_mm_slave_byteenable),    //   input,    width = 4,                  .byteenable
		.av_mm_slave_writedata     (mm_interconnect_0_scheduler_av_mm_slave_writedata),     //   input,   width = 32,                  .writedata
		.av_mm_slave_read          (mm_interconnect_0_scheduler_av_mm_slave_read),          //   input,    width = 1,                  .read
		.av_mm_slave_readdata      (mm_interconnect_0_scheduler_av_mm_slave_readdata),      //  output,   width = 32,                  .readdata
		.av_mm_slave_readdatavalid (mm_interconnect_0_scheduler_av_mm_slave_readdatavalid), //  output,    width = 1,                  .readdatavalid
		.av_mm_slave_waitrequest   (mm_interconnect_0_scheduler_av_mm_slave_waitrequest),   //  output,    width = 1,                  .waitrequest
		.axi_st_ctrl_in_tdata      (in_bridge_axi_st_ctrl_out_tdata),                       //   input,   width = 16,    axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid     (in_bridge_axi_st_ctrl_out_tvalid),                      //   input,    width = 1,                  .tvalid
		.axi_st_ctrl_in_tready     (in_bridge_axi_st_ctrl_out_tready),                      //  output,    width = 1,                  .tready
		.axi_st_ctrl_in_tlast      (in_bridge_axi_st_ctrl_out_tlast),                       //   input,    width = 1,                  .tlast
		.axi_st_ctrl_in_tuser      (in_bridge_axi_st_ctrl_out_tuser),                       //   input,    width = 2,                  .tuser
		.axi_st_ctrl_out_tdata     (scheduler_axi_st_ctrl_out_tdata),                       //  output,   width = 16,   axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid    (scheduler_axi_st_ctrl_out_tvalid),                      //  output,    width = 1,                  .tvalid
		.axi_st_ctrl_out_tready    (scheduler_axi_st_ctrl_out_tready),                      //   input,    width = 1,                  .tready
		.axi_st_ctrl_out_tlast     (scheduler_axi_st_ctrl_out_tlast),                       //  output,    width = 1,                  .tlast
		.axi_st_ctrl_out_tuser     (scheduler_axi_st_ctrl_out_tuser),                       //  output,    width = 2,                  .tuser
		.axi_st_lb_cmd_tdata       (scheduler_axi_st_lb_cmd_tdata),                         //  output,   width = 24,     axi_st_lb_cmd.tdata
		.axi_st_lb_cmd_tvalid      (scheduler_axi_st_lb_cmd_tvalid),                        //  output,    width = 1,                  .tvalid
		.axi_st_lb_cmd_tready      (scheduler_axi_st_lb_cmd_tready),                        //   input,    width = 1,                  .tready
		.axi_st_v_core_cmd_tdata   (scheduler_axi_st_v_core_cmd_tdata),                     //  output,   width = 56, axi_st_v_core_cmd.tdata
		.axi_st_v_core_cmd_tvalid  (scheduler_axi_st_v_core_cmd_tvalid),                    //  output,    width = 1,                  .tvalid
		.axi_st_v_core_cmd_tready  (scheduler_axi_st_v_core_cmd_tready),                    //   input,    width = 1,                  .tready
		.axi_st_h_core_cmd_tdata   (scheduler_axi_st_h_core_cmd_tdata),                     //  output,  width = 128, axi_st_h_core_cmd.tdata
		.axi_st_h_core_cmd_tvalid  (scheduler_axi_st_h_core_cmd_tvalid),                    //  output,    width = 1,                  .tvalid
		.axi_st_h_core_cmd_tready  (scheduler_axi_st_h_core_cmd_tready),                    //   input,    width = 1,                  .tready
		.axi_st_ls_cmd_tdata       (),                                                      // (terminated),                                 
		.axi_st_ls_cmd_tvalid      (),                                                      // (terminated),                                 
		.axi_st_ls_cmd_tready      (1'b0),                                                  // (terminated),                                 
		.axi_st_lb_resp_tdata      (8'b00000000),                                           // (terminated),                                 
		.axi_st_lb_resp_tvalid     (1'b0),                                                  // (terminated),                                 
		.axi_st_lb_resp_tready     ()                                                       // (terminated),                                 
	);

	niosv_intel_vvp_scaler_0_intel_vvp_vert_scaler_algo_comp_2451_ymbvhki v_algo_comp (
		.clk                    (main_clock_clk),                         //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),        //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_v_core_cmd_tdata),      //   input,   width = 56,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_v_core_cmd_tvalid),     //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_v_core_cmd_tready),     //  output,    width = 1,                .tready
		.coeff_clk              (main_clock_clk),                         //   input,    width = 1,     coeff_clock.clk
		.coeff_rst              (main_rst_bridge_out_reset_reset),        //   input,    width = 1,     coeff_reset.reset
		.axi_st_coeff_tdata     (coeff_handler_axi_st_vert_coeff_tdata),  //   input,   width = 24,    axi_st_coeff.tdata
		.axi_st_coeff_tvalid    (coeff_handler_axi_st_vert_coeff_tvalid), //   input,    width = 1,                .tvalid
		.axi_st_coeff_tready    (coeff_handler_axi_st_vert_coeff_tready), //  output,    width = 1,                .tready
		.axi_st_coeff_tlast     (coeff_handler_axi_st_vert_coeff_tlast),  //   input,    width = 1,                .tlast
		.axi_st_coeff_tuser     (coeff_handler_axi_st_vert_coeff_tuser),  //   input,    width = 3,                .tuser
		.axi_st_data_in_tdata   (line_buffer_axi_st_data_out_tdata),      //   input,  width = 144,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (line_buffer_axi_st_data_out_tvalid),     //   input,    width = 1,                .tvalid
		.axi_st_data_in_tready  (line_buffer_axi_st_data_out_tready),     //  output,    width = 1,                .tready
		.axi_st_data_in_tlast   (line_buffer_axi_st_data_out_tlast),      //   input,    width = 1,                .tlast
		.axi_st_data_in_tuser   (line_buffer_axi_st_data_out_tuser),      //   input,   width = 18,                .tuser
		.axi_st_data_out_tdata  (v_algo_comp_axi_st_data_out_tdata),      //  output,   width = 64, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (v_algo_comp_axi_st_data_out_tvalid),     //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (v_algo_comp_axi_st_data_out_tready),     //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (v_algo_comp_axi_st_data_out_tlast),      //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (v_algo_comp_axi_st_data_out_tuser)       //  output,    width = 8,                .tuser
	);

	intel_vvp_round_sat_algo_comp #(
		.BPS_IN                 (19),
		.BPS_OUT                (10),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.UNSIGNED_INPUT         (0),
		.FRAC_BITS_IN           (6),
		.PRESERVE_BITS          (0),
		.UNSIGNED_OUTPUT        (0),
		.DO_ROUNDING            (1),
		.PIPELINE_READY         (0)
	) v_round_sat (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (v_algo_comp_axi_st_data_out_tdata),  //   input,  width = 64,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (v_algo_comp_axi_st_data_out_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (v_algo_comp_axi_st_data_out_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (v_algo_comp_axi_st_data_out_tlast),  //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (v_algo_comp_axi_st_data_out_tuser),  //   input,   width = 8,                .tuser
		.axi_st_data_out_tdata  (v_round_sat_axi_st_data_out_tdata),  //  output,  width = 32, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (v_round_sat_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (v_round_sat_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (v_round_sat_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (v_round_sat_axi_st_data_out_tuser)   //  output,   width = 4,                .tuser
	);

	niosv_intel_vvp_scaler_0_intel_vvp_scaler_h_macro_2451_6c3lnyy h_algo_comp (
		.main_clock_clk         (main_clock_clk),                          //   input,    width = 1,      main_clock.clk
		.main_reset_reset       (main_rst_bridge_out_reset_reset),         //   input,    width = 1,      main_reset.reset
		.coeff_clock_clk        (main_clock_clk),                          //   input,    width = 1,     coeff_clock.clk
		.coeff_reset_reset      (main_rst_bridge_out_reset_reset),         //   input,    width = 1,     coeff_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_h_core_cmd_tdata),       //   input,  width = 128,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_h_core_cmd_tvalid),      //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_h_core_cmd_tready),      //  output,    width = 1,                .tready
		.axi_st_coeff_tdata     (coeff_handler_axi_st_horiz_coeff_tdata),  //   input,   width = 56,    axi_st_coeff.tdata
		.axi_st_coeff_tvalid    (coeff_handler_axi_st_horiz_coeff_tvalid), //   input,    width = 1,                .tvalid
		.axi_st_coeff_tready    (coeff_handler_axi_st_horiz_coeff_tready), //  output,    width = 1,                .tready
		.axi_st_coeff_tlast     (coeff_handler_axi_st_horiz_coeff_tlast),  //   input,    width = 1,                .tlast
		.axi_st_coeff_tuser     (coeff_handler_axi_st_horiz_coeff_tuser),  //   input,    width = 7,                .tuser
		.axi_st_data_in_tdata   (v_round_sat_axi_st_data_out_tdata),       //   input,   width = 32,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (v_round_sat_axi_st_data_out_tvalid),      //   input,    width = 1,                .tvalid
		.axi_st_data_in_tready  (v_round_sat_axi_st_data_out_tready),      //  output,    width = 1,                .tready
		.axi_st_data_in_tlast   (v_round_sat_axi_st_data_out_tlast),       //   input,    width = 1,                .tlast
		.axi_st_data_in_tuser   (v_round_sat_axi_st_data_out_tuser),       //   input,    width = 4,                .tuser
		.axi_st_data_out_tdata  (h_algo_comp_axi_st_data_out_tdata),       //  output,   width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (h_algo_comp_axi_st_data_out_tvalid),      //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (h_algo_comp_axi_st_data_out_tready),      //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (h_algo_comp_axi_st_data_out_tlast),       //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (h_algo_comp_axi_st_data_out_tuser)        //  output,    width = 3,                .tuser
	);

	niosv_intel_vvp_scaler_0_intel_vvp_slave_front_end_2441_swkcwha #(
		.ENABLE_DATA_RW       (0),
		.AV_MAX_PENDING_READS (2)
	) slave_interface (
		.main_clock_clk                (main_clock_clk),                                //   input,   width = 1,        main_clock.clk
		.main_reset_reset              (main_rst_bridge_out_reset_reset),               //   input,   width = 1,        main_reset.reset
		.av_mm_master_address          (slave_interface_av_mm_master_address),          //  output,   width = 8,      av_mm_master.address
		.av_mm_master_waitrequest      (slave_interface_av_mm_master_waitrequest),      //   input,   width = 1,                  .waitrequest
		.av_mm_master_write            (slave_interface_av_mm_master_write),            //  output,   width = 1,                  .write
		.av_mm_master_writedata        (slave_interface_av_mm_master_writedata),        //  output,  width = 32,                  .writedata
		.av_mm_master_byteenable       (slave_interface_av_mm_master_byteenable),       //  output,   width = 4,                  .byteenable
		.av_mm_master_read             (slave_interface_av_mm_master_read),             //  output,   width = 1,                  .read
		.av_mm_master_readdata         (slave_interface_av_mm_master_readdata),         //   input,  width = 32,                  .readdata
		.av_mm_master_readdatavalid    (slave_interface_av_mm_master_readdatavalid),    //   input,   width = 1,                  .readdatavalid
		.av_mm_data_master_address     (slave_interface_av_mm_data_master_address),     //  output,   width = 9, av_mm_data_master.address
		.av_mm_data_master_waitrequest (slave_interface_av_mm_data_master_waitrequest), //   input,   width = 1,                  .waitrequest
		.av_mm_data_master_write       (slave_interface_av_mm_data_master_write),       //  output,   width = 1,                  .write
		.av_mm_data_master_writedata   (slave_interface_av_mm_data_master_writedata),   //  output,  width = 32,                  .writedata
		.av_mm_data_master_byteenable  (slave_interface_av_mm_data_master_byteenable),  //  output,   width = 4,                  .byteenable
		.av_mm_slave_address           (av_mm_control_agent_address),                   //   input,   width = 8,       av_mm_slave.address
		.av_mm_slave_write             (av_mm_control_agent_write),                     //   input,   width = 1,                  .write
		.av_mm_slave_byteenable        (av_mm_control_agent_byteenable),                //   input,   width = 4,                  .byteenable
		.av_mm_slave_writedata         (av_mm_control_agent_writedata),                 //   input,  width = 32,                  .writedata
		.av_mm_slave_read              (av_mm_control_agent_read),                      //   input,   width = 1,                  .read
		.av_mm_slave_readdata          (av_mm_control_agent_readdata),                  //  output,  width = 32,                  .readdata
		.av_mm_slave_readdatavalid     (av_mm_control_agent_readdatavalid),             //  output,   width = 1,                  .readdatavalid
		.av_mm_slave_waitrequest       (av_mm_control_agent_waitrequest)                //  output,   width = 1,                  .waitrequest
	);

	intel_vvp_scaler_coeff_handler #(
		.ENABLE_V      (1),
		.ENABLE_H      (1),
		.V_COEFF_WIDTH (8),
		.H_COEFF_WIDTH (8),
		.V_TAPS        (6),
		.H_TAPS        (6),
		.V_PHASES      (64),
		.H_PHASES      (64),
		.V_BANKS       (1),
		.H_BANKS       (1)
	) coeff_handler (
		.clk                       (main_clock_clk),                                          //   input,   width = 1,         main_clock.clk
		.rst                       (main_rst_bridge_out_reset_reset),                         //   input,   width = 1,         main_reset.reset
		.av_mm_slave_address       (mm_interconnect_1_coeff_handler_av_mm_slave_address),     //   input,   width = 7,        av_mm_slave.address
		.av_mm_slave_byteenable    (mm_interconnect_1_coeff_handler_av_mm_slave_byteenable),  //   input,   width = 4,                   .byteenable
		.av_mm_slave_write         (mm_interconnect_1_coeff_handler_av_mm_slave_write),       //   input,   width = 1,                   .write
		.av_mm_slave_writedata     (mm_interconnect_1_coeff_handler_av_mm_slave_writedata),   //   input,  width = 32,                   .writedata
		.av_mm_slave_waitrequest   (mm_interconnect_1_coeff_handler_av_mm_slave_waitrequest), //  output,   width = 1,                   .waitrequest
		.axi_st_vert_coeff_tdata   (coeff_handler_axi_st_vert_coeff_tdata),                   //  output,  width = 24,  axi_st_vert_coeff.tdata
		.axi_st_vert_coeff_tvalid  (coeff_handler_axi_st_vert_coeff_tvalid),                  //  output,   width = 1,                   .tvalid
		.axi_st_vert_coeff_tready  (coeff_handler_axi_st_vert_coeff_tready),                  //   input,   width = 1,                   .tready
		.axi_st_vert_coeff_tlast   (coeff_handler_axi_st_vert_coeff_tlast),                   //  output,   width = 1,                   .tlast
		.axi_st_vert_coeff_tuser   (coeff_handler_axi_st_vert_coeff_tuser),                   //  output,   width = 3,                   .tuser
		.axi_st_horiz_coeff_tdata  (coeff_handler_axi_st_horiz_coeff_tdata),                  //  output,  width = 56, axi_st_horiz_coeff.tdata
		.axi_st_horiz_coeff_tvalid (coeff_handler_axi_st_horiz_coeff_tvalid),                 //  output,   width = 1,                   .tvalid
		.axi_st_horiz_coeff_tready (coeff_handler_axi_st_horiz_coeff_tready),                 //   input,   width = 1,                   .tready
		.axi_st_horiz_coeff_tlast  (coeff_handler_axi_st_horiz_coeff_tlast),                  //  output,   width = 1,                   .tlast
		.axi_st_horiz_coeff_tuser  (coeff_handler_axi_st_horiz_coeff_tuser)                   //  output,   width = 7,                   .tuser
	);

	niosv_intel_vvp_scaler_0_altera_mm_interconnect_1920_vevxpda mm_interconnect_0 (
		.slave_interface_av_mm_master_address                                      (slave_interface_av_mm_master_address),                  //   input,   width = 8,                                        slave_interface_av_mm_master.address
		.slave_interface_av_mm_master_waitrequest                                  (slave_interface_av_mm_master_waitrequest),              //  output,   width = 1,                                                                    .waitrequest
		.slave_interface_av_mm_master_byteenable                                   (slave_interface_av_mm_master_byteenable),               //   input,   width = 4,                                                                    .byteenable
		.slave_interface_av_mm_master_read                                         (slave_interface_av_mm_master_read),                     //   input,   width = 1,                                                                    .read
		.slave_interface_av_mm_master_readdata                                     (slave_interface_av_mm_master_readdata),                 //  output,  width = 32,                                                                    .readdata
		.slave_interface_av_mm_master_readdatavalid                                (slave_interface_av_mm_master_readdatavalid),            //  output,   width = 1,                                                                    .readdatavalid
		.slave_interface_av_mm_master_write                                        (slave_interface_av_mm_master_write),                    //   input,   width = 1,                                                                    .write
		.slave_interface_av_mm_master_writedata                                    (slave_interface_av_mm_master_writedata),                //   input,  width = 32,                                                                    .writedata
		.scheduler_av_mm_slave_address                                             (mm_interconnect_0_scheduler_av_mm_slave_address),       //  output,   width = 6,                                               scheduler_av_mm_slave.address
		.scheduler_av_mm_slave_write                                               (mm_interconnect_0_scheduler_av_mm_slave_write),         //  output,   width = 1,                                                                    .write
		.scheduler_av_mm_slave_read                                                (mm_interconnect_0_scheduler_av_mm_slave_read),          //  output,   width = 1,                                                                    .read
		.scheduler_av_mm_slave_readdata                                            (mm_interconnect_0_scheduler_av_mm_slave_readdata),      //   input,  width = 32,                                                                    .readdata
		.scheduler_av_mm_slave_writedata                                           (mm_interconnect_0_scheduler_av_mm_slave_writedata),     //  output,  width = 32,                                                                    .writedata
		.scheduler_av_mm_slave_byteenable                                          (mm_interconnect_0_scheduler_av_mm_slave_byteenable),    //  output,   width = 4,                                                                    .byteenable
		.scheduler_av_mm_slave_readdatavalid                                       (mm_interconnect_0_scheduler_av_mm_slave_readdatavalid), //   input,   width = 1,                                                                    .readdatavalid
		.scheduler_av_mm_slave_waitrequest                                         (mm_interconnect_0_scheduler_av_mm_slave_waitrequest),   //   input,   width = 1,                                                                    .waitrequest
		.slave_interface_av_mm_master_translator_reset_reset_bridge_in_reset_reset (main_rst_bridge_out_reset_reset),                       //   input,   width = 1, slave_interface_av_mm_master_translator_reset_reset_bridge_in_reset.reset
		.main_clk_bridge_out_clk_clk                                               (main_clock_clk)                                         //   input,   width = 1,                                             main_clk_bridge_out_clk.clk
	);

	niosv_intel_vvp_scaler_0_altera_mm_interconnect_1920_vg4v6pi mm_interconnect_1 (
		.slave_interface_av_mm_data_master_address                                      (slave_interface_av_mm_data_master_address),               //   input,   width = 9,                                        slave_interface_av_mm_data_master.address
		.slave_interface_av_mm_data_master_waitrequest                                  (slave_interface_av_mm_data_master_waitrequest),           //  output,   width = 1,                                                                         .waitrequest
		.slave_interface_av_mm_data_master_byteenable                                   (slave_interface_av_mm_data_master_byteenable),            //   input,   width = 4,                                                                         .byteenable
		.slave_interface_av_mm_data_master_write                                        (slave_interface_av_mm_data_master_write),                 //   input,   width = 1,                                                                         .write
		.slave_interface_av_mm_data_master_writedata                                    (slave_interface_av_mm_data_master_writedata),             //   input,  width = 32,                                                                         .writedata
		.coeff_handler_av_mm_slave_address                                              (mm_interconnect_1_coeff_handler_av_mm_slave_address),     //  output,   width = 7,                                                coeff_handler_av_mm_slave.address
		.coeff_handler_av_mm_slave_write                                                (mm_interconnect_1_coeff_handler_av_mm_slave_write),       //  output,   width = 1,                                                                         .write
		.coeff_handler_av_mm_slave_writedata                                            (mm_interconnect_1_coeff_handler_av_mm_slave_writedata),   //  output,  width = 32,                                                                         .writedata
		.coeff_handler_av_mm_slave_byteenable                                           (mm_interconnect_1_coeff_handler_av_mm_slave_byteenable),  //  output,   width = 4,                                                                         .byteenable
		.coeff_handler_av_mm_slave_waitrequest                                          (mm_interconnect_1_coeff_handler_av_mm_slave_waitrequest), //   input,   width = 1,                                                                         .waitrequest
		.slave_interface_av_mm_data_master_translator_reset_reset_bridge_in_reset_reset (main_rst_bridge_out_reset_reset),                         //   input,   width = 1, slave_interface_av_mm_data_master_translator_reset_reset_bridge_in_reset.reset
		.main_clk_bridge_out_clk_clk                                                    (main_clock_clk)                                           //   input,   width = 1,                                                  main_clk_bridge_out_clk.clk
	);

endmodule
