// system_intel_vvp_protocol_conv_1_intel_vvp_protocol_conv_2460_ydxwruq.v

// This file was auto-generated from intel_vvp_protocol_conv_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system_intel_vvp_protocol_conv_1_intel_vvp_protocol_conv_2460_ydxwruq (
		input  wire        main_clock_clk,       //    main_clock.clk,   Clock Input
		input  wire        main_reset_reset,     //    main_reset.reset
		input  wire [23:0] axi4s_vid_in_tdata,   //  axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,  //              .tvalid
		output wire        axi4s_vid_in_tready,  //              .tready
		input  wire        axi4s_vid_in_tlast,   //              .tlast
		input  wire [2:0]  axi4s_vid_in_tuser,   //              .tuser
		output wire [23:0] axi4s_vid_out_tdata,  // axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid, //              .tvalid
		input  wire        axi4s_vid_out_tready, //              .tready
		output wire        axi4s_vid_out_tlast,  //              .tlast
		output wire [2:0]  axi4s_vid_out_tuser   //              .tuser
	);

	wire         main_rst_bridge_out_reset_reset;  // main_rst_bridge:out_rst -> [in_bridge:rst, out_bridge:rst]
	wire         in_bridge_axi_st_ctrl_out_tvalid; // in_bridge:axi_st_ctrl_out_tvalid -> out_bridge:axi_st_ctrl_in_tvalid
	wire   [1:0] in_bridge_axi_st_ctrl_out_tuser;  // in_bridge:axi_st_ctrl_out_tuser -> out_bridge:axi_st_ctrl_in_tuser
	wire         in_bridge_axi_st_ctrl_out_tready; // out_bridge:axi_st_ctrl_in_tready -> in_bridge:axi_st_ctrl_out_tready
	wire  [15:0] in_bridge_axi_st_ctrl_out_tdata;  // in_bridge:axi_st_ctrl_out_tdata -> out_bridge:axi_st_ctrl_in_tdata
	wire         in_bridge_axi_st_ctrl_out_tlast;  // in_bridge:axi_st_ctrl_out_tlast -> out_bridge:axi_st_ctrl_in_tlast
	wire         in_bridge_axi_st_data_out_tvalid; // in_bridge:axi_st_data_out_tvalid -> out_bridge:axi_st_data_in_tvalid
	wire   [2:0] in_bridge_axi_st_data_out_tuser;  // in_bridge:axi_st_data_out_tuser -> out_bridge:axi_st_data_in_tuser
	wire         in_bridge_axi_st_data_out_tready; // out_bridge:axi_st_data_in_tready -> in_bridge:axi_st_data_out_tready
	wire  [23:0] in_bridge_axi_st_data_out_tdata;  // in_bridge:axi_st_data_out_tdata -> out_bridge:axi_st_data_in_tdata
	wire         in_bridge_axi_st_data_out_tlast;  // in_bridge:axi_st_data_out_tlast -> out_bridge:axi_st_data_in_tlast

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_int_to_ext_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0)
	) in_bridge (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_ccd_in_tdata    (axi4s_vid_in_tdata),               //   input,  width = 24,   axi_st_ccd_in.tdata
		.axi_st_ccd_in_tvalid   (axi4s_vid_in_tvalid),              //   input,   width = 1,                .tvalid
		.axi_st_ccd_in_tready   (axi4s_vid_in_tready),              //  output,   width = 1,                .tready
		.axi_st_ccd_in_tlast    (axi4s_vid_in_tlast),               //   input,   width = 1,                .tlast
		.axi_st_ccd_in_tuser    (axi4s_vid_in_tuser),               //   input,   width = 3,                .tuser
		.axi_st_ctrl_out_tdata  (in_bridge_axi_st_ctrl_out_tdata),  //  output,  width = 16, axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid (in_bridge_axi_st_ctrl_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_ctrl_out_tready (in_bridge_axi_st_ctrl_out_tready), //   input,   width = 1,                .tready
		.axi_st_ctrl_out_tlast  (in_bridge_axi_st_ctrl_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_ctrl_out_tuser  (in_bridge_axi_st_ctrl_out_tuser),  //  output,   width = 2,                .tuser
		.axi_st_data_out_tdata  (in_bridge_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (in_bridge_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (in_bridge_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (in_bridge_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (in_bridge_axi_st_data_out_tuser)   //  output,   width = 3,                .tuser
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (1)
	) out_bridge (
		.clk                   (main_clock_clk),                   //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),  //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (in_bridge_axi_st_ctrl_out_tdata),  //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (in_bridge_axi_st_ctrl_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (in_bridge_axi_st_ctrl_out_tready), //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (in_bridge_axi_st_ctrl_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (in_bridge_axi_st_ctrl_out_tuser),  //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (in_bridge_axi_st_data_out_tdata),  //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (in_bridge_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (in_bridge_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (in_bridge_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (in_bridge_axi_st_data_out_tuser),  //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),              //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),             //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),             //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),              //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)               //  output,   width = 3,               .tuser
	);

endmodule
