// color_space_intel_vvp_csc_0_intel_vvp_csc_2451_6iisa2q.v

// This file was auto-generated from intel_vvp_csc_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module color_space_intel_vvp_csc_0_intel_vvp_csc_2451_6iisa2q #(
		parameter P_UPDATE_CMD_SUPPORTED = 0,
		parameter P_CORE_CTRL_ID         = 0
	) (
		input  wire        main_clock_clk,       //    main_clock.clk,   Clock Input
		input  wire        main_reset_reset,     //    main_reset.reset
		input  wire [23:0] axi4s_vid_in_tdata,   //  axi4s_vid_in.tdata
		input  wire        axi4s_vid_in_tvalid,  //              .tvalid
		output wire        axi4s_vid_in_tready,  //              .tready
		input  wire        axi4s_vid_in_tlast,   //              .tlast
		input  wire [2:0]  axi4s_vid_in_tuser,   //              .tuser
		output wire [23:0] axi4s_vid_out_tdata,  // axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid, //              .tvalid
		input  wire        axi4s_vid_out_tready, //              .tready
		output wire        axi4s_vid_out_tlast,  //              .tlast
		output wire [2:0]  axi4s_vid_out_tuser   //              .tuser
	);

	wire         main_rst_bridge_out_reset_reset;  // main_rst_bridge:out_rst -> [algo_comp:rst, iib:rst, oib:rst, scheduler:rst]
	wire         iib_axi_st_data_out_tvalid;       // iib:axi_st_data_out_tvalid -> algo_comp:axi_st_data_in_tvalid
	wire   [2:0] iib_axi_st_data_out_tuser;        // iib:axi_st_data_out_tuser -> algo_comp:axi_st_data_in_tuser
	wire         iib_axi_st_data_out_tready;       // algo_comp:axi_st_data_in_tready -> iib:axi_st_data_out_tready
	wire  [23:0] iib_axi_st_data_out_tdata;        // iib:axi_st_data_out_tdata -> algo_comp:axi_st_data_in_tdata
	wire         iib_axi_st_data_out_tlast;        // iib:axi_st_data_out_tlast -> algo_comp:axi_st_data_in_tlast
	wire         algo_comp_axi_st_data_out_tvalid; // algo_comp:axi_st_data_out_tvalid -> oib:axi_st_data_in_tvalid
	wire   [2:0] algo_comp_axi_st_data_out_tuser;  // algo_comp:axi_st_data_out_tuser -> oib:axi_st_data_in_tuser
	wire         algo_comp_axi_st_data_out_tready; // oib:axi_st_data_in_tready -> algo_comp:axi_st_data_out_tready
	wire  [23:0] algo_comp_axi_st_data_out_tdata;  // algo_comp:axi_st_data_out_tdata -> oib:axi_st_data_in_tdata
	wire         algo_comp_axi_st_data_out_tlast;  // algo_comp:axi_st_data_out_tlast -> oib:axi_st_data_in_tlast
	wire         scheduler_axi4s_cmd_out_tvalid;   // scheduler:axi4s_cmd_out_tvalid -> algo_comp:axi_st_cmd_tvalid
	wire         scheduler_axi4s_cmd_out_tready;   // algo_comp:axi_st_cmd_tready -> scheduler:axi4s_cmd_out_tready
	wire  [39:0] scheduler_axi4s_cmd_out_tdata;    // scheduler:axi4s_cmd_out_tdata -> algo_comp:axi_st_cmd_tdata
	wire         iib_axi_st_ctrl_out_tvalid;       // iib:axi_st_ctrl_out_tvalid -> scheduler:axi4s_ctrl_in_tvalid
	wire   [1:0] iib_axi_st_ctrl_out_tuser;        // iib:axi_st_ctrl_out_tuser -> scheduler:axi4s_ctrl_in_tuser
	wire         iib_axi_st_ctrl_out_tready;       // scheduler:axi4s_ctrl_in_tready -> iib:axi_st_ctrl_out_tready
	wire  [15:0] iib_axi_st_ctrl_out_tdata;        // iib:axi_st_ctrl_out_tdata -> scheduler:axi4s_ctrl_in_tdata
	wire         iib_axi_st_ctrl_out_tlast;        // iib:axi_st_ctrl_out_tlast -> scheduler:axi4s_ctrl_in_tlast
	wire         scheduler_axi4s_ctrl_out_tvalid;  // scheduler:axi4s_ctrl_out_tvalid -> oib:axi_st_ctrl_in_tvalid
	wire   [1:0] scheduler_axi4s_ctrl_out_tuser;   // scheduler:axi4s_ctrl_out_tuser -> oib:axi_st_ctrl_in_tuser
	wire         scheduler_axi4s_ctrl_out_tready;  // oib:axi_st_ctrl_in_tready -> scheduler:axi4s_ctrl_out_tready
	wire  [15:0] scheduler_axi4s_ctrl_out_tdata;   // scheduler:axi4s_ctrl_out_tdata -> oib:axi_st_ctrl_in_tdata
	wire         scheduler_axi4s_ctrl_out_tlast;   // scheduler:axi4s_ctrl_out_tlast -> oib:axi_st_ctrl_in_tlast

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (P_UPDATE_CMD_SUPPORTED != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					p_update_cmd_supported_check ( .error(1'b1) );
		end
		if (P_CORE_CTRL_ID != 0)
		begin
		// synthesis translate_off
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
		// synthesis translate_on
			instantiated_with_wrong_parameters_error_see_comment_above
					p_core_ctrl_id_check ( .error(1'b1) );
		end
	endgenerate

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_csc_algo_comp #(
		.BPS_IN                  (8),
		.BPS_OUT                 (8),
		.PIXELS_IN_PARALLEL      (1),
		.PIPELINE_READY          (0),
		.DEVICE_FAMILY           ("Cyclone 10 GX"),
		.EXTERNAL_MODE           (0),
		.MOVE_BINARY_POINT_RIGHT (0),
		.ROUNDING_METHOD         ("ROUND_HALF_UP"),
		.RUNTIME_CONTROL         (0),
		.COEFF_SIGNED            (1),
		.COEFF_INTEGER_BITS      (2),
		.COEFF_FRACTION_BITS     (8),
		.SUMMAND_SIGNED          (1),
		.SUMMAND_INTEGER_BITS    (9),
		.SUMMAND_FRACTION_BITS   (8),
		.COEFF_A0                (541),
		.COEFF_A1                (-55),
		.COEFF_A2                (0),
		.COEFF_B0                (298),
		.COEFF_B1                (298),
		.COEFF_B2                (298),
		.COEFF_C0                (0),
		.COEFF_C1                (-137),
		.COEFF_C2                (459),
		.COEFF_S0                (-74072),
		.COEFF_S1                (19710),
		.COEFF_S2                (-63521)
	) algo_comp (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (iib_axi_st_data_out_tdata),        //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (iib_axi_st_data_out_tvalid),       //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (iib_axi_st_data_out_tready),       //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (iib_axi_st_data_out_tlast),        //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (iib_axi_st_data_out_tuser),        //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (algo_comp_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (algo_comp_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (algo_comp_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (algo_comp_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (algo_comp_axi_st_data_out_tuser),  //  output,   width = 3,                .tuser
		.axi_st_cmd_tdata       (scheduler_axi4s_cmd_out_tdata),    //   input,  width = 40,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi4s_cmd_out_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi4s_cmd_out_tready)    //  output,   width = 1,                .tready
	);

	intel_vvp_input_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) iib (
		.clk                    (main_clock_clk),                  //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset), //   input,   width = 1,      main_reset.reset
		.axi_st_ccd_in_tdata    (axi4s_vid_in_tdata),              //   input,  width = 24,   axi_st_ccd_in.tdata
		.axi_st_ccd_in_tvalid   (axi4s_vid_in_tvalid),             //   input,   width = 1,                .tvalid
		.axi_st_ccd_in_tready   (axi4s_vid_in_tready),             //  output,   width = 1,                .tready
		.axi_st_ccd_in_tlast    (axi4s_vid_in_tlast),              //   input,   width = 1,                .tlast
		.axi_st_ccd_in_tuser    (axi4s_vid_in_tuser),              //   input,   width = 3,                .tuser
		.axi_st_ctrl_out_tdata  (iib_axi_st_ctrl_out_tdata),       //  output,  width = 16, axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid (iib_axi_st_ctrl_out_tvalid),      //  output,   width = 1,                .tvalid
		.axi_st_ctrl_out_tready (iib_axi_st_ctrl_out_tready),      //   input,   width = 1,                .tready
		.axi_st_ctrl_out_tlast  (iib_axi_st_ctrl_out_tlast),       //  output,   width = 1,                .tlast
		.axi_st_ctrl_out_tuser  (iib_axi_st_ctrl_out_tuser),       //  output,   width = 2,                .tuser
		.axi_st_data_out_tdata  (iib_axi_st_data_out_tdata),       //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (iib_axi_st_data_out_tvalid),      //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (iib_axi_st_data_out_tready),      //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (iib_axi_st_data_out_tlast),       //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (iib_axi_st_data_out_tuser)        //  output,   width = 3,                .tuser
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) oib (
		.clk                   (main_clock_clk),                   //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),  //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi4s_ctrl_out_tdata),   //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi4s_ctrl_out_tvalid),  //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi4s_ctrl_out_tready),  //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi4s_ctrl_out_tlast),   //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi4s_ctrl_out_tuser),   //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (algo_comp_axi_st_data_out_tdata),  //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (algo_comp_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (algo_comp_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (algo_comp_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (algo_comp_axi_st_data_out_tuser),  //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),              //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),             //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),             //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),              //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)               //  output,   width = 3,               .tuser
	);

	intel_vvp_csc_scheduler #(
		.EXTERNAL_MODE          (0),
		.RUNTIME_CONTROL        (0),
		.ENABLE_DEBUG           (0),
		.P_UPDATE_CMD_SUPPORTED (0),
		.P_CORE_CTRL_ID         (0),
		.BPS_OUT                (8),
		.PIPELINE_READY         (0),
		.OUTPUT_COLORSPACE      (0)
	) scheduler (
		.clk                               (main_clock_clk),                       //   input,   width = 1,     main_clock.clk
		.rst                               (main_rst_bridge_out_reset_reset),      //   input,   width = 1,     main_reset.reset
		.axi4s_ctrl_in_tdata               (iib_axi_st_ctrl_out_tdata),            //   input,  width = 16,  axi4s_ctrl_in.tdata
		.axi4s_ctrl_in_tvalid              (iib_axi_st_ctrl_out_tvalid),           //   input,   width = 1,               .tvalid
		.axi4s_ctrl_in_tready              (iib_axi_st_ctrl_out_tready),           //  output,   width = 1,               .tready
		.axi4s_ctrl_in_tlast               (iib_axi_st_ctrl_out_tlast),            //   input,   width = 1,               .tlast
		.axi4s_ctrl_in_tuser               (iib_axi_st_ctrl_out_tuser),            //   input,   width = 2,               .tuser
		.axi4s_ctrl_out_tdata              (scheduler_axi4s_ctrl_out_tdata),       //  output,  width = 16, axi4s_ctrl_out.tdata
		.axi4s_ctrl_out_tvalid             (scheduler_axi4s_ctrl_out_tvalid),      //  output,   width = 1,               .tvalid
		.axi4s_ctrl_out_tready             (scheduler_axi4s_ctrl_out_tready),      //   input,   width = 1,               .tready
		.axi4s_ctrl_out_tlast              (scheduler_axi4s_ctrl_out_tlast),       //  output,   width = 1,               .tlast
		.axi4s_ctrl_out_tuser              (scheduler_axi4s_ctrl_out_tuser),       //  output,   width = 2,               .tuser
		.axi4s_cmd_out_tdata               (scheduler_axi4s_cmd_out_tdata),        //  output,  width = 40,  axi4s_cmd_out.tdata
		.axi4s_cmd_out_tvalid              (scheduler_axi4s_cmd_out_tvalid),       //  output,   width = 1,               .tvalid
		.axi4s_cmd_out_tready              (scheduler_axi4s_cmd_out_tready),       //   input,   width = 1,               .tready
		.av_mm_control_agent_address       (5'b00000),                             // (terminated),                             
		.av_mm_control_agent_write         (1'b0),                                 // (terminated),                             
		.av_mm_control_agent_byteenable    (4'b0000),                              // (terminated),                             
		.av_mm_control_agent_writedata     (32'b00000000000000000000000000000000), // (terminated),                             
		.av_mm_control_agent_read          (1'b0),                                 // (terminated),                             
		.av_mm_control_agent_readdata      (),                                     // (terminated),                             
		.av_mm_control_agent_readdatavalid (),                                     // (terminated),                             
		.av_mm_control_agent_waitrequest   ()                                      // (terminated),                             
	);

endmodule
