// Auto-generated by image_viewer.py — do not edit manually

parameter TPG_WIDTH      = 32;
parameter TPG_HEIGHT     = 32;
parameter CLIPPER_TOP    = 4;
parameter CLIPPER_BOTTOM = 4;
parameter CLIPPER_LEFT   = 4;
parameter CLIPPER_RIGHT  = 4;
parameter SCALER_WIDTH   = 16;
parameter SCALER_HEIGHT  = 16;
