// Auto-generated Configuration Header

parameter DEBUG_MODE      = 0;
parameter INPUT_SEL       = 0;
parameter TPG_WIDTH       = 32;
parameter TPG_HEIGHT      = 32;
parameter CLIPPER_TOP     = 4;
parameter CLIPPER_BOTTOM  = 4;
parameter CLIPPER_LEFT    = 4;
parameter CLIPPER_RIGHT   = 4;
parameter SCALER_WIDTH    = 64;
parameter SCALER_HEIGHT   = 64;
parameter TPG_COLORSPACE  = 1;
parameter VID_PLANES      = 2;
parameter PIP_ENABLE      = 1;
parameter PIP_BG_COLOR    = 1;
parameter PIP_BG_W        = 80;
parameter PIP_BG_H        = 80;
parameter PIP_H_OFF       = 8;
parameter PIP_V_OFF       = 14;
