// Auto-generated Configuration Header

parameter DEBUG_MODE      = 0;
parameter INPUT_SEL       = 0;
parameter TPG_WIDTH       = 32;
parameter TPG_HEIGHT      = 32;
parameter CLIPPER_TOP     = 4;
parameter CLIPPER_BOTTOM  = 4;
parameter CLIPPER_LEFT    = 5;
parameter CLIPPER_RIGHT   = 3;
parameter SCALER_WIDTH    = 32;
parameter SCALER_HEIGHT   = 32;
parameter TPG_COLORSPACE  = 3;
parameter VID_PLANES      = 2;
parameter PIP_ENABLE      = 0;
parameter PIP_BG_COLOR    = 2;
parameter PIP_BG_W        = 1280;
parameter PIP_BG_H        = 960;
parameter PIP_H_OFF       = 624;
parameter PIP_V_OFF       = 464;
