// pipeline_intel_vvp_crs_0_intel_vvp_crs_v_2451_zxafysy.v

// This file was auto-generated from intel_vvp_crs_v_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module pipeline_intel_vvp_crs_0_intel_vvp_crs_v_2451_zxafysy (
		input  wire        main_clock_clk,         //      main_clock.clk,   Clock Input
		input  wire        main_reset_reset,       //      main_reset.reset
		input  wire [39:0] axi_st_cmd_tdata,       //      axi_st_cmd.tdata
		input  wire        axi_st_cmd_tvalid,      //                .tvalid
		output wire        axi_st_cmd_tready,      //                .tready
		output wire [23:0] axi_st_data_out_tdata,  // axi_st_data_out.tdata
		output wire        axi_st_data_out_tvalid, //                .tvalid
		input  wire        axi_st_data_out_tready, //                .tready
		output wire        axi_st_data_out_tlast,  //                .tlast
		output wire [2:0]  axi_st_data_out_tuser,  //                .tuser
		input  wire [71:0] axi_st_data_in_tdata,   //  axi_st_data_in.tdata
		input  wire        axi_st_data_in_tvalid,  //                .tvalid
		output wire        axi_st_data_in_tready,  //                .tready
		input  wire        axi_st_data_in_tlast,   //                .tlast
		input  wire [8:0]  axi_st_data_in_tuser    //                .tuser
	);

	wire          main_rst_bridge_out_reset_reset;      // main_rst_bridge:out_rst -> [down_core:rst, down_pip_in:rst, down_pip_out:rst, down_select:rst, in_demux:rst, out_clip:rst, out_mux:rst, pass_pip_conv:rst, pass_select:rst, scheduler:rst, up_cols_conv:rst, up_core:rst, up_pip_in:rst, up_pip_out:rst, up_select:rst]
	wire          scheduler_axi_st_demux_cmd_tvalid;    // scheduler:axi_st_demux_cmd_tvalid -> in_demux:axi_st_cmd_tvalid
	wire          scheduler_axi_st_demux_cmd_tready;    // in_demux:axi_st_cmd_tready -> scheduler:axi_st_demux_cmd_tready
	wire    [7:0] scheduler_axi_st_demux_cmd_tdata;     // scheduler:axi_st_demux_cmd_tdata -> in_demux:axi_st_cmd_tdata
	wire          scheduler_axi_st_mux_cmd_tvalid;      // scheduler:axi_st_mux_cmd_tvalid -> out_mux:axi_st_cmd_tvalid
	wire          scheduler_axi_st_mux_cmd_tready;      // out_mux:axi_st_cmd_tready -> scheduler:axi_st_mux_cmd_tready
	wire    [7:0] scheduler_axi_st_mux_cmd_tdata;       // scheduler:axi_st_mux_cmd_tdata -> out_mux:axi_st_cmd_tdata
	wire          scheduler_axi_st_up_cmd_tvalid;       // scheduler:axi_st_up_cmd_tvalid -> up_core:axi_st_cmd_tvalid
	wire          scheduler_axi_st_up_cmd_tready;       // up_core:axi_st_cmd_tready -> scheduler:axi_st_up_cmd_tready
	wire   [15:0] scheduler_axi_st_up_cmd_tdata;        // scheduler:axi_st_up_cmd_tdata -> up_core:axi_st_cmd_tdata
	wire          scheduler_axi_st_down_cmd_tvalid;     // scheduler:axi_st_down_cmd_tvalid -> down_core:axi_st_cmd_tvalid
	wire          scheduler_axi_st_down_cmd_tready;     // down_core:axi_st_cmd_tready -> scheduler:axi_st_down_cmd_tready
	wire   [15:0] scheduler_axi_st_down_cmd_tdata;      // scheduler:axi_st_down_cmd_tdata -> down_core:axi_st_cmd_tdata
	wire          scheduler_axi_st_clp_cmd_tvalid;      // scheduler:axi_st_clp_cmd_tvalid -> out_clip:axi_st_cmd_tvalid
	wire          scheduler_axi_st_clp_cmd_tready;      // out_clip:axi_st_cmd_tready -> scheduler:axi_st_clp_cmd_tready
	wire   [15:0] scheduler_axi_st_clp_cmd_tdata;       // scheduler:axi_st_clp_cmd_tdata -> out_clip:axi_st_cmd_tdata
	wire          up_select_axi_st_data_out_tvalid;     // up_select:axi_st_data_out_tvalid -> up_pip_in:axi_st_data_in_tvalid
	wire    [8:0] up_select_axi_st_data_out_tuser;      // up_select:axi_st_data_out_tuser -> up_pip_in:axi_st_data_in_tuser
	wire          up_select_axi_st_data_out_tready;     // up_pip_in:axi_st_data_in_tready -> up_select:axi_st_data_out_tready
	wire   [71:0] up_select_axi_st_data_out_tdata;      // up_select:axi_st_data_out_tdata -> up_pip_in:axi_st_data_in_tdata
	wire          up_select_axi_st_data_out_tlast;      // up_select:axi_st_data_out_tlast -> up_pip_in:axi_st_data_in_tlast
	wire          up_pip_in_axi_st_data_out_tvalid;     // up_pip_in:axi_st_data_out_tvalid -> up_core:axi_st_data_in_tvalid
	wire    [8:0] up_pip_in_axi_st_data_out_tuser;      // up_pip_in:axi_st_data_out_tuser -> up_core:axi_st_data_in_tuser
	wire          up_pip_in_axi_st_data_out_tready;     // up_core:axi_st_data_in_tready -> up_pip_in:axi_st_data_out_tready
	wire   [71:0] up_pip_in_axi_st_data_out_tdata;      // up_pip_in:axi_st_data_out_tdata -> up_core:axi_st_data_in_tdata
	wire          up_pip_in_axi_st_data_out_tlast;      // up_pip_in:axi_st_data_out_tlast -> up_core:axi_st_data_in_tlast
	wire          up_core_axi_st_data_out_tvalid;       // up_core:axi_st_data_out_tvalid -> up_pip_out:axi_st_data_in_tvalid
	wire    [3:0] up_core_axi_st_data_out_tuser;        // up_core:axi_st_data_out_tuser -> up_pip_out:axi_st_data_in_tuser
	wire          up_core_axi_st_data_out_tready;       // up_pip_out:axi_st_data_in_tready -> up_core:axi_st_data_out_tready
	wire   [31:0] up_core_axi_st_data_out_tdata;        // up_core:axi_st_data_out_tdata -> up_pip_out:axi_st_data_in_tdata
	wire          up_core_axi_st_data_out_tlast;        // up_core:axi_st_data_out_tlast -> up_pip_out:axi_st_data_in_tlast
	wire          up_pip_out_axi_st_data_out_tvalid;    // up_pip_out:axi_st_data_out_tvalid -> up_cols_conv:axi_st_data_in_tvalid
	wire    [1:0] up_pip_out_axi_st_data_out_tuser;     // up_pip_out:axi_st_data_out_tuser -> up_cols_conv:axi_st_data_in_tuser
	wire          up_pip_out_axi_st_data_out_tready;    // up_cols_conv:axi_st_data_in_tready -> up_pip_out:axi_st_data_out_tready
	wire   [15:0] up_pip_out_axi_st_data_out_tdata;     // up_pip_out:axi_st_data_out_tdata -> up_cols_conv:axi_st_data_in_tdata
	wire          up_pip_out_axi_st_data_out_tlast;     // up_pip_out:axi_st_data_out_tlast -> up_cols_conv:axi_st_data_in_tlast
	wire          down_select_axi_st_data_out_tvalid;   // down_select:axi_st_data_out_tvalid -> down_pip_in:axi_st_data_in_tvalid
	wire    [3:0] down_select_axi_st_data_out_tuser;    // down_select:axi_st_data_out_tuser -> down_pip_in:axi_st_data_in_tuser
	wire          down_select_axi_st_data_out_tready;   // down_pip_in:axi_st_data_in_tready -> down_select:axi_st_data_out_tready
	wire   [31:0] down_select_axi_st_data_out_tdata;    // down_select:axi_st_data_out_tdata -> down_pip_in:axi_st_data_in_tdata
	wire          down_select_axi_st_data_out_tlast;    // down_select:axi_st_data_out_tlast -> down_pip_in:axi_st_data_in_tlast
	wire          down_pip_in_axi_st_data_out_tvalid;   // down_pip_in:axi_st_data_out_tvalid -> down_core:axi_st_data_in_tvalid
	wire    [7:0] down_pip_in_axi_st_data_out_tuser;    // down_pip_in:axi_st_data_out_tuser -> down_core:axi_st_data_in_tuser
	wire          down_pip_in_axi_st_data_out_tready;   // down_core:axi_st_data_in_tready -> down_pip_in:axi_st_data_out_tready
	wire   [63:0] down_pip_in_axi_st_data_out_tdata;    // down_pip_in:axi_st_data_out_tdata -> down_core:axi_st_data_in_tdata
	wire          down_pip_in_axi_st_data_out_tlast;    // down_pip_in:axi_st_data_out_tlast -> down_core:axi_st_data_in_tlast
	wire          down_core_axi_st_data_out_tvalid;     // down_core:axi_st_data_out_tvalid -> down_pip_out:axi_st_data_in_tvalid
	wire    [2:0] down_core_axi_st_data_out_tuser;      // down_core:axi_st_data_out_tuser -> down_pip_out:axi_st_data_in_tuser
	wire          down_core_axi_st_data_out_tready;     // down_pip_out:axi_st_data_in_tready -> down_core:axi_st_data_out_tready
	wire   [23:0] down_core_axi_st_data_out_tdata;      // down_core:axi_st_data_out_tdata -> down_pip_out:axi_st_data_in_tdata
	wire          down_core_axi_st_data_out_tlast;      // down_core:axi_st_data_out_tlast -> down_pip_out:axi_st_data_in_tlast
	wire          pass_select_axi_st_data_out_tvalid;   // pass_select:axi_st_data_out_tvalid -> pass_pip_conv:axi_st_data_in_tvalid
	wire    [2:0] pass_select_axi_st_data_out_tuser;    // pass_select:axi_st_data_out_tuser -> pass_pip_conv:axi_st_data_in_tuser
	wire          pass_select_axi_st_data_out_tready;   // pass_pip_conv:axi_st_data_in_tready -> pass_select:axi_st_data_out_tready
	wire   [23:0] pass_select_axi_st_data_out_tdata;    // pass_select:axi_st_data_out_tdata -> pass_pip_conv:axi_st_data_in_tdata
	wire          pass_select_axi_st_data_out_tlast;    // pass_select:axi_st_data_out_tlast -> pass_pip_conv:axi_st_data_in_tlast
	wire          out_mux_axi_st_dout_tvalid;           // out_mux:axi_st_dout_tvalid -> out_clip:axi_st_data_in_tvalid
	wire    [2:0] out_mux_axi_st_dout_tuser;            // out_mux:axi_st_dout_tuser -> out_clip:axi_st_data_in_tuser
	wire          out_mux_axi_st_dout_tready;           // out_clip:axi_st_data_in_tready -> out_mux:axi_st_dout_tready
	wire   [23:0] out_mux_axi_st_dout_tdata;            // out_mux:axi_st_dout_tdata -> out_clip:axi_st_data_in_tdata
	wire          out_mux_axi_st_dout_tlast;            // out_mux:axi_st_dout_tlast -> out_clip:axi_st_data_in_tlast
	wire          in_demux_axi_st_dout_0_tvalid;        // in_demux:axi_st_dout_0_tvalid -> pass_select:axi_st_data_in_tvalid
	wire    [8:0] in_demux_axi_st_dout_0_tuser;         // in_demux:axi_st_dout_0_tuser -> pass_select:axi_st_data_in_tuser
	wire          in_demux_axi_st_dout_0_tready;        // pass_select:axi_st_data_in_tready -> in_demux:axi_st_dout_0_tready
	wire   [71:0] in_demux_axi_st_dout_0_tdata;         // in_demux:axi_st_dout_0_tdata -> pass_select:axi_st_data_in_tdata
	wire          in_demux_axi_st_dout_0_tlast;         // in_demux:axi_st_dout_0_tlast -> pass_select:axi_st_data_in_tlast
	wire          pass_pip_conv_axi_st_data_out_tvalid; // pass_pip_conv:axi_st_data_out_tvalid -> out_mux:axi_st_din_0_tvalid
	wire    [2:0] pass_pip_conv_axi_st_data_out_tuser;  // pass_pip_conv:axi_st_data_out_tuser -> out_mux:axi_st_din_0_tuser
	wire          pass_pip_conv_axi_st_data_out_tready; // out_mux:axi_st_din_0_tready -> pass_pip_conv:axi_st_data_out_tready
	wire   [23:0] pass_pip_conv_axi_st_data_out_tdata;  // pass_pip_conv:axi_st_data_out_tdata -> out_mux:axi_st_din_0_tdata
	wire          pass_pip_conv_axi_st_data_out_tlast;  // pass_pip_conv:axi_st_data_out_tlast -> out_mux:axi_st_din_0_tlast
	wire          in_demux_axi_st_dout_1_tvalid;        // in_demux:axi_st_dout_1_tvalid -> up_select:axi_st_data_in_tvalid
	wire    [8:0] in_demux_axi_st_dout_1_tuser;         // in_demux:axi_st_dout_1_tuser -> up_select:axi_st_data_in_tuser
	wire          in_demux_axi_st_dout_1_tready;        // up_select:axi_st_data_in_tready -> in_demux:axi_st_dout_1_tready
	wire   [71:0] in_demux_axi_st_dout_1_tdata;         // in_demux:axi_st_dout_1_tdata -> up_select:axi_st_data_in_tdata
	wire          in_demux_axi_st_dout_1_tlast;         // in_demux:axi_st_dout_1_tlast -> up_select:axi_st_data_in_tlast
	wire          up_cols_conv_axi_st_data_out_tvalid;  // up_cols_conv:axi_st_data_out_tvalid -> out_mux:axi_st_din_1_tvalid
	wire    [2:0] up_cols_conv_axi_st_data_out_tuser;   // up_cols_conv:axi_st_data_out_tuser -> out_mux:axi_st_din_1_tuser
	wire          up_cols_conv_axi_st_data_out_tready;  // out_mux:axi_st_din_1_tready -> up_cols_conv:axi_st_data_out_tready
	wire   [23:0] up_cols_conv_axi_st_data_out_tdata;   // up_cols_conv:axi_st_data_out_tdata -> out_mux:axi_st_din_1_tdata
	wire          up_cols_conv_axi_st_data_out_tlast;   // up_cols_conv:axi_st_data_out_tlast -> out_mux:axi_st_din_1_tlast
	wire          in_demux_axi_st_dout_2_tvalid;        // in_demux:axi_st_dout_2_tvalid -> down_select:axi_st_data_in_tvalid
	wire    [8:0] in_demux_axi_st_dout_2_tuser;         // in_demux:axi_st_dout_2_tuser -> down_select:axi_st_data_in_tuser
	wire          in_demux_axi_st_dout_2_tready;        // down_select:axi_st_data_in_tready -> in_demux:axi_st_dout_2_tready
	wire   [71:0] in_demux_axi_st_dout_2_tdata;         // in_demux:axi_st_dout_2_tdata -> down_select:axi_st_data_in_tdata
	wire          in_demux_axi_st_dout_2_tlast;         // in_demux:axi_st_dout_2_tlast -> down_select:axi_st_data_in_tlast
	wire          down_pip_out_axi_st_data_out_tvalid;  // down_pip_out:axi_st_data_out_tvalid -> out_mux:axi_st_din_2_tvalid
	wire    [2:0] down_pip_out_axi_st_data_out_tuser;   // down_pip_out:axi_st_data_out_tuser -> out_mux:axi_st_din_2_tuser
	wire          down_pip_out_axi_st_data_out_tready;  // out_mux:axi_st_din_2_tready -> down_pip_out:axi_st_data_out_tready
	wire   [23:0] down_pip_out_axi_st_data_out_tdata;   // down_pip_out:axi_st_data_out_tdata -> out_mux:axi_st_din_2_tdata
	wire          down_pip_out_axi_st_data_out_tlast;   // down_pip_out:axi_st_data_out_tlast -> out_mux:axi_st_din_2_tlast
	wire  [215:0] in_demux_axi_st_dout_tdata;           // port fragment
	wire    [2:0] in_demux_axi_st_dout_tvalid;          // port fragment
	wire    [2:0] in_demux_axi_st_dout_tlast;           // port fragment
	wire   [26:0] in_demux_axi_st_dout_tuser;           // port fragment
	wire    [2:0] out_mux_axi_st_din_tready;            // port fragment

	intel_vvp_reset_bridge main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_crs_v_cmd_gen #(
		.USE_UP_CORE     (1),
		.USE_DOWN_CORE   (1),
		.USE_PASSTHROUGH (1)
	) scheduler (
		.clk                     (main_clock_clk),                    //   input,   width = 1,       main_clock.clk
		.rst                     (main_rst_bridge_out_reset_reset),   //   input,   width = 1,       main_reset.reset
		.axi_st_in_cmd_tdata     (axi_st_cmd_tdata),                  //   input,  width = 40,    axi_st_in_cmd.tdata
		.axi_st_in_cmd_tvalid    (axi_st_cmd_tvalid),                 //   input,   width = 1,                 .tvalid
		.axi_st_in_cmd_tready    (axi_st_cmd_tready),                 //  output,   width = 1,                 .tready
		.axi_st_up_cmd_tdata     (scheduler_axi_st_up_cmd_tdata),     //  output,  width = 16,    axi_st_up_cmd.tdata
		.axi_st_up_cmd_tvalid    (scheduler_axi_st_up_cmd_tvalid),    //  output,   width = 1,                 .tvalid
		.axi_st_up_cmd_tready    (scheduler_axi_st_up_cmd_tready),    //   input,   width = 1,                 .tready
		.axi_st_down_cmd_tdata   (scheduler_axi_st_down_cmd_tdata),   //  output,  width = 16,  axi_st_down_cmd.tdata
		.axi_st_down_cmd_tvalid  (scheduler_axi_st_down_cmd_tvalid),  //  output,   width = 1,                 .tvalid
		.axi_st_down_cmd_tready  (scheduler_axi_st_down_cmd_tready),  //   input,   width = 1,                 .tready
		.axi_st_demux_cmd_tdata  (scheduler_axi_st_demux_cmd_tdata),  //  output,   width = 8, axi_st_demux_cmd.tdata
		.axi_st_demux_cmd_tvalid (scheduler_axi_st_demux_cmd_tvalid), //  output,   width = 1,                 .tvalid
		.axi_st_demux_cmd_tready (scheduler_axi_st_demux_cmd_tready), //   input,   width = 1,                 .tready
		.axi_st_mux_cmd_tdata    (scheduler_axi_st_mux_cmd_tdata),    //  output,   width = 8,   axi_st_mux_cmd.tdata
		.axi_st_mux_cmd_tvalid   (scheduler_axi_st_mux_cmd_tvalid),   //  output,   width = 1,                 .tvalid
		.axi_st_mux_cmd_tready   (scheduler_axi_st_mux_cmd_tready),   //   input,   width = 1,                 .tready
		.axi_st_clp_cmd_tdata    (scheduler_axi_st_clp_cmd_tdata),    //  output,  width = 16,   axi_st_clp_cmd.tdata
		.axi_st_clp_cmd_tvalid   (scheduler_axi_st_clp_cmd_tvalid),   //  output,   width = 1,                 .tvalid
		.axi_st_clp_cmd_tready   (scheduler_axi_st_clp_cmd_tready)    //   input,   width = 1,                 .tready
	);

	intel_vvp_pkt_clip #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0)
	) out_clip (
		.clk                    (main_clock_clk),                  //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset), //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_clp_cmd_tdata),  //   input,  width = 16,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_clp_cmd_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_clp_cmd_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (out_mux_axi_st_dout_tdata),       //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (out_mux_axi_st_dout_tvalid),      //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (out_mux_axi_st_dout_tready),      //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (out_mux_axi_st_dout_tlast),       //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (out_mux_axi_st_dout_tuser),       //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (axi_st_data_out_tdata),           //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (axi_st_data_out_tvalid),          //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (axi_st_data_out_tready),          //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (axi_st_data_out_tlast),           //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (axi_st_data_out_tuser)            //  output,   width = 3,                .tuser
	);

	intel_vvp_pkt_demux #(
		.NUM_OUTPUTS    (3),
		.PIPELINE_READY (0),
		.DATA_WIDTH     (72)
	) in_demux (
		.clk                (main_clock_clk),                                                                                            //   input,    width = 1,    main_clock.clk
		.rst                (main_rst_bridge_out_reset_reset),                                                                           //   input,    width = 1,    main_reset.reset
		.axi_st_cmd_tdata   (scheduler_axi_st_demux_cmd_tdata),                                                                          //   input,    width = 8,    axi_st_cmd.tdata
		.axi_st_cmd_tvalid  (scheduler_axi_st_demux_cmd_tvalid),                                                                         //   input,    width = 1,              .tvalid
		.axi_st_cmd_tready  (scheduler_axi_st_demux_cmd_tready),                                                                         //  output,    width = 1,              .tready
		.axi_st_din_tdata   (axi_st_data_in_tdata),                                                                                      //   input,   width = 72,    axi_st_din.tdata
		.axi_st_din_tvalid  (axi_st_data_in_tvalid),                                                                                     //   input,    width = 1,              .tvalid
		.axi_st_din_tready  (axi_st_data_in_tready),                                                                                     //  output,    width = 1,              .tready
		.axi_st_din_tlast   (axi_st_data_in_tlast),                                                                                      //   input,    width = 1,              .tlast
		.axi_st_din_tuser   (axi_st_data_in_tuser),                                                                                      //   input,    width = 9,              .tuser
		.axi_st_dout_tdata  ({in_demux_axi_st_dout_tdata[215:144],in_demux_axi_st_dout_tdata[143:72],in_demux_axi_st_dout_tdata[71:0]}), //  output,  width = 216, axi_st_dout_0.tdata
		.axi_st_dout_tvalid ({in_demux_axi_st_dout_tvalid[2],in_demux_axi_st_dout_tvalid[1],in_demux_axi_st_dout_tvalid[0]}),            //  output,    width = 3,              .tvalid
		.axi_st_dout_tready ({in_demux_axi_st_dout_2_tready,in_demux_axi_st_dout_1_tready,in_demux_axi_st_dout_0_tready}),               //   input,    width = 3,              .tready
		.axi_st_dout_tlast  ({in_demux_axi_st_dout_tlast[2],in_demux_axi_st_dout_tlast[1],in_demux_axi_st_dout_tlast[0]}),               //  output,    width = 3,              .tlast
		.axi_st_dout_tuser  ({in_demux_axi_st_dout_tuser[26:18],in_demux_axi_st_dout_tuser[17:9],in_demux_axi_st_dout_tuser[8:0]})       //  output,   width = 27,              .tuser
	);

	intel_vvp_pkt_mux #(
		.NUM_INPUTS     (3),
		.PIPELINE_READY (0),
		.DATA_WIDTH     (24)
	) out_mux (
		.clk                (main_clock_clk),                                                                                                                //   input,   width = 1,   main_clock.clk
		.rst                (main_rst_bridge_out_reset_reset),                                                                                               //   input,   width = 1,   main_reset.reset
		.axi_st_cmd_tdata   (scheduler_axi_st_mux_cmd_tdata),                                                                                                //   input,   width = 8,   axi_st_cmd.tdata
		.axi_st_cmd_tvalid  (scheduler_axi_st_mux_cmd_tvalid),                                                                                               //   input,   width = 1,             .tvalid
		.axi_st_cmd_tready  (scheduler_axi_st_mux_cmd_tready),                                                                                               //  output,   width = 1,             .tready
		.axi_st_din_tdata   ({down_pip_out_axi_st_data_out_tdata[23:0],up_cols_conv_axi_st_data_out_tdata[23:0],pass_pip_conv_axi_st_data_out_tdata[23:0]}), //   input,  width = 72, axi_st_din_0.tdata
		.axi_st_din_tvalid  ({down_pip_out_axi_st_data_out_tvalid,up_cols_conv_axi_st_data_out_tvalid,pass_pip_conv_axi_st_data_out_tvalid}),                //   input,   width = 3,             .tvalid
		.axi_st_din_tready  ({out_mux_axi_st_din_tready[2],out_mux_axi_st_din_tready[1],out_mux_axi_st_din_tready[0]}),                                      //  output,   width = 3,             .tready
		.axi_st_din_tlast   ({down_pip_out_axi_st_data_out_tlast,up_cols_conv_axi_st_data_out_tlast,pass_pip_conv_axi_st_data_out_tlast}),                   //   input,   width = 3,             .tlast
		.axi_st_din_tuser   ({down_pip_out_axi_st_data_out_tuser[2:0],up_cols_conv_axi_st_data_out_tuser[2:0],pass_pip_conv_axi_st_data_out_tuser[2:0]}),    //   input,   width = 9,             .tuser
		.axi_st_dout_tdata  (out_mux_axi_st_dout_tdata),                                                                                                     //  output,  width = 24,  axi_st_dout.tdata
		.axi_st_dout_tvalid (out_mux_axi_st_dout_tvalid),                                                                                                    //  output,   width = 1,             .tvalid
		.axi_st_dout_tready (out_mux_axi_st_dout_tready),                                                                                                    //   input,   width = 1,             .tready
		.axi_st_dout_tlast  (out_mux_axi_st_dout_tlast),                                                                                                     //  output,   width = 1,             .tlast
		.axi_st_dout_tuser  (out_mux_axi_st_dout_tuser)                                                                                                      //  output,   width = 3,             .tuser
	);

	intel_vvp_kernel_select #(
		.BPS                        (8),
		.PIXELS_IN_PARALLEL         (1),
		.NUMBER_OF_COLOR_PLANES_IN  (3),
		.NUMBER_OF_COLOR_PLANES_OUT (3),
		.NUM_LINES_IN               (3),
		.NUM_LINES_OUT              (3),
		.OFFSET_LINE                (0)
	) up_select (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (in_demux_axi_st_dout_1_tdata),     //   input,  width = 72,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (in_demux_axi_st_dout_1_tvalid),    //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (in_demux_axi_st_dout_1_tready),    //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (in_demux_axi_st_dout_1_tlast),     //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (in_demux_axi_st_dout_1_tuser),     //   input,   width = 9,                .tuser
		.axi_st_data_out_tdata  (up_select_axi_st_data_out_tdata),  //  output,  width = 72, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (up_select_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (up_select_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (up_select_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (up_select_axi_st_data_out_tuser)   //  output,   width = 9,                .tuser
	);

	intel_vvp_pip_conv_core #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (9),
		.PIXELS_IN_PARALLEL_IN  (1),
		.PIXELS_IN_PARALLEL_OUT (1),
		.PIPELINE_READY         (0)
	) up_pip_in (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (up_select_axi_st_data_out_tdata),  //   input,  width = 72,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (up_select_axi_st_data_out_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (up_select_axi_st_data_out_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (up_select_axi_st_data_out_tlast),  //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (up_select_axi_st_data_out_tuser),  //   input,   width = 9,                .tuser
		.axi_st_data_out_tdata  (up_pip_in_axi_st_data_out_tdata),  //  output,  width = 72, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (up_pip_in_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (up_pip_in_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (up_pip_in_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (up_pip_in_axi_st_data_out_tuser)   //  output,   width = 9,                .tuser
	);

	intel_vvp_crs_v_up_algo_comp #(
		.BPS                (8),
		.PIXELS_IN_PARALLEL (2),
		.ALGORITHM          ("NEAREST_NEIGHBOUR"),
		.CO_SITING          ("TOP"),
		.ENABLE_LUMA_ADAPT  (0),
		.PIPELINE_READY     (0),
		.DEVICE_FAMILY      ("Agilex 5")
	) up_core (
		.clk                    (main_clock_clk),                   //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),  //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_up_cmd_tdata),    //   input,  width = 16,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_up_cmd_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_up_cmd_tready),   //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (up_pip_in_axi_st_data_out_tdata),  //   input,  width = 72,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (up_pip_in_axi_st_data_out_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (up_pip_in_axi_st_data_out_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (up_pip_in_axi_st_data_out_tlast),  //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (up_pip_in_axi_st_data_out_tuser),  //   input,   width = 9,                .tuser
		.axi_st_data_out_tdata  (up_core_axi_st_data_out_tdata),    //  output,  width = 32, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (up_core_axi_st_data_out_tvalid),   //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (up_core_axi_st_data_out_tready),   //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (up_core_axi_st_data_out_tlast),    //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (up_core_axi_st_data_out_tuser)     //  output,   width = 4,                .tuser
	);

	intel_vvp_pip_conv_core #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (2),
		.PIXELS_IN_PARALLEL_IN  (2),
		.PIXELS_IN_PARALLEL_OUT (1),
		.PIPELINE_READY         (0)
	) up_pip_out (
		.clk                    (main_clock_clk),                    //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),   //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (up_core_axi_st_data_out_tdata),     //   input,  width = 32,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (up_core_axi_st_data_out_tvalid),    //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (up_core_axi_st_data_out_tready),    //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (up_core_axi_st_data_out_tlast),     //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (up_core_axi_st_data_out_tuser),     //   input,   width = 4,                .tuser
		.axi_st_data_out_tdata  (up_pip_out_axi_st_data_out_tdata),  //  output,  width = 16, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (up_pip_out_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (up_pip_out_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (up_pip_out_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (up_pip_out_axi_st_data_out_tuser)   //  output,   width = 2,                .tuser
	);

	intel_vvp_cpp_adapter #(
		.BPS                        (8),
		.NUMBER_OF_COLOR_PLANES_IN  (2),
		.NUMBER_OF_COLOR_PLANES_OUT (3),
		.PIXELS_IN_PARALLEL         (1)
	) up_cols_conv (
		.clk                    (main_clock_clk),                      //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),     //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (up_pip_out_axi_st_data_out_tdata),    //   input,  width = 16,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (up_pip_out_axi_st_data_out_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (up_pip_out_axi_st_data_out_tready),   //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (up_pip_out_axi_st_data_out_tlast),    //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (up_pip_out_axi_st_data_out_tuser),    //   input,   width = 2,                .tuser
		.axi_st_data_out_tdata  (up_cols_conv_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (up_cols_conv_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (up_cols_conv_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (up_cols_conv_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (up_cols_conv_axi_st_data_out_tuser)   //  output,   width = 3,                .tuser
	);

	intel_vvp_kernel_select #(
		.BPS                        (8),
		.PIXELS_IN_PARALLEL         (1),
		.NUMBER_OF_COLOR_PLANES_IN  (3),
		.NUMBER_OF_COLOR_PLANES_OUT (2),
		.NUM_LINES_IN               (3),
		.NUM_LINES_OUT              (2),
		.OFFSET_LINE                (1)
	) down_select (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (in_demux_axi_st_dout_2_tdata),       //   input,  width = 72,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (in_demux_axi_st_dout_2_tvalid),      //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (in_demux_axi_st_dout_2_tready),      //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (in_demux_axi_st_dout_2_tlast),       //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (in_demux_axi_st_dout_2_tuser),       //   input,   width = 9,                .tuser
		.axi_st_data_out_tdata  (down_select_axi_st_data_out_tdata),  //  output,  width = 32, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (down_select_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (down_select_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (down_select_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (down_select_axi_st_data_out_tuser)   //  output,   width = 4,                .tuser
	);

	intel_vvp_pip_conv_core #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (4),
		.PIXELS_IN_PARALLEL_IN  (1),
		.PIXELS_IN_PARALLEL_OUT (2),
		.PIPELINE_READY         (0)
	) down_pip_in (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (down_select_axi_st_data_out_tdata),  //   input,  width = 32,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (down_select_axi_st_data_out_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (down_select_axi_st_data_out_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (down_select_axi_st_data_out_tlast),  //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (down_select_axi_st_data_out_tuser),  //   input,   width = 4,                .tuser
		.axi_st_data_out_tdata  (down_pip_in_axi_st_data_out_tdata),  //  output,  width = 64, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (down_pip_in_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (down_pip_in_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (down_pip_in_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (down_pip_in_axi_st_data_out_tuser)   //  output,   width = 8,                .tuser
	);

	intel_vvp_crs_v_down_algo_comp #(
		.BPS                (8),
		.PIXELS_IN_PARALLEL (2),
		.ALGORITHM          ("NEAREST_NEIGHBOUR"),
		.CO_SITING          ("TOP"),
		.NO_BLANKING        (0),
		.PIPELINE_READY     (0)
	) down_core (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_down_cmd_tdata),    //   input,  width = 16,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_down_cmd_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_down_cmd_tready),   //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (down_pip_in_axi_st_data_out_tdata),  //   input,  width = 64,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (down_pip_in_axi_st_data_out_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (down_pip_in_axi_st_data_out_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (down_pip_in_axi_st_data_out_tlast),  //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (down_pip_in_axi_st_data_out_tuser),  //   input,   width = 8,                .tuser
		.axi_st_data_out_tdata  (down_core_axi_st_data_out_tdata),    //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (down_core_axi_st_data_out_tvalid),   //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (down_core_axi_st_data_out_tready),   //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (down_core_axi_st_data_out_tlast),    //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (down_core_axi_st_data_out_tuser)     //  output,   width = 3,                .tuser
	);

	intel_vvp_pip_conv_core #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL_IN  (1),
		.PIXELS_IN_PARALLEL_OUT (1),
		.PIPELINE_READY         (0)
	) down_pip_out (
		.clk                    (main_clock_clk),                      //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),     //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (down_core_axi_st_data_out_tdata),     //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (down_core_axi_st_data_out_tvalid),    //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (down_core_axi_st_data_out_tready),    //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (down_core_axi_st_data_out_tlast),     //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (down_core_axi_st_data_out_tuser),     //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (down_pip_out_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (down_pip_out_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (down_pip_out_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (down_pip_out_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (down_pip_out_axi_st_data_out_tuser)   //  output,   width = 3,                .tuser
	);

	intel_vvp_kernel_select #(
		.BPS                        (8),
		.PIXELS_IN_PARALLEL         (1),
		.NUMBER_OF_COLOR_PLANES_IN  (3),
		.NUMBER_OF_COLOR_PLANES_OUT (3),
		.NUM_LINES_IN               (3),
		.NUM_LINES_OUT              (1),
		.OFFSET_LINE                (2)
	) pass_select (
		.clk                    (main_clock_clk),                     //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (in_demux_axi_st_dout_0_tdata),       //   input,  width = 72,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (in_demux_axi_st_dout_0_tvalid),      //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (in_demux_axi_st_dout_0_tready),      //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (in_demux_axi_st_dout_0_tlast),       //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (in_demux_axi_st_dout_0_tuser),       //   input,   width = 9,                .tuser
		.axi_st_data_out_tdata  (pass_select_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (pass_select_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (pass_select_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (pass_select_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (pass_select_axi_st_data_out_tuser)   //  output,   width = 3,                .tuser
	);

	intel_vvp_pip_conv_core #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL_IN  (1),
		.PIXELS_IN_PARALLEL_OUT (1),
		.PIPELINE_READY         (0)
	) pass_pip_conv (
		.clk                    (main_clock_clk),                       //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),      //   input,   width = 1,      main_reset.reset
		.axi_st_data_in_tdata   (pass_select_axi_st_data_out_tdata),    //   input,  width = 24,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (pass_select_axi_st_data_out_tvalid),   //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (pass_select_axi_st_data_out_tready),   //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (pass_select_axi_st_data_out_tlast),    //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (pass_select_axi_st_data_out_tuser),    //   input,   width = 3,                .tuser
		.axi_st_data_out_tdata  (pass_pip_conv_axi_st_data_out_tdata),  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (pass_pip_conv_axi_st_data_out_tvalid), //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (pass_pip_conv_axi_st_data_out_tready), //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (pass_pip_conv_axi_st_data_out_tlast),  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (pass_pip_conv_axi_st_data_out_tuser)   //  output,   width = 3,                .tuser
	);

	assign down_pip_out_axi_st_data_out_tready = { out_mux_axi_st_din_tready[2] };

	assign in_demux_axi_st_dout_0_tdata = { in_demux_axi_st_dout_tdata[71:0] };

	assign in_demux_axi_st_dout_0_tlast = { in_demux_axi_st_dout_tlast[0] };

	assign in_demux_axi_st_dout_0_tuser = { in_demux_axi_st_dout_tuser[8:0] };

	assign in_demux_axi_st_dout_0_tvalid = { in_demux_axi_st_dout_tvalid[0] };

	assign in_demux_axi_st_dout_1_tdata = { in_demux_axi_st_dout_tdata[143:72] };

	assign in_demux_axi_st_dout_1_tlast = { in_demux_axi_st_dout_tlast[1] };

	assign in_demux_axi_st_dout_1_tuser = { in_demux_axi_st_dout_tuser[17:9] };

	assign in_demux_axi_st_dout_1_tvalid = { in_demux_axi_st_dout_tvalid[1] };

	assign in_demux_axi_st_dout_2_tdata = { in_demux_axi_st_dout_tdata[215:144] };

	assign in_demux_axi_st_dout_2_tlast = { in_demux_axi_st_dout_tlast[2] };

	assign in_demux_axi_st_dout_2_tuser = { in_demux_axi_st_dout_tuser[26:18] };

	assign in_demux_axi_st_dout_2_tvalid = { in_demux_axi_st_dout_tvalid[2] };

	assign pass_pip_conv_axi_st_data_out_tready = { out_mux_axi_st_din_tready[0] };

	assign up_cols_conv_axi_st_data_out_tready = { out_mux_axi_st_din_tready[1] };

endmodule
