// pipeline_intel_vvp_pipeline2_0_intel_vvp_scaler_h_macro_2451_3cz3gjy.v

// This file was auto-generated from intel_vvp_scaler_h_macro_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module pipeline_intel_vvp_pipeline2_0_intel_vvp_scaler_h_macro_2451_3cz3gjy (
		input  wire         main_clock_clk,         //      main_clock.clk,   Clock Input
		input  wire         main_reset_reset,       //      main_reset.reset
		input  wire [127:0] axi_st_cmd_tdata,       //      axi_st_cmd.tdata
		input  wire         axi_st_cmd_tvalid,      //                .tvalid
		output wire         axi_st_cmd_tready,      //                .tready
		input  wire [23:0]  axi_st_data_in_tdata,   //  axi_st_data_in.tdata
		input  wire         axi_st_data_in_tvalid,  //                .tvalid
		output wire         axi_st_data_in_tready,  //                .tready
		input  wire         axi_st_data_in_tlast,   //                .tlast
		input  wire [2:0]   axi_st_data_in_tuser,   //                .tuser
		output wire [23:0]  axi_st_data_out_tdata,  // axi_st_data_out.tdata
		output wire         axi_st_data_out_tvalid, //                .tvalid
		input  wire         axi_st_data_out_tready, //                .tready
		output wire         axi_st_data_out_tlast,  //                .tlast
		output wire [2:0]   axi_st_data_out_tuser   //                .tuser
	);

	wire          main_rst_bridge_out_reset_reset;              // main_rst_bridge:out_rst -> [chroma_algo_comp:rst, chroma_sp_down:rst, chroma_sp_up:rst, in_cmd:rst, in_split:rst, luma_algo_comp:rst, out_switch:rst]
	wire          in_cmd_axi_st_cmd_output_switch_tvalid;       // in_cmd:axi_st_cmd_output_switch_tvalid -> out_switch:axi_st_cmd_tvalid
	wire          in_cmd_axi_st_cmd_output_switch_tready;       // out_switch:axi_st_cmd_tready -> in_cmd:axi_st_cmd_output_switch_tready
	wire   [23:0] in_cmd_axi_st_cmd_output_switch_tdata;        // in_cmd:axi_st_cmd_output_switch_tdata -> out_switch:axi_st_cmd_tdata
	wire          in_cmd_axi_st_cmd_luma_core_tvalid;           // in_cmd:axi_st_cmd_luma_core_tvalid -> luma_algo_comp:axi_st_cmd_tvalid
	wire          in_cmd_axi_st_cmd_luma_core_tready;           // luma_algo_comp:axi_st_cmd_tready -> in_cmd:axi_st_cmd_luma_core_tready
	wire  [119:0] in_cmd_axi_st_cmd_luma_core_tdata;            // in_cmd:axi_st_cmd_luma_core_tdata -> luma_algo_comp:axi_st_cmd_tdata
	wire          in_split_axi_st_luma_out_tvalid;              // in_split:axi_st_luma_out_tvalid -> luma_algo_comp:axi_st_data_in_tvalid
	wire    [1:0] in_split_axi_st_luma_out_tuser;               // in_split:axi_st_luma_out_tuser -> luma_algo_comp:axi_st_data_in_tuser
	wire          in_split_axi_st_luma_out_tready;              // luma_algo_comp:axi_st_data_in_tready -> in_split:axi_st_luma_out_tready
	wire   [15:0] in_split_axi_st_luma_out_tdata;               // in_split:axi_st_luma_out_tdata -> luma_algo_comp:axi_st_data_in_tdata
	wire          in_split_axi_st_luma_out_tlast;               // in_split:axi_st_luma_out_tlast -> luma_algo_comp:axi_st_data_in_tlast
	wire          luma_algo_comp_axi_st_data_out_tvalid;        // luma_algo_comp:axi_st_data_out_tvalid -> out_switch:axi_st_luma_tvalid
	wire    [1:0] luma_algo_comp_axi_st_data_out_tuser;         // luma_algo_comp:axi_st_data_out_tuser -> out_switch:axi_st_luma_tuser
	wire          luma_algo_comp_axi_st_data_out_tready;        // out_switch:axi_st_luma_tready -> luma_algo_comp:axi_st_data_out_tready
	wire   [15:0] luma_algo_comp_axi_st_data_out_tdata;         // luma_algo_comp:axi_st_data_out_tdata -> out_switch:axi_st_luma_tdata
	wire          luma_algo_comp_axi_st_data_out_tlast;         // luma_algo_comp:axi_st_data_out_tlast -> out_switch:axi_st_luma_tlast
	wire          in_cmd_axi_st_cmd_chroma_core_tvalid;         // in_cmd:axi_st_cmd_chroma_core_tvalid -> chroma_algo_comp:axi_st_cmd_tvalid
	wire          in_cmd_axi_st_cmd_chroma_core_tready;         // chroma_algo_comp:axi_st_cmd_tready -> in_cmd:axi_st_cmd_chroma_core_tready
	wire  [119:0] in_cmd_axi_st_cmd_chroma_core_tdata;          // in_cmd:axi_st_cmd_chroma_core_tdata -> chroma_algo_comp:axi_st_cmd_tdata
	wire          in_cmd_axi_st_cmd_chroma_seq_par_up_tvalid;   // in_cmd:axi_st_cmd_chroma_seq_par_up_tvalid -> chroma_sp_up:axi_st_cmd_tvalid
	wire          in_cmd_axi_st_cmd_chroma_seq_par_up_tready;   // chroma_sp_up:axi_st_cmd_tready -> in_cmd:axi_st_cmd_chroma_seq_par_up_tready
	wire    [7:0] in_cmd_axi_st_cmd_chroma_seq_par_up_tdata;    // in_cmd:axi_st_cmd_chroma_seq_par_up_tdata -> chroma_sp_up:axi_st_cmd_tdata
	wire          in_cmd_axi_st_cmd_chroma_seq_par_down_tvalid; // in_cmd:axi_st_cmd_chroma_seq_par_down_tvalid -> chroma_sp_down:axi_st_cmd_tvalid
	wire          in_cmd_axi_st_cmd_chroma_seq_par_down_tready; // chroma_sp_down:axi_st_cmd_tready -> in_cmd:axi_st_cmd_chroma_seq_par_down_tready
	wire    [7:0] in_cmd_axi_st_cmd_chroma_seq_par_down_tdata;  // in_cmd:axi_st_cmd_chroma_seq_par_down_tdata -> chroma_sp_down:axi_st_cmd_tdata
	wire          in_split_axi_st_chroma_out_tvalid;            // in_split:axi_st_chroma_out_tvalid -> chroma_sp_up:axi_st_data_in_tvalid
	wire    [1:0] in_split_axi_st_chroma_out_tuser;             // in_split:axi_st_chroma_out_tuser -> chroma_sp_up:axi_st_data_in_tuser
	wire          in_split_axi_st_chroma_out_tready;            // chroma_sp_up:axi_st_data_in_tready -> in_split:axi_st_chroma_out_tready
	wire   [15:0] in_split_axi_st_chroma_out_tdata;             // in_split:axi_st_chroma_out_tdata -> chroma_sp_up:axi_st_data_in_tdata
	wire          in_split_axi_st_chroma_out_tlast;             // in_split:axi_st_chroma_out_tlast -> chroma_sp_up:axi_st_data_in_tlast
	wire          chroma_sp_up_axi_st_data_out_tvalid;          // chroma_sp_up:axi_st_data_out_tvalid -> chroma_algo_comp:axi_st_data_in_tvalid
	wire    [1:0] chroma_sp_up_axi_st_data_out_tuser;           // chroma_sp_up:axi_st_data_out_tuser -> chroma_algo_comp:axi_st_data_in_tuser
	wire          chroma_sp_up_axi_st_data_out_tready;          // chroma_algo_comp:axi_st_data_in_tready -> chroma_sp_up:axi_st_data_out_tready
	wire   [15:0] chroma_sp_up_axi_st_data_out_tdata;           // chroma_sp_up:axi_st_data_out_tdata -> chroma_algo_comp:axi_st_data_in_tdata
	wire          chroma_sp_up_axi_st_data_out_tlast;           // chroma_sp_up:axi_st_data_out_tlast -> chroma_algo_comp:axi_st_data_in_tlast
	wire          chroma_algo_comp_axi_st_data_out_tvalid;      // chroma_algo_comp:axi_st_data_out_tvalid -> chroma_sp_down:axi_st_data_in_tvalid
	wire    [1:0] chroma_algo_comp_axi_st_data_out_tuser;       // chroma_algo_comp:axi_st_data_out_tuser -> chroma_sp_down:axi_st_data_in_tuser
	wire          chroma_algo_comp_axi_st_data_out_tready;      // chroma_sp_down:axi_st_data_in_tready -> chroma_algo_comp:axi_st_data_out_tready
	wire   [15:0] chroma_algo_comp_axi_st_data_out_tdata;       // chroma_algo_comp:axi_st_data_out_tdata -> chroma_sp_down:axi_st_data_in_tdata
	wire          chroma_algo_comp_axi_st_data_out_tlast;       // chroma_algo_comp:axi_st_data_out_tlast -> chroma_sp_down:axi_st_data_in_tlast
	wire          chroma_sp_down_axi_st_data_out_tvalid;        // chroma_sp_down:axi_st_data_out_tvalid -> out_switch:axi_st_chroma_tvalid
	wire    [1:0] chroma_sp_down_axi_st_data_out_tuser;         // chroma_sp_down:axi_st_data_out_tuser -> out_switch:axi_st_chroma_tuser
	wire          chroma_sp_down_axi_st_data_out_tready;        // out_switch:axi_st_chroma_tready -> chroma_sp_down:axi_st_data_out_tready
	wire   [15:0] chroma_sp_down_axi_st_data_out_tdata;         // chroma_sp_down:axi_st_data_out_tdata -> out_switch:axi_st_chroma_tdata
	wire          chroma_sp_down_axi_st_data_out_tlast;         // chroma_sp_down:axi_st_data_out_tlast -> out_switch:axi_st_chroma_tlast

	intel_vvp_reset_bridge main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_horiz_scaler_cmd #(
		.ENABLE_444    (1),
		.ENABLE_422    (1),
		.ENABLE_420    (0),
		.HALF_RATE_420 (0)
	) in_cmd (
		.clk                                   (main_clock_clk),                               //   input,    width = 1,                     main_clock.clk
		.rst                                   (main_rst_bridge_out_reset_reset),              //   input,    width = 1,                     main_reset.reset
		.axi_st_cmd_in_tdata                   (axi_st_cmd_tdata),                             //   input,  width = 128,                  axi_st_cmd_in.tdata
		.axi_st_cmd_in_tvalid                  (axi_st_cmd_tvalid),                            //   input,    width = 1,                               .tvalid
		.axi_st_cmd_in_tready                  (axi_st_cmd_tready),                            //  output,    width = 1,                               .tready
		.axi_st_cmd_luma_core_tdata            (in_cmd_axi_st_cmd_luma_core_tdata),            //  output,  width = 120,           axi_st_cmd_luma_core.tdata
		.axi_st_cmd_luma_core_tvalid           (in_cmd_axi_st_cmd_luma_core_tvalid),           //  output,    width = 1,                               .tvalid
		.axi_st_cmd_luma_core_tready           (in_cmd_axi_st_cmd_luma_core_tready),           //   input,    width = 1,                               .tready
		.axi_st_cmd_chroma_core_tdata          (in_cmd_axi_st_cmd_chroma_core_tdata),          //  output,  width = 120,         axi_st_cmd_chroma_core.tdata
		.axi_st_cmd_chroma_core_tvalid         (in_cmd_axi_st_cmd_chroma_core_tvalid),         //  output,    width = 1,                               .tvalid
		.axi_st_cmd_chroma_core_tready         (in_cmd_axi_st_cmd_chroma_core_tready),         //   input,    width = 1,                               .tready
		.axi_st_cmd_chroma_seq_par_up_tdata    (in_cmd_axi_st_cmd_chroma_seq_par_up_tdata),    //  output,    width = 8,   axi_st_cmd_chroma_seq_par_up.tdata
		.axi_st_cmd_chroma_seq_par_up_tvalid   (in_cmd_axi_st_cmd_chroma_seq_par_up_tvalid),   //  output,    width = 1,                               .tvalid
		.axi_st_cmd_chroma_seq_par_up_tready   (in_cmd_axi_st_cmd_chroma_seq_par_up_tready),   //   input,    width = 1,                               .tready
		.axi_st_cmd_chroma_seq_par_down_tdata  (in_cmd_axi_st_cmd_chroma_seq_par_down_tdata),  //  output,    width = 8, axi_st_cmd_chroma_seq_par_down.tdata
		.axi_st_cmd_chroma_seq_par_down_tvalid (in_cmd_axi_st_cmd_chroma_seq_par_down_tvalid), //  output,    width = 1,                               .tvalid
		.axi_st_cmd_chroma_seq_par_down_tready (in_cmd_axi_st_cmd_chroma_seq_par_down_tready), //   input,    width = 1,                               .tready
		.axi_st_cmd_output_switch_tdata        (in_cmd_axi_st_cmd_output_switch_tdata),        //  output,   width = 24,       axi_st_cmd_output_switch.tdata
		.axi_st_cmd_output_switch_tvalid       (in_cmd_axi_st_cmd_output_switch_tvalid),       //  output,    width = 1,                               .tvalid
		.axi_st_cmd_output_switch_tready       (in_cmd_axi_st_cmd_output_switch_tready),       //   input,    width = 1,                               .tready
		.axi_st_cmd_luma_split_tdata           (),                                             // (terminated),                                              
		.axi_st_cmd_luma_split_tvalid          (),                                             // (terminated),                                              
		.axi_st_cmd_luma_split_tready          (1'b0),                                         // (terminated),                                              
		.axi_st_cmd_luma_seq_par_up_tdata      (),                                             // (terminated),                                              
		.axi_st_cmd_luma_seq_par_up_tvalid     (),                                             // (terminated),                                              
		.axi_st_cmd_luma_seq_par_up_tready     (1'b0),                                         // (terminated),                                              
		.axi_st_cmd_luma_seq_par_down_tdata    (),                                             // (terminated),                                              
		.axi_st_cmd_luma_seq_par_down_tvalid   (),                                             // (terminated),                                              
		.axi_st_cmd_luma_seq_par_down_tready   (1'b0),                                         // (terminated),                                              
		.axi_st_cmd_luma_pkt_clp_tdata         (),                                             // (terminated),                                              
		.axi_st_cmd_luma_pkt_clp_tvalid        (),                                             // (terminated),                                              
		.axi_st_cmd_luma_pkt_clp_tready        (1'b0)                                          // (terminated),                                              
	);

	intel_vvp_scaler_luma_split #(
		.BPS                (8),
		.PIXELS_IN_PARALLEL (1),
		.ENABLE_420         (0),
		.ENABLE_422         (1),
		.ENABLE_444         (1),
		.PIPELINE_READY     (0)
	) in_split (
		.clk                      (main_clock_clk),                    //   input,   width = 1,        main_clock.clk
		.rst                      (main_rst_bridge_out_reset_reset),   //   input,   width = 1,        main_reset.reset
		.axi_st_data_in_tdata     (axi_st_data_in_tdata),              //   input,  width = 24,    axi_st_data_in.tdata
		.axi_st_data_in_tvalid    (axi_st_data_in_tvalid),             //   input,   width = 1,                  .tvalid
		.axi_st_data_in_tready    (axi_st_data_in_tready),             //  output,   width = 1,                  .tready
		.axi_st_data_in_tlast     (axi_st_data_in_tlast),              //   input,   width = 1,                  .tlast
		.axi_st_data_in_tuser     (axi_st_data_in_tuser),              //   input,   width = 3,                  .tuser
		.axi_st_luma_out_tdata    (in_split_axi_st_luma_out_tdata),    //  output,  width = 16,   axi_st_luma_out.tdata
		.axi_st_luma_out_tvalid   (in_split_axi_st_luma_out_tvalid),   //  output,   width = 1,                  .tvalid
		.axi_st_luma_out_tready   (in_split_axi_st_luma_out_tready),   //   input,   width = 1,                  .tready
		.axi_st_luma_out_tlast    (in_split_axi_st_luma_out_tlast),    //  output,   width = 1,                  .tlast
		.axi_st_luma_out_tuser    (in_split_axi_st_luma_out_tuser),    //  output,   width = 2,                  .tuser
		.axi_st_chroma_out_tdata  (in_split_axi_st_chroma_out_tdata),  //  output,  width = 16, axi_st_chroma_out.tdata
		.axi_st_chroma_out_tvalid (in_split_axi_st_chroma_out_tvalid), //  output,   width = 1,                  .tvalid
		.axi_st_chroma_out_tready (in_split_axi_st_chroma_out_tready), //   input,   width = 1,                  .tready
		.axi_st_chroma_out_tlast  (in_split_axi_st_chroma_out_tlast),  //  output,   width = 1,                  .tlast
		.axi_st_chroma_out_tuser  (in_split_axi_st_chroma_out_tuser),  //  output,   width = 2,                  .tuser
		.axi_st_cmd_tdata         (8'b00000000),                       // (terminated),                                
		.axi_st_cmd_tvalid        (1'b0),                              // (terminated),                                
		.axi_st_cmd_tready        ()                                   // (terminated),                                
	);

	intel_vvp_scaler_output_switch #(
		.BPS                (8),
		.PIXELS_IN_PARALLEL (1),
		.PIPELINE_READY     (0),
		.ENABLE_444         (1),
		.ENABLE_422         (1),
		.ENABLE_420         (0)
	) out_switch (
		.clk                    (main_clock_clk),                         //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),        //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (in_cmd_axi_st_cmd_output_switch_tdata),  //   input,  width = 24,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (in_cmd_axi_st_cmd_output_switch_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (in_cmd_axi_st_cmd_output_switch_tready), //  output,   width = 1,                .tready
		.axi_st_luma_tdata      (luma_algo_comp_axi_st_data_out_tdata),   //   input,  width = 16,     axi_st_luma.tdata
		.axi_st_luma_tvalid     (luma_algo_comp_axi_st_data_out_tvalid),  //   input,   width = 1,                .tvalid
		.axi_st_luma_tready     (luma_algo_comp_axi_st_data_out_tready),  //  output,   width = 1,                .tready
		.axi_st_luma_tlast      (luma_algo_comp_axi_st_data_out_tlast),   //   input,   width = 1,                .tlast
		.axi_st_luma_tuser      (luma_algo_comp_axi_st_data_out_tuser),   //   input,   width = 2,                .tuser
		.axi_st_chroma_tdata    (chroma_sp_down_axi_st_data_out_tdata),   //   input,  width = 16,   axi_st_chroma.tdata
		.axi_st_chroma_tvalid   (chroma_sp_down_axi_st_data_out_tvalid),  //   input,   width = 1,                .tvalid
		.axi_st_chroma_tready   (chroma_sp_down_axi_st_data_out_tready),  //  output,   width = 1,                .tready
		.axi_st_chroma_tlast    (chroma_sp_down_axi_st_data_out_tlast),   //   input,   width = 1,                .tlast
		.axi_st_chroma_tuser    (chroma_sp_down_axi_st_data_out_tuser),   //   input,   width = 2,                .tuser
		.axi_st_data_out_tdata  (axi_st_data_out_tdata),                  //  output,  width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (axi_st_data_out_tvalid),                 //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (axi_st_data_out_tready),                 //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (axi_st_data_out_tlast),                  //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (axi_st_data_out_tuser)                   //  output,   width = 3,                .tuser
	);

	pipeline_intel_vvp_pipeline2_0_intel_vvp_horiz_scaler_algo_comp_2451_tk4fwgq luma_algo_comp (
		.clk                    (main_clock_clk),                        //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),       //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (in_cmd_axi_st_cmd_luma_core_tdata),     //   input,  width = 120,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (in_cmd_axi_st_cmd_luma_core_tvalid),    //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (in_cmd_axi_st_cmd_luma_core_tready),    //  output,    width = 1,                .tready
		.axi_st_data_in_tdata   (in_split_axi_st_luma_out_tdata),        //   input,   width = 16,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (in_split_axi_st_luma_out_tvalid),       //   input,    width = 1,                .tvalid
		.axi_st_data_in_tready  (in_split_axi_st_luma_out_tready),       //  output,    width = 1,                .tready
		.axi_st_data_in_tlast   (in_split_axi_st_luma_out_tlast),        //   input,    width = 1,                .tlast
		.axi_st_data_in_tuser   (in_split_axi_st_luma_out_tuser),        //   input,    width = 2,                .tuser
		.axi_st_data_out_tdata  (luma_algo_comp_axi_st_data_out_tdata),  //  output,   width = 16, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (luma_algo_comp_axi_st_data_out_tvalid), //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (luma_algo_comp_axi_st_data_out_tready), //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (luma_algo_comp_axi_st_data_out_tlast),  //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (luma_algo_comp_axi_st_data_out_tuser)   //  output,    width = 2,                .tuser
	);

	pipeline_intel_vvp_pipeline2_0_intel_vvp_horiz_scaler_algo_comp_2451_vxbz7by chroma_algo_comp (
		.clk                    (main_clock_clk),                          //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),         //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (in_cmd_axi_st_cmd_chroma_core_tdata),     //   input,  width = 120,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (in_cmd_axi_st_cmd_chroma_core_tvalid),    //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (in_cmd_axi_st_cmd_chroma_core_tready),    //  output,    width = 1,                .tready
		.axi_st_data_in_tdata   (chroma_sp_up_axi_st_data_out_tdata),      //   input,   width = 16,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (chroma_sp_up_axi_st_data_out_tvalid),     //   input,    width = 1,                .tvalid
		.axi_st_data_in_tready  (chroma_sp_up_axi_st_data_out_tready),     //  output,    width = 1,                .tready
		.axi_st_data_in_tlast   (chroma_sp_up_axi_st_data_out_tlast),      //   input,    width = 1,                .tlast
		.axi_st_data_in_tuser   (chroma_sp_up_axi_st_data_out_tuser),      //   input,    width = 2,                .tuser
		.axi_st_data_out_tdata  (chroma_algo_comp_axi_st_data_out_tdata),  //  output,   width = 16, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (chroma_algo_comp_axi_st_data_out_tvalid), //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (chroma_algo_comp_axi_st_data_out_tready), //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (chroma_algo_comp_axi_st_data_out_tlast),  //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (chroma_algo_comp_axi_st_data_out_tuser)   //  output,    width = 2,                .tuser
	);

	intel_vvp_scaler_seq_par_chroma #(
		.BPS                (8),
		.PIXELS_IN_PARALLEL (1),
		.ENABLE_444         (1),
		.ENABLE_420         (0),
		.UP_CONVERT         (1),
		.PIPELINE_READY     (0)
	) chroma_sp_up (
		.clk                    (main_clock_clk),                             //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),            //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (in_cmd_axi_st_cmd_chroma_seq_par_up_tdata),  //   input,   width = 8,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (in_cmd_axi_st_cmd_chroma_seq_par_up_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (in_cmd_axi_st_cmd_chroma_seq_par_up_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (in_split_axi_st_chroma_out_tdata),           //   input,  width = 16,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (in_split_axi_st_chroma_out_tvalid),          //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (in_split_axi_st_chroma_out_tready),          //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (in_split_axi_st_chroma_out_tlast),           //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (in_split_axi_st_chroma_out_tuser),           //   input,   width = 2,                .tuser
		.axi_st_data_out_tdata  (chroma_sp_up_axi_st_data_out_tdata),         //  output,  width = 16, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (chroma_sp_up_axi_st_data_out_tvalid),        //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (chroma_sp_up_axi_st_data_out_tready),        //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (chroma_sp_up_axi_st_data_out_tlast),         //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (chroma_sp_up_axi_st_data_out_tuser)          //  output,   width = 2,                .tuser
	);

	intel_vvp_scaler_seq_par_chroma #(
		.BPS                (8),
		.PIXELS_IN_PARALLEL (1),
		.ENABLE_444         (1),
		.ENABLE_420         (0),
		.UP_CONVERT         (0),
		.PIPELINE_READY     (0)
	) chroma_sp_down (
		.clk                    (main_clock_clk),                               //   input,   width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),              //   input,   width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (in_cmd_axi_st_cmd_chroma_seq_par_down_tdata),  //   input,   width = 8,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (in_cmd_axi_st_cmd_chroma_seq_par_down_tvalid), //   input,   width = 1,                .tvalid
		.axi_st_cmd_tready      (in_cmd_axi_st_cmd_chroma_seq_par_down_tready), //  output,   width = 1,                .tready
		.axi_st_data_in_tdata   (chroma_algo_comp_axi_st_data_out_tdata),       //   input,  width = 16,  axi_st_data_in.tdata
		.axi_st_data_in_tvalid  (chroma_algo_comp_axi_st_data_out_tvalid),      //   input,   width = 1,                .tvalid
		.axi_st_data_in_tready  (chroma_algo_comp_axi_st_data_out_tready),      //  output,   width = 1,                .tready
		.axi_st_data_in_tlast   (chroma_algo_comp_axi_st_data_out_tlast),       //   input,   width = 1,                .tlast
		.axi_st_data_in_tuser   (chroma_algo_comp_axi_st_data_out_tuser),       //   input,   width = 2,                .tuser
		.axi_st_data_out_tdata  (chroma_sp_down_axi_st_data_out_tdata),         //  output,  width = 16, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (chroma_sp_down_axi_st_data_out_tvalid),        //  output,   width = 1,                .tvalid
		.axi_st_data_out_tready (chroma_sp_down_axi_st_data_out_tready),        //   input,   width = 1,                .tready
		.axi_st_data_out_tlast  (chroma_sp_down_axi_st_data_out_tlast),         //  output,   width = 1,                .tlast
		.axi_st_data_out_tuser  (chroma_sp_down_axi_st_data_out_tuser)          //  output,   width = 2,                .tuser
	);

endmodule
