// system.v

// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module system (
		output wire [47:0] alt_vip_cl_crs_0_dout_data,          // alt_vip_cl_crs_0_dout.data
		output wire        alt_vip_cl_crs_0_dout_valid,         //                      .valid
		output wire        alt_vip_cl_crs_0_dout_startofpacket, //                      .startofpacket
		output wire        alt_vip_cl_crs_0_dout_endofpacket,   //                      .endofpacket
		output wire [2:0]  alt_vip_cl_crs_0_dout_empty,         //                      .empty
		input  wire        alt_vip_cl_crs_0_dout_ready,         //                      .ready
		input  wire        clk_clk,                             //                   clk.clk
		input  wire        reset_reset                          //                 reset.reset
	);

	wire         alt_vip_cl_tpg_0_dout_valid;         // alt_vip_cl_tpg_0:dout_valid -> alt_vip_cl_crs_0:din_valid
	wire  [31:0] alt_vip_cl_tpg_0_dout_data;          // alt_vip_cl_tpg_0:dout_data -> alt_vip_cl_crs_0:din_data
	wire         alt_vip_cl_tpg_0_dout_ready;         // alt_vip_cl_crs_0:din_ready -> alt_vip_cl_tpg_0:dout_ready
	wire         alt_vip_cl_tpg_0_dout_startofpacket; // alt_vip_cl_tpg_0:dout_startofpacket -> alt_vip_cl_crs_0:din_startofpacket
	wire         alt_vip_cl_tpg_0_dout_endofpacket;   // alt_vip_cl_tpg_0:dout_endofpacket -> alt_vip_cl_crs_0:din_endofpacket
	wire   [1:0] alt_vip_cl_tpg_0_dout_empty;         // alt_vip_cl_tpg_0:dout_empty -> alt_vip_cl_crs_0:din_empty
	wire         clock_in_out_clk_clk;                // clock_in:out_clk -> [alt_vip_cl_crs_0:main_clock, alt_vip_cl_tpg_0:main_clock, reset_in:clk]
	wire         reset_in_out_reset_reset;            // reset_in:out_reset -> [alt_vip_cl_crs_0:main_reset, alt_vip_cl_tpg_0:main_reset]

	system_alt_vip_cl_crs_0 alt_vip_cl_crs_0 (
		.main_clock         (clock_in_out_clk_clk),                //   input,   width = 1, main_clock.clk
		.main_reset         (reset_in_out_reset_reset),            //   input,   width = 1, main_reset.reset
		.din_data           (alt_vip_cl_tpg_0_dout_data),          //   input,  width = 32,        din.data
		.din_valid          (alt_vip_cl_tpg_0_dout_valid),         //   input,   width = 1,           .valid
		.din_startofpacket  (alt_vip_cl_tpg_0_dout_startofpacket), //   input,   width = 1,           .startofpacket
		.din_endofpacket    (alt_vip_cl_tpg_0_dout_endofpacket),   //   input,   width = 1,           .endofpacket
		.din_empty          (alt_vip_cl_tpg_0_dout_empty),         //   input,   width = 2,           .empty
		.din_ready          (alt_vip_cl_tpg_0_dout_ready),         //  output,   width = 1,           .ready
		.dout_data          (alt_vip_cl_crs_0_dout_data),          //  output,  width = 48,       dout.data
		.dout_valid         (alt_vip_cl_crs_0_dout_valid),         //  output,   width = 1,           .valid
		.dout_startofpacket (alt_vip_cl_crs_0_dout_startofpacket), //  output,   width = 1,           .startofpacket
		.dout_endofpacket   (alt_vip_cl_crs_0_dout_endofpacket),   //  output,   width = 1,           .endofpacket
		.dout_empty         (alt_vip_cl_crs_0_dout_empty),         //  output,   width = 3,           .empty
		.dout_ready         (alt_vip_cl_crs_0_dout_ready)          //   input,   width = 1,           .ready
	);

	system_alt_vip_cl_tpg_0 alt_vip_cl_tpg_0 (
		.main_clock         (clock_in_out_clk_clk),                //   input,   width = 1, main_clock.clk
		.main_reset         (reset_in_out_reset_reset),            //   input,   width = 1, main_reset.reset
		.dout_data          (alt_vip_cl_tpg_0_dout_data),          //  output,  width = 32,       dout.data
		.dout_valid         (alt_vip_cl_tpg_0_dout_valid),         //  output,   width = 1,           .valid
		.dout_startofpacket (alt_vip_cl_tpg_0_dout_startofpacket), //  output,   width = 1,           .startofpacket
		.dout_endofpacket   (alt_vip_cl_tpg_0_dout_endofpacket),   //  output,   width = 1,           .endofpacket
		.dout_empty         (alt_vip_cl_tpg_0_dout_empty),         //  output,   width = 2,           .empty
		.dout_ready         (alt_vip_cl_tpg_0_dout_ready)          //   input,   width = 1,           .ready
	);

	system_clock_in clock_in (
		.in_clk  (clk_clk),              //   input,  width = 1,  in_clk.clk
		.out_clk (clock_in_out_clk_clk)  //  output,  width = 1, out_clk.clk
	);

	system_reset_in reset_in (
		.clk       (clock_in_out_clk_clk),     //   input,  width = 1,       clk.clk
		.in_reset  (reset_reset),              //   input,  width = 1,  in_reset.reset
		.out_reset (reset_in_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

endmodule
