// pl_sys_intel_vvp_adv_tpg_1_intel_vvp_adv_tpg_2451_spkd5oa.v

// This file was auto-generated from intel_vvp_adv_tpg_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 25.1.1 125

`timescale 1 ps / 1 ps
module pl_sys_intel_vvp_adv_tpg_1_intel_vvp_adv_tpg_2451_spkd5oa (
		input  wire        main_clock_clk,       //    main_clock.clk,   Clock Input
		input  wire        main_reset_reset,     //    main_reset.reset
		output wire [23:0] axi4s_vid_out_tdata,  // axi4s_vid_out.tdata
		output wire        axi4s_vid_out_tvalid, //              .tvalid
		input  wire        axi4s_vid_out_tready, //              .tready
		output wire        axi4s_vid_out_tlast,  //              .tlast
		output wire [2:0]  axi4s_vid_out_tuser   //              .tuser
	);

	wire          main_rst_bridge_out_reset_reset;     // main_rst_bridge:out_rst -> [core_inst_0:rst, core_inst_1:rst, mixer_inst_0:rst, out_bridge:rst, scheduler:rst]
	wire          scheduler_axi_st_ctrl_out_tvalid;    // scheduler:axi_st_ctrl_out_tvalid -> out_bridge:axi_st_ctrl_in_tvalid
	wire    [1:0] scheduler_axi_st_ctrl_out_tuser;     // scheduler:axi_st_ctrl_out_tuser -> out_bridge:axi_st_ctrl_in_tuser
	wire          scheduler_axi_st_ctrl_out_tready;    // out_bridge:axi_st_ctrl_in_tready -> scheduler:axi_st_ctrl_out_tready
	wire   [15:0] scheduler_axi_st_ctrl_out_tdata;     // scheduler:axi_st_ctrl_out_tdata -> out_bridge:axi_st_ctrl_in_tdata
	wire          scheduler_axi_st_ctrl_out_tlast;     // scheduler:axi_st_ctrl_out_tlast -> out_bridge:axi_st_ctrl_in_tlast
	wire          scheduler_axi_st_tpg_cmd_0_tvalid;   // scheduler:axi_st_tpg_cmd_0_tvalid -> core_inst_0:axi_st_cmd_tvalid
	wire          scheduler_axi_st_tpg_cmd_0_tready;   // core_inst_0:axi_st_cmd_tready -> scheduler:axi_st_tpg_cmd_0_tready
	wire  [215:0] scheduler_axi_st_tpg_cmd_0_tdata;    // scheduler:axi_st_tpg_cmd_0_tdata -> core_inst_0:axi_st_cmd_tdata
	wire          scheduler_axi_st_tpg_cmd_1_tvalid;   // scheduler:axi_st_tpg_cmd_1_tvalid -> core_inst_1:axi_st_cmd_tvalid
	wire          scheduler_axi_st_tpg_cmd_1_tready;   // core_inst_1:axi_st_cmd_tready -> scheduler:axi_st_tpg_cmd_1_tready
	wire  [215:0] scheduler_axi_st_tpg_cmd_1_tdata;    // scheduler:axi_st_tpg_cmd_1_tdata -> core_inst_1:axi_st_cmd_tdata
	wire          scheduler_axi_st_mixer_cmd_0_tvalid; // scheduler:axi_st_mixer_cmd_0_tvalid -> mixer_inst_0:axi_st_cmd_tvalid
	wire          scheduler_axi_st_mixer_cmd_0_tready; // mixer_inst_0:axi_st_cmd_tready -> scheduler:axi_st_mixer_cmd_0_tready
	wire   [55:0] scheduler_axi_st_mixer_cmd_0_tdata;  // scheduler:axi_st_mixer_cmd_0_tdata -> mixer_inst_0:axi_st_cmd_tdata
	wire          core_inst_0_axi_st_data_out_tvalid;  // core_inst_0:axi_st_data_out_tvalid -> mixer_inst_0:axi_st_base_data_tvalid
	wire    [2:0] core_inst_0_axi_st_data_out_tuser;   // core_inst_0:axi_st_data_out_tuser -> mixer_inst_0:axi_st_base_data_tuser
	wire          core_inst_0_axi_st_data_out_tready;  // mixer_inst_0:axi_st_base_data_tready -> core_inst_0:axi_st_data_out_tready
	wire   [23:0] core_inst_0_axi_st_data_out_tdata;   // core_inst_0:axi_st_data_out_tdata -> mixer_inst_0:axi_st_base_data_tdata
	wire          core_inst_0_axi_st_data_out_tlast;   // core_inst_0:axi_st_data_out_tlast -> mixer_inst_0:axi_st_base_data_tlast
	wire          core_inst_1_axi_st_data_out_tvalid;  // core_inst_1:axi_st_data_out_tvalid -> mixer_inst_0:axi_st_overlay_data_tvalid
	wire    [2:0] core_inst_1_axi_st_data_out_tuser;   // core_inst_1:axi_st_data_out_tuser -> mixer_inst_0:axi_st_overlay_data_tuser
	wire          core_inst_1_axi_st_data_out_tready;  // mixer_inst_0:axi_st_overlay_data_tready -> core_inst_1:axi_st_data_out_tready
	wire   [23:0] core_inst_1_axi_st_data_out_tdata;   // core_inst_1:axi_st_data_out_tdata -> mixer_inst_0:axi_st_overlay_data_tdata
	wire          core_inst_1_axi_st_data_out_tlast;   // core_inst_1:axi_st_data_out_tlast -> mixer_inst_0:axi_st_overlay_data_tlast
	wire          mixer_inst_0_axi_st_data_out_tvalid; // mixer_inst_0:axi_st_data_out_tvalid -> out_bridge:axi_st_data_in_tvalid
	wire    [2:0] mixer_inst_0_axi_st_data_out_tuser;  // mixer_inst_0:axi_st_data_out_tuser -> out_bridge:axi_st_data_in_tuser
	wire          mixer_inst_0_axi_st_data_out_tready; // out_bridge:axi_st_data_in_tready -> mixer_inst_0:axi_st_data_out_tready
	wire   [23:0] mixer_inst_0_axi_st_data_out_tdata;  // mixer_inst_0:axi_st_data_out_tdata -> out_bridge:axi_st_data_in_tdata
	wire          mixer_inst_0_axi_st_data_out_tlast;  // mixer_inst_0:axi_st_data_out_tlast -> out_bridge:axi_st_data_in_tlast
	wire    [1:0] scheduler_axi_st_tpg_cmd_tvalid;     // port fragment
	wire  [431:0] scheduler_axi_st_tpg_cmd_tdata;      // port fragment
	wire    [0:0] scheduler_axi_st_mixer_cmd_tvalid;   // port fragment
	wire   [55:0] scheduler_axi_st_mixer_cmd_tdata;    // port fragment

	intel_vvp_reset_sync #(
		.SYNC_LEN (3)
	) main_rst_bridge (
		.clk     (main_clock_clk),                  //   input,  width = 1,       clk.clk
		.in_rst  (main_reset_reset),                //   input,  width = 1,  in_reset.reset
		.out_rst (main_rst_bridge_out_reset_reset)  //  output,  width = 1, out_reset.reset
	);

	intel_vvp_adv_tpg_scheduler #(
		.EXTERNAL_MODE                (0),
		.BPS                          (8),
		.RUNTIME_CONTROL              (0),
		.ENABLE_DEBUG                 (0),
		.NUM_CORES                    (2),
		.FIXED_WIDTH                  (640),
		.FIXED_HEIGHT                 (480),
		.COLOUR_SPACE                 (0),
		.FIXED_INTERLACE              (8),
		.CORE_PATTERN_0               (0),
		.FIXED_BARS_MODE_0            (0),
		.FIXED_ZONE_COARSE_0          (16),
		.FIXED_ZONE_FINE_0            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_0 (1),
		.FIXED_PRIMARY_B_CB_0         (0),
		.FIXED_PRIMARY_G_Y_0          (0),
		.FIXED_PRIMARY_R_CR_0         (0),
		.FIXED_SECONDARY_B_CB_0       (0),
		.FIXED_SECONDARY_G_Y_0        (0),
		.FIXED_SECONDARY_R_CR_0       (0),
		.FIXED_LOCATION_X_0           (0),
		.FIXED_LOCATION_Y_0           (0),
		.FIXED_FPS_0                  (1),
		.SIGTAP_TYPE_0                (0),
		.CORE_PATTERN_1               (0),
		.FIXED_BARS_MODE_1            (0),
		.FIXED_ZONE_COARSE_1          (16),
		.FIXED_ZONE_FINE_1            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_1 (1),
		.FIXED_PRIMARY_B_CB_1         (0),
		.FIXED_PRIMARY_G_Y_1          (0),
		.FIXED_PRIMARY_R_CR_1         (0),
		.FIXED_SECONDARY_B_CB_1       (0),
		.FIXED_SECONDARY_G_Y_1        (0),
		.FIXED_SECONDARY_R_CR_1       (0),
		.FIXED_LOCATION_X_1           (0),
		.FIXED_LOCATION_Y_1           (0),
		.FIXED_FPS_1                  (1),
		.SIGTAP_TYPE_1                (0),
		.CORE_PATTERN_2               (0),
		.FIXED_BARS_MODE_2            (0),
		.FIXED_ZONE_COARSE_2          (16),
		.FIXED_ZONE_FINE_2            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_2 (0),
		.FIXED_PRIMARY_B_CB_2         (0),
		.FIXED_PRIMARY_G_Y_2          (0),
		.FIXED_PRIMARY_R_CR_2         (0),
		.FIXED_SECONDARY_B_CB_2       (0),
		.FIXED_SECONDARY_G_Y_2        (0),
		.FIXED_SECONDARY_R_CR_2       (0),
		.FIXED_LOCATION_X_2           (0),
		.FIXED_LOCATION_Y_2           (0),
		.FIXED_FPS_2                  (0),
		.SIGTAP_TYPE_2                (0),
		.CORE_PATTERN_3               (0),
		.FIXED_BARS_MODE_3            (0),
		.FIXED_ZONE_COARSE_3          (16),
		.FIXED_ZONE_FINE_3            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_3 (0),
		.FIXED_PRIMARY_B_CB_3         (0),
		.FIXED_PRIMARY_G_Y_3          (0),
		.FIXED_PRIMARY_R_CR_3         (0),
		.FIXED_SECONDARY_B_CB_3       (0),
		.FIXED_SECONDARY_G_Y_3        (0),
		.FIXED_SECONDARY_R_CR_3       (0),
		.FIXED_LOCATION_X_3           (0),
		.FIXED_LOCATION_Y_3           (0),
		.FIXED_FPS_3                  (0),
		.SIGTAP_TYPE_3                (0),
		.CORE_PATTERN_4               (0),
		.FIXED_BARS_MODE_4            (0),
		.FIXED_ZONE_COARSE_4          (16),
		.FIXED_ZONE_FINE_4            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_4 (0),
		.FIXED_PRIMARY_B_CB_4         (0),
		.FIXED_PRIMARY_G_Y_4          (0),
		.FIXED_PRIMARY_R_CR_4         (0),
		.FIXED_SECONDARY_B_CB_4       (0),
		.FIXED_SECONDARY_G_Y_4        (0),
		.FIXED_SECONDARY_R_CR_4       (0),
		.FIXED_LOCATION_X_4           (0),
		.FIXED_LOCATION_Y_4           (0),
		.FIXED_FPS_4                  (0),
		.SIGTAP_TYPE_4                (0),
		.CORE_PATTERN_5               (0),
		.FIXED_BARS_MODE_5            (0),
		.FIXED_ZONE_COARSE_5          (16),
		.FIXED_ZONE_FINE_5            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_5 (0),
		.FIXED_PRIMARY_B_CB_5         (0),
		.FIXED_PRIMARY_G_Y_5          (0),
		.FIXED_PRIMARY_R_CR_5         (0),
		.FIXED_SECONDARY_B_CB_5       (0),
		.FIXED_SECONDARY_G_Y_5        (0),
		.FIXED_SECONDARY_R_CR_5       (0),
		.FIXED_LOCATION_X_5           (0),
		.FIXED_LOCATION_Y_5           (0),
		.FIXED_FPS_5                  (0),
		.SIGTAP_TYPE_5                (0),
		.CORE_PATTERN_6               (0),
		.FIXED_BARS_MODE_6            (0),
		.FIXED_ZONE_COARSE_6          (16),
		.FIXED_ZONE_FINE_6            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_6 (0),
		.FIXED_PRIMARY_B_CB_6         (0),
		.FIXED_PRIMARY_G_Y_6          (0),
		.FIXED_PRIMARY_R_CR_6         (0),
		.FIXED_SECONDARY_B_CB_6       (0),
		.FIXED_SECONDARY_G_Y_6        (0),
		.FIXED_SECONDARY_R_CR_6       (0),
		.FIXED_LOCATION_X_6           (0),
		.FIXED_LOCATION_Y_6           (0),
		.FIXED_FPS_6                  (0),
		.SIGTAP_TYPE_6                (0),
		.CORE_PATTERN_7               (0),
		.FIXED_BARS_MODE_7            (0),
		.FIXED_ZONE_COARSE_7          (16),
		.FIXED_ZONE_FINE_7            (256),
		.FIXED_DIGITAL_SCALE_FACTOR_7 (0),
		.FIXED_PRIMARY_B_CB_7         (0),
		.FIXED_PRIMARY_G_Y_7          (0),
		.FIXED_PRIMARY_R_CR_7         (0),
		.FIXED_SECONDARY_B_CB_7       (0),
		.FIXED_SECONDARY_G_Y_7        (0),
		.FIXED_SECONDARY_R_CR_7       (0),
		.FIXED_LOCATION_X_7           (0),
		.FIXED_LOCATION_Y_7           (0),
		.FIXED_FPS_7                  (0),
		.SIGTAP_TYPE_7                (0),
		.FIXED_LAYER_1_HEIGHT         (480),
		.FIXED_LAYER_1_WIDTH          (640),
		.FIXED_LAYER_1_ALPHA          (0),
		.FIXED_LAYER_1_H_OFFSET       (0),
		.FIXED_LAYER_1_V_OFFSET       (0),
		.FIXED_LAYER_2_HEIGHT         (16384),
		.FIXED_LAYER_2_WIDTH          (16384),
		.FIXED_LAYER_2_ALPHA          (0),
		.FIXED_LAYER_2_H_OFFSET       (0),
		.FIXED_LAYER_2_V_OFFSET       (0),
		.FIXED_LAYER_3_HEIGHT         (16384),
		.FIXED_LAYER_3_WIDTH          (16384),
		.FIXED_LAYER_3_ALPHA          (0),
		.FIXED_LAYER_3_H_OFFSET       (0),
		.FIXED_LAYER_3_V_OFFSET       (0),
		.FIXED_LAYER_4_HEIGHT         (16384),
		.FIXED_LAYER_4_WIDTH          (16384),
		.FIXED_LAYER_4_ALPHA          (0),
		.FIXED_LAYER_4_H_OFFSET       (0),
		.FIXED_LAYER_4_V_OFFSET       (0),
		.FIXED_LAYER_5_HEIGHT         (16384),
		.FIXED_LAYER_5_WIDTH          (16384),
		.FIXED_LAYER_5_ALPHA          (0),
		.FIXED_LAYER_5_H_OFFSET       (0),
		.FIXED_LAYER_5_V_OFFSET       (0),
		.FIXED_LAYER_6_HEIGHT         (16384),
		.FIXED_LAYER_6_WIDTH          (16384),
		.FIXED_LAYER_6_ALPHA          (0),
		.FIXED_LAYER_6_H_OFFSET       (0),
		.FIXED_LAYER_6_V_OFFSET       (0),
		.FIXED_LAYER_7_HEIGHT         (16384),
		.FIXED_LAYER_7_WIDTH          (16384),
		.FIXED_LAYER_7_ALPHA          (0),
		.FIXED_LAYER_7_H_OFFSET       (0),
		.FIXED_LAYER_7_V_OFFSET       (0),
		.PIPELINE_READY               (0),
		.SLAVE_ADDRESS_WIDTH          (7)
	) scheduler (
		.clk                       (main_clock_clk),                                                                  //   input,    width = 1,         main_clock.clk
		.rst                       (main_rst_bridge_out_reset_reset),                                                 //   input,    width = 1,         main_reset.reset
		.axi_st_ctrl_out_tdata     (scheduler_axi_st_ctrl_out_tdata),                                                 //  output,   width = 16,    axi_st_ctrl_out.tdata
		.axi_st_ctrl_out_tvalid    (scheduler_axi_st_ctrl_out_tvalid),                                                //  output,    width = 1,                   .tvalid
		.axi_st_ctrl_out_tready    (scheduler_axi_st_ctrl_out_tready),                                                //   input,    width = 1,                   .tready
		.axi_st_ctrl_out_tlast     (scheduler_axi_st_ctrl_out_tlast),                                                 //  output,    width = 1,                   .tlast
		.axi_st_ctrl_out_tuser     (scheduler_axi_st_ctrl_out_tuser),                                                 //  output,    width = 2,                   .tuser
		.axi_st_mixer_cmd_tdata    (scheduler_axi_st_mixer_cmd_tdata[55:0]),                                          //  output,   width = 56, axi_st_mixer_cmd_0.tdata
		.axi_st_mixer_cmd_tvalid   (scheduler_axi_st_mixer_cmd_tvalid[0]),                                            //  output,    width = 1,                   .tvalid
		.axi_st_mixer_cmd_tready   (scheduler_axi_st_mixer_cmd_0_tready),                                             //   input,    width = 1,                   .tready
		.axi_st_tpg_cmd_tdata      ({scheduler_axi_st_tpg_cmd_tdata[431:216],scheduler_axi_st_tpg_cmd_tdata[215:0]}), //  output,  width = 432,   axi_st_tpg_cmd_0.tdata
		.axi_st_tpg_cmd_tvalid     ({scheduler_axi_st_tpg_cmd_tvalid[1],scheduler_axi_st_tpg_cmd_tvalid[0]}),         //  output,    width = 2,                   .tvalid
		.axi_st_tpg_cmd_tready     ({scheduler_axi_st_tpg_cmd_1_tready,scheduler_axi_st_tpg_cmd_0_tready}),           //   input,    width = 2,                   .tready
		.av_mm_slave_address       (7'b0000000),                                                                      // (terminated),                                  
		.av_mm_slave_write         (1'b0),                                                                            // (terminated),                                  
		.av_mm_slave_byteenable    (4'b0000),                                                                         // (terminated),                                  
		.av_mm_slave_writedata     (32'b00000000000000000000000000000000),                                            // (terminated),                                  
		.av_mm_slave_read          (1'b0),                                                                            // (terminated),                                  
		.av_mm_slave_readdata      (),                                                                                // (terminated),                                  
		.av_mm_slave_readdatavalid (),                                                                                // (terminated),                                  
		.av_mm_slave_waitrequest   ()                                                                                 // (terminated),                                  
	);

	intel_vvp_output_interface_bridge #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.EXTERNAL_MODE          (0)
	) out_bridge (
		.clk                   (main_clock_clk),                      //   input,   width = 1,     main_clock.clk
		.rst                   (main_rst_bridge_out_reset_reset),     //   input,   width = 1,     main_reset.reset
		.axi_st_ctrl_in_tdata  (scheduler_axi_st_ctrl_out_tdata),     //   input,  width = 16, axi_st_ctrl_in.tdata
		.axi_st_ctrl_in_tvalid (scheduler_axi_st_ctrl_out_tvalid),    //   input,   width = 1,               .tvalid
		.axi_st_ctrl_in_tready (scheduler_axi_st_ctrl_out_tready),    //  output,   width = 1,               .tready
		.axi_st_ctrl_in_tlast  (scheduler_axi_st_ctrl_out_tlast),     //   input,   width = 1,               .tlast
		.axi_st_ctrl_in_tuser  (scheduler_axi_st_ctrl_out_tuser),     //   input,   width = 2,               .tuser
		.axi_st_data_in_tdata  (mixer_inst_0_axi_st_data_out_tdata),  //   input,  width = 24, axi_st_data_in.tdata
		.axi_st_data_in_tvalid (mixer_inst_0_axi_st_data_out_tvalid), //   input,   width = 1,               .tvalid
		.axi_st_data_in_tready (mixer_inst_0_axi_st_data_out_tready), //  output,   width = 1,               .tready
		.axi_st_data_in_tlast  (mixer_inst_0_axi_st_data_out_tlast),  //   input,   width = 1,               .tlast
		.axi_st_data_in_tuser  (mixer_inst_0_axi_st_data_out_tuser),  //   input,   width = 3,               .tuser
		.axi_st_ccd_out_tdata  (axi4s_vid_out_tdata),                 //  output,  width = 24, axi_st_ccd_out.tdata
		.axi_st_ccd_out_tvalid (axi4s_vid_out_tvalid),                //  output,   width = 1,               .tvalid
		.axi_st_ccd_out_tready (axi4s_vid_out_tready),                //   input,   width = 1,               .tready
		.axi_st_ccd_out_tlast  (axi4s_vid_out_tlast),                 //  output,   width = 1,               .tlast
		.axi_st_ccd_out_tuser  (axi4s_vid_out_tuser)                  //  output,   width = 3,               .tuser
	);

	intel_vvp_tpg_bars_algo_comp #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.TPG_CS                 ("RGB_444")
	) core_inst_0 (
		.clk                    (main_clock_clk),                     //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_tpg_cmd_0_tdata),   //   input,  width = 216,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_tpg_cmd_0_tvalid),  //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_tpg_cmd_0_tready),  //  output,    width = 1,                .tready
		.axi_st_data_out_tdata  (core_inst_0_axi_st_data_out_tdata),  //  output,   width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (core_inst_0_axi_st_data_out_tvalid), //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (core_inst_0_axi_st_data_out_tready), //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (core_inst_0_axi_st_data_out_tlast),  //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (core_inst_0_axi_st_data_out_tuser)   //  output,    width = 3,                .tuser
	);

	intel_vvp_tpg_bars_algo_comp #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.PIPELINE_READY         (0),
		.TPG_CS                 ("RGB_444")
	) core_inst_1 (
		.clk                    (main_clock_clk),                     //   input,    width = 1,      main_clock.clk
		.rst                    (main_rst_bridge_out_reset_reset),    //   input,    width = 1,      main_reset.reset
		.axi_st_cmd_tdata       (scheduler_axi_st_tpg_cmd_1_tdata),   //   input,  width = 216,      axi_st_cmd.tdata
		.axi_st_cmd_tvalid      (scheduler_axi_st_tpg_cmd_1_tvalid),  //   input,    width = 1,                .tvalid
		.axi_st_cmd_tready      (scheduler_axi_st_tpg_cmd_1_tready),  //  output,    width = 1,                .tready
		.axi_st_data_out_tdata  (core_inst_1_axi_st_data_out_tdata),  //  output,   width = 24, axi_st_data_out.tdata
		.axi_st_data_out_tvalid (core_inst_1_axi_st_data_out_tvalid), //  output,    width = 1,                .tvalid
		.axi_st_data_out_tready (core_inst_1_axi_st_data_out_tready), //   input,    width = 1,                .tready
		.axi_st_data_out_tlast  (core_inst_1_axi_st_data_out_tlast),  //  output,    width = 1,                .tlast
		.axi_st_data_out_tuser  (core_inst_1_axi_st_data_out_tuser)   //  output,    width = 3,                .tuser
	);

	intel_vvp_mixer_algo_comp #(
		.BPS                    (8),
		.NUMBER_OF_COLOR_PLANES (3),
		.PIXELS_IN_PARALLEL     (1),
		.BLENDING_MODE          (1),
		.DO_ROUNDING            (1),
		.RESTRICTED_OFFSETS     (0),
		.PIPELINE_LEVEL         (0),
		.DEVICE_FAMILY          ("Cyclone 10 GX")
	) mixer_inst_0 (
		.clk                        (main_clock_clk),                      //   input,   width = 1,          main_clock.clk
		.rst                        (main_rst_bridge_out_reset_reset),     //   input,   width = 1,          main_reset.reset
		.axi_st_cmd_tdata           (scheduler_axi_st_mixer_cmd_0_tdata),  //   input,  width = 56,          axi_st_cmd.tdata
		.axi_st_cmd_tvalid          (scheduler_axi_st_mixer_cmd_0_tvalid), //   input,   width = 1,                    .tvalid
		.axi_st_cmd_tready          (scheduler_axi_st_mixer_cmd_0_tready), //  output,   width = 1,                    .tready
		.axi_st_base_data_tdata     (core_inst_0_axi_st_data_out_tdata),   //   input,  width = 24,    axi_st_base_data.tdata
		.axi_st_base_data_tvalid    (core_inst_0_axi_st_data_out_tvalid),  //   input,   width = 1,                    .tvalid
		.axi_st_base_data_tready    (core_inst_0_axi_st_data_out_tready),  //  output,   width = 1,                    .tready
		.axi_st_base_data_tlast     (core_inst_0_axi_st_data_out_tlast),   //   input,   width = 1,                    .tlast
		.axi_st_base_data_tuser     (core_inst_0_axi_st_data_out_tuser),   //   input,   width = 3,                    .tuser
		.axi_st_overlay_data_tdata  (core_inst_1_axi_st_data_out_tdata),   //   input,  width = 24, axi_st_overlay_data.tdata
		.axi_st_overlay_data_tvalid (core_inst_1_axi_st_data_out_tvalid),  //   input,   width = 1,                    .tvalid
		.axi_st_overlay_data_tready (core_inst_1_axi_st_data_out_tready),  //  output,   width = 1,                    .tready
		.axi_st_overlay_data_tlast  (core_inst_1_axi_st_data_out_tlast),   //   input,   width = 1,                    .tlast
		.axi_st_overlay_data_tuser  (core_inst_1_axi_st_data_out_tuser),   //   input,   width = 3,                    .tuser
		.axi_st_data_out_tdata      (mixer_inst_0_axi_st_data_out_tdata),  //  output,  width = 24,     axi_st_data_out.tdata
		.axi_st_data_out_tvalid     (mixer_inst_0_axi_st_data_out_tvalid), //  output,   width = 1,                    .tvalid
		.axi_st_data_out_tready     (mixer_inst_0_axi_st_data_out_tready), //   input,   width = 1,                    .tready
		.axi_st_data_out_tlast      (mixer_inst_0_axi_st_data_out_tlast),  //  output,   width = 1,                    .tlast
		.axi_st_data_out_tuser      (mixer_inst_0_axi_st_data_out_tuser)   //  output,   width = 3,                    .tuser
	);

	assign scheduler_axi_st_mixer_cmd_0_tdata = { scheduler_axi_st_mixer_cmd_tdata[55:0] };

	assign scheduler_axi_st_mixer_cmd_0_tvalid = { scheduler_axi_st_mixer_cmd_tvalid[0] };

	assign scheduler_axi_st_tpg_cmd_0_tdata = { scheduler_axi_st_tpg_cmd_tdata[215:0] };

	assign scheduler_axi_st_tpg_cmd_0_tvalid = { scheduler_axi_st_tpg_cmd_tvalid[0] };

	assign scheduler_axi_st_tpg_cmd_1_tdata = { scheduler_axi_st_tpg_cmd_tdata[431:216] };

	assign scheduler_axi_st_tpg_cmd_1_tvalid = { scheduler_axi_st_tpg_cmd_tvalid[1] };

endmodule
